### ISSUE TITLE
trace: The attributes of span which generated by the official trace sample can not be listed on zipkin 

### ISSUE THREAD

**Issue by zanghao2** [census-instrumentation/opencensus-go#1002]
**Describe the bug**
trace: The attributes of span which generated by the official trace sample can not be listed on zipkin
span.data.Annotation.attributes can not be listed on zipkin and span.data.attributes is empty
what is the difference between span.data.Annotation and span.data.attributes
**To Reproduce**
1. run a zipkin instance of v2.1.1
2. download sample from https://opencensus.io/quickstart/go/tracing/
3. execute the code

**Expected behavior**
Attributes of annotation can be listed on zipkin as {key ,value} entry

**Additional context**

**Comment by rghetia** [comment]
[Attributes](https://github.com/census-instrumentation/opencensus-proto/blob/e2601ef16f8a085a69d94ace5133f97438f8945f/src/opencensus/proto/trace/v1/trace.proto#L149) are like metadata providing additional information about the trace.
[Annotations](https://github.com/census-instrumentation/opencensus-proto/blob/e2601ef16f8a085a69d94ace5133f97438f8945f/src/opencensus/proto/trace/v1/trace.proto#L178) are timed events with custom description and attributes recorded to capture specific even during the span.
