### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by olivere** [census-instrumentation/opencensus-go#1005]
I'm the maintainer of github.com/olivere/elastic, which is a Go driver for Elasticsearch. As part of that repository, I'm offering (experimental support for) [tracing with OpenCensus](https://github.com/olivere/elastic/blob/release-branch.v6/trace/opencensus/transport.go).

A user of `elastic` recently used [Fossa](https://fossa.com) to check for licensing issues, and it raised two issues that he tracked down to `opencensus-go`, claiming it uses a version of Thrift that had a reference to LGPL-3.0 / LGPL-2.1 in it (see https://github.com/olivere/elastic/issues/1001).

![image](https://user-images.githubusercontent.com/134848/50547659-a78c3480-0c3e-11e9-81eb-319f62c4f4ed.png)

IANAL so I asked on the Fossa Slack if this maybe is a false positive, and Carlos of the Fossa team replied:

> Carlos (FOSSA)
> 
> Depending on which version of Thrift project you were on if it's before 0.9.3 than there were traces of LGPL. It looks like we matched a mention of LGPL in the "Changes" Folder -> https://github.com/apache/thrift/blob/master/CHANGES You can ignore the issue if you're using the latest version.
> 
> CHANGES
> ```
> Apache Thrift Changelog
> 
> Breaking Changes since 0.11.0 [for 0.12.0]:
> --------------------------------------------------------------------------------
>    * [THRIFT-4529] - Rust enum variants are now camel-cased instead of uppercased to conform to Rust naming conventions
>    * [THRIFT-4448] - Support for golang 1.6 and earlier has been dropped.
> ...
> ```
>
> Hope that helps!

Now I just want to get feedback on your standpoint regarding these legal issues. Thanks in advance.

**Comment by mtwo** [comment]
@jparsana uh oh, looks like we need to update a Thrift dependency ASAP

**Comment by sjkaris** [comment]
We should be fine I think, [go.mod](https://github.com/census-instrumentation/opencensus-go/blob/master/go.mod#L5) has thrift pinned to [this commit](https://github.com/apache/thrift/commit/9b75e4fe745a9b08e6ccdc0998ec7a69272f5b4c) which appears to be in between 0.11.0 and 0.12.0. As a side note, we should probably just pin to 0.12.0 now since it was released recently, and includes the commit to which we were previously pinned.

**Comment by rghetia** [comment]
ok.

**Comment by rghetia** [comment]
after #1118 it doesn't depend on thrift anymore.
