### ISSUE TITLE
Update github.com/prometheus/common Version

### ISSUE THREAD

**Issue by ssgelm** [census-instrumentation/opencensus-go#1025]
I am currently packaging this for Debian.  Because of differences in versions, the prometheus tests do not currently pass due to 
https://github.com/prometheus/common/commit/67670fe90761d7ff18ec1d640135e53b9198328f.  That commit has since been reverted at https://github.com/prometheus/common/commit/0c0463831dd744385fd25a8c1a8422b696b5c3c9.  Would it be possible to update the dependency to one that includes that second commit?  That way I can avoid maintaining a local patch.

**Comment by rghetia** [comment]
@ssgelm sure. I'll update the version.
