### ISSUE TITLE
Remove dep files

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#1048]
This is a reminder to remove Gopkg.lock and Gopkg.toml once the community transition into the Go modules. In the meanwhile, we are trying to keep both dep and modules files up-to-date. 

Please note that the version resolution method they use are different hence there might be cases of incompatibilities. IMHO, we should drop support for dep when it happens.

cc @rghetia @bogdandrutu

**Comment by bogdandrutu** [comment]
We never updated these files for a long time. Happy to remove them.

**Comment by rakyll** [comment]
AFAIK, there are still dep users who depend on OpenCensus. I'd prefer update them and keep them around for a little while. GO111MODULE=on, the new default in 1.12, has just been landed. It might be too early to solely depend on the modules.
