### ISSUE TITLE
For long-lived grpc streaming messages, can we add parameters for ocgrpc to control the number of MessageEvents in a single span?

### ISSUE THREAD

**Issue by chuerxiao** [census-instrumentation/opencensus-go#1050]
**Is your feature request related to a problem? Please describe.**
https://github.com/dgraph-io/dgraph/issues/3032

**Describe the solution you'd like**
We add parameters to ocgrpc to control the number of MessageEvents in a single span.
**Describe alternatives you've considered**

**Additional context**

**Comment by chuerxiao** [comment]
Sorry, I see that the latest version is already supported.

```go
const (
	// DefaultMaxAnnotationEventsPerSpan is default max number of annotation events per span
	DefaultMaxAnnotationEventsPerSpan = 32

	// DefaultMaxMessageEventsPerSpan is default max number of message events per span
	DefaultMaxMessageEventsPerSpan = 128

	// DefaultMaxAttributesPerSpan is default max number of attributes per span
	DefaultMaxAttributesPerSpan = 32

	// DefaultMaxLinksPerSpan is default max number of links per span
	DefaultMaxLinksPerSpan = 32
)
```

**Comment by chuerxiao** [comment]
4baeb63 Add option to configure limits for attributes, annotations, message events and links. (#1015)

**Comment by songy23** [comment]
@chuerxiao Does #1015 resolve your issue?

**Comment by songy23** [comment]
Consider resolved, feel free to reopen if you have follow-up questions.

**Comment by chuerxiao** [comment]
We made the dgraph version using the latest opencensus version. The dgraph was run for about two weeks and did not find that the dgraph had a memory leak associated with the trace function.
