### ISSUE TITLE
go.mod: update deps

### ISSUE THREAD

**Issue by broady** [census-instrumentation/opencensus-go#1064]
go.opencensus.io@v0.19.1 still depends on very old versions of Google APIs, resulting in an eventual import of "github.com/golang/lint". See https://github.com/googleapis/google-cloud-go/issues/1359 and https://github.com/golang/lint/issues/436 for background.

```
go.opencensus.io@v0.19.1 google.golang.org/genproto@v0.0.0-20181219182458-5a97ab628bfb
go.opencensus.io@v0.19.1 cloud.google.com/go@v0.34.0
go.opencensus.io@v0.19.1 google.golang.org/api@v0.0.0-20181220000619-583d854617af
```

google.golang.org/api is on v0.2.0
cloud.google.com/go is on v0.37.0

google.golang.org/grpc is on v0.19.0

/cc @jadekler

**Comment by bogdandrutu** [comment]
Trying to do the update in https://github.com/census-instrumentation/opencensus-go/pull/1052 but cannot pass on windows. Any idea? Otherwise we may disable appveyor for the moment.

**Comment by dmitshur** [comment]
There's been progress made in #1052 by dropping the x module, which was causing trouble. But it seems more needs to be done before one can safely do `go get -u` on this module.

Consider that the latest `go.mod` of this module has:

https://github.com/census-instrumentation/opencensus-go/blob/3b8e2721f2c3c01fa1bf4a2e455874e7b8319cd7/go.mod#L11

Yet that module has a problem where it requires `go.opencensus.io@v0.19.1`, see https://github.com/googleapis/google-api-go-client/issues/342.

It seems some coordination will need to happen to resolve the circular problem.
