### ISSUE TITLE
How to export "metrics"/gauges?

### ISSUE THREAD

**Issue by anacrolix** [census-instrumentation/opencensus-go#1080]
I've created a derived gauge, via a metrics.Registry. How do I export it? It's not clear, or documented. Additionally why does the metrics interface differ from all the stuff around measures, it's very unexpected.

**Comment by rghetia** [comment]
@anacrolix Gauges support is incomplete as noted in the release [note](https://github.com/census-instrumentation/opencensus-go/releases). It will be available in 0.20.0 with examples.

**Comment by raulk** [comment]
@rghetia are there any plans for supporting lazily calculated metrics via gauge functions/thunks?

**Comment by rghetia** [comment]
@raulk[ derived gauge ](https://github.com/census-instrumentation/opencensus-go/blob/41e54b832491efe97a2aafe696f6e7d812f136bb/metric/registry.go#L76) provides that.

**Comment by anacrolix** [comment]
@rghetia I can't tell if support has been added. I still can't determine how to export derived gauge metrics. Thanks

**Comment by rghetia** [comment]
> @rghetia I can't tell if support has been added. I still can't determine how to export derived gauge metrics. Thanks

i have an example for [gauge](https://github.com/rghetia/opencensus-go/blob/gauge_example/examples/gauges/gauge.go) and  [derived gauge](https://github.com/rghetia/opencensus-go/blob/gauge_example/examples/gauges/derived_gauge.go ) and derived gauge to export to stackdriver. I will upload the PR sometime this week.

Note: only stackdriver exporter is supported at the moment. Prometheus will be added soon. What exporter are you using?

**Comment by anacrolix** [comment]
@rghetia I'm using Prometheus to export. Here's my export code (no gauges yet): https://github.com/anacrolix/go-libp2p-dht-tool/blob/feat/oc-metrics/main.go#L359.

**Comment by rghetia** [comment]
> @rghetia I'm using Prometheus to export. Here's my export code (no gauges yet): https://github.com/anacrolix/go-libp2p-dht-tool/blob/feat/oc-metrics/main.go#L359.

Prometheus exporter doesn't export gauges yet. When #1040 is fixed, it will support.

**Comment by raulk** [comment]
Can we use a last value view over a measurement in the meantime? Will that be correctly exported to Prometheus?

**Comment by rghetia** [comment]
> Can we use a last value view over a measurement in the meantime? Will that be correctly exported to Prometheus?

yes. It will be [exported](https://github.com/census-instrumentation/opencensus-go/blob/75c0cca22312e51bfd4fafdbe9197ae399e18b38/exporter/prometheus/prometheus.go#L226-L227) as Gauge in prometheus.

**Comment by rghetia** [comment]
[example](https://github.com/census-instrumentation/opencensus-go/tree/master/examples) for Gauge is added and support for exporting metrics is added to
1. logexporter
2. [prometheus](https://github.com/census-ecosystem/opencensus-go-exporter-prometheus)
3. [stackdriver](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/76b193af8427702f23ef781799f45272d43f7475/stackdriver.go#L363-L377)
