### ISSUE TITLE
Print all spans generated in a test

### ISSUE THREAD

**Issue by nhooyr** [census-instrumentation/opencensus-go#1081]
I want to print a text format of all the spans generated in a given test if the test fails. Every test has a root context.

Is there any easy way to do this? It would be huge for test debugging, especially for larger tests.

**Comment by songy23** [comment]
Consider using a print exporter, like the example on https://opencensus.io/exporters/custom-exporter/go/trace/.

**Comment by nhooyr** [comment]
I can't use an exporter per test afaik. Using a print exporter would just make all my tests print their spans, regardless of whether they failed or not.

Maybe I could set an attribute and correlate spans based on that but that seems really janky to me.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
