### ISSUE TITLE
AlwaysSample and NeverSample are confusingly named.

### ISSUE THREAD

**Issue by bmhatfield** [census-instrumentation/opencensus-go#1099]
**Describe the bug**
If you're using an IDE such as VSCode and setting up a sampling policy, you might want to try and disable any sampling behavior to debug why your traces aren't making it to your exporter. You're not sure which methods that control this are available, so you type Sample into your IDE:

<img width="417" alt="Screen Shot 2019-04-08 at 10 07 47 PM" src="https://user-images.githubusercontent.com/1119967/55768461-01c14080-5a4b-11e9-9305-8e48f41c0646.png">

If you're me, "sample" is synonymous with "discard some data", and so you think "well, I _never_ want to do that". But then you'd be wrong 😢 

**Expected behavior**
Perhaps these functions could be renamed to "DiscardAll" and "KeepAll" or something that clarifies their behavior. I don't feel that the comments are sufficient, as only the warning about sending too much data in an active production system provides a tractable clue for someone who thinks "sample" is somewhat synonymous with "discard" rather than "keep".

I realize for API stability reasons this is a challenging change to make. I'd like to encourage you to consider it anyways for the sake of (perhaps silly, but extant) folks who think of "sampling" as "discarding" rather than "keeping".

**Comment by rghetia** [comment]
@bmhatfield When I think of "sampling" it mean pick a few from a large pool of items and check it out. It is like food sample in grocery store or a piece of carpet as a sample, etc. It is like picking tiny portion to inspect that would represent the large group. From that perspective, the names are quite appropriate.
Let me know if you are still not convinced ;-)

**Comment by rghetia** [comment]
#wontfix: I am closing this issue. If more discussion is required then please open an issue in spec repo as this defined in the spec and it is not specific to Go implementation.

**Comment by bogdandrutu** [comment]
@bmhatfield what do you think about these new names:
```proto
// Sampler that always makes a constant decision on span sampling.
message ConstantSampler {
  // How spans should be sampled:
  // - Always off
  // - Always on
  // - Always follow the parent Span's decision (off if no parent).
  enum ConstantDecision {
    ALWAYS_OFF = 0;
    ALWAYS_ON = 1;
    ALWAYS_PARENT = 2;
  }
  ConstantDecision decision = 1;
}
```

**Comment by bmhatfield** [comment]
@rghetia I expected this to be in the territory of #wontfix/#cantfix, but please consider my response below to @bogdandrutu

@bogdandrutu I don't mean to be obtuse here, but I think the word "sampling" is a bit of a [contronym](https://www.merriam-webster.com/dictionary/contronym) - as @rghetia illustrates, it's possible to use it in context to mean "keep" (selecting a blueberry at the grocery store), or to mean "discard" (adding sampling to a process begins discarding some events).

If you see what I mean about it being a sort-of contronym, then "ALWAYS_ON" and "ALWAYS_OFF" require additional context to determine if it means "keep" or "discard", and so some additional contextual clues in those names (or the message surrounding them) would be helpful!

**Comment by bogdandrutu** [comment]
Maybe something like:
```proto
// Sampler that always makes a constant decision on span sampling.
message ConstantSampler {
  // How spans should be sampled:
  // - Always off
  // - Always on
  // - Always follow the parent Span's decision (off if no parent).
  enum ConstantDecision {
    KEEP_ALL = 0;
    DISCARD_ALL = 1;
    KEEP_PARENT_DECISION = 2;
  }
  ConstantDecision decision = 1;
}
```
