### ISSUE TITLE
stats, trace: add benchmarks

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#111]
Add stats benchmarks, start with the gRPC benchmarks with the stats instrumentation turned on.

**Comment by odeke-em** [comment]
Interesting idea @rakyll, I was just looking at the gRPC benchmarks. Looks like a code heavy task for which we might have to fork a benchmarks repo perhaps for?

**Comment by rakyll** [comment]
We did a first round of contributions that are not captured by this tracking bug:

- https://github.com/census-instrumentation/opencensus-go/pull/467
- https://github.com/census-instrumentation/opencensus-go/pull/474
- https://github.com/census-instrumentation/opencensus-go/pull/301
- https://github.com/census-instrumentation/opencensus-go/pull/464
- https://github.com/census-instrumentation/opencensus-go/wiki/gRPC-Benchmarks
