### ISSUE TITLE
Zipkin exporter is missing bytes sent and received in message events

### ISSUE THREAD

**Issue by alexamies** [census-instrumentation/opencensus-go#1130]
**Describe the bug**
The trace.MessageEvent struct has a field for UncompressedByteSize:

https://godoc.org/go.opencensus.io/trace#MessageEvent

but those are not included in the Zipkin exporter

https://github.com/census-instrumentation/opencensus-go/blob/master/exporter/zipkin/zipkin.go#L184

**To Reproduce**
Need PR #1129 (https://github.com/census-instrumentation/opencensus-go/pull/1129)

1. Run the Go HTTP integration example
https://opencensus.io/guides/http/go/net_http/server/

2. Go to Zipkin 
http://localhost:9411/zipkin/

4. Click on a span.
As per the screenshot, all that is shown is 'SENT' or 'RECV'
![zipkin_no_bytes](https://user-images.githubusercontent.com/5554156/56670255-61346880-6667-11e9-94b5-24024dbeb40c.png)

**Expected behavior**
The number of bytes sent and received.

**Additional context**
These should be included and it is very important in determining why one trace might be taking longer than another trace. I submit a PR to fix the issue.

**Comment by rghetia** [comment]
zipkin exporter has its own repo now. So opened it there. https://github.com/census-ecosystem/opencensus-go-exporter-zipkin/issues/6

**Comment by alexamies** [comment]
Addressed by PR here
https://github.com/census-ecosystem/opencensus-go-exporter-zipkin/pull/7
