### ISSUE TITLE
Prometheus Sum aggregation always 0

### ISSUE THREAD

**Issue by eqinox76** [census-instrumentation/opencensus-go#1187]
### What version of OpenCensus are you using?
go.opencensus.io@v0.22.0

### What version of Go are you using?
go1.13 linux/amd64

### What did you do?
Added a measure
```golang
dbLiveness     = stats.Int64("database/liveness", "latency of liveness check to database", "ms")
dbLivenessView = &view.View{
	Name:        "database/liveness",
	Measure:     dbLiveness,
	Description: "latency of liveness check to database",
	Aggregation: view.Sum(),
}
```
Putting in data
```golang
	start := time.Now()
	defer stats.Record(context.Background(), dbLiveness.M(time.Now().Sub(start).Milliseconds()))
```
And exposing it for scraping via prometheus.

### What did you expect to see?
A gauge metric with steadily increasing value.

### What did you see instead?
```
# HELP database_liveness latency of liveness check to database
# TYPE database_liveness counter
database_liveness 0
```

### Additional context
The Distribution and Count aggregations work well. For example with
```golang
dbLivenessView = &view.View{
	Name:        "database/liveness",
	Measure:     dbLiveness,
	Description: "latency of liveness check to database",
	Aggregation: view.Count(),
}
```
I see the expected:
```
# HELP database_liveness latency of liveness check to database
# TYPE database_liveness counter
database_liveness 14
```

I verified that i am putting in measures > 0. That a TYPE counter is reported when using view.Sum() seems also very strange.

Clearly i am defining something wrong and my Sum aggregation gets interpreted as a counter. Any pointers what may be the issue? 

Regards,
Carsten

**Comment by rghetia** [comment]
@eqinox76 which prometheus exporter version are you using? I tried this [example](https://github.com/census-ecosystem/opencensus-go-exporter-prometheus/blob/1d6bc2a7914046e6146ede481471d2801ba34121/example/main.go#L56) after replacing view.Count() with view.Sum() and I do see non zero values.
```
# HELP video_count number of videos processed over time
# TYPE video_count counter
video_count 54
```

**Comment by eqinox76** [comment]
Thanks @rghetia !
by playing with the example i figured out that i was misusing defer and indeed generated only 0 values 
`golang
        start := time.Now()
-       defer stats.Record(context.Background(), dbLiveness.M(time.Now().Sub(start).Milliseconds()))
+       defer func(){
+               t := time.Now().Sub(start).Milliseconds()
+               stats.Record(context.Background(), dbLiveness.M(t))
+       }()
`
Works now with v0.1.0 :
`
# HELP database_liveness latency of liveness check to database
# TYPE database_liveness counter
database_liveness 105
`
Thanks for your time and help!
