### ISSUE TITLE
ochttp public traceparent/tracestate marshal/unmarshal

### ISSUE THREAD

**Issue by slinkydeveloper** [census-instrumentation/opencensus-go#1208]
**NB:** Before opening a feature request against this repo, consider whether the feature should/could be implemented in OpenCensus libraries in other languages. If so, please [open an issue on opencensus-specs](https://github.com/census-instrumentation/opencensus-specs/issues/new) first.

**Is your feature request related to a problem? Please describe.**
I wish to read and write traceparent/tracestate, encoded using [trace context](https://w3c.github.io/trace-context/), without passing an `http.Request`

**Describe the solution you'd like**
Two new methods should be added to [`HttpFormat`](https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ochttp/propagation/tracecontext/propagation.go#L46) or as public functions:

```
SpanContextFromHeaders(traceparent string, tracestate string) (sc trace.SpanContext, ok bool)
SpanContextToRequest(sc trace.SpanContext) (traceparent string, tracestate string)
```

**Describe alternatives you've considered**
AFAIK no alternatives are available in this library, except copy pasting that code in my own code.

**Comment by llhhbc** [comment]
This method has already has in package: `go.opencensus.io/plugin/ochttp/propagation/b3`

```go
HTTPFormat{}

func (f *HTTPFormat) SpanContextFromRequest(req *http.Request) (sc trace.SpanContext, ok bool)

func (f *HTTPFormat) SpanContextToRequest(sc trace.SpanContext, req *http.Request)
```

**Comment by slinkydeveloper** [comment]
What I mean is that I want to extract manually the traceparent/tracestate headers and then i want to pass them to a method, while these two methods interacts already with http request
