### ISSUE TITLE
GRPC Plugin Reports server/client CompletedRpcs to Latency Measure

### ISSUE THREAD

**Issue by smhendrickson** [census-instrumentation/opencensus-go#1214]
This can be found in master:
https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ocgrpc/client_metrics.go#L64
https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ocgrpc/server_metrics.go#L67

Smells like a typo? If so, I'm happy to provide a PR.

AIUI the process should be just adding a new stats var, and fixup tests:
https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ocgrpc/server_metrics.go#L25-L31

**Comment by james-bebbington** [comment]
Yes, this definitely looks like a typo. Please go ahead and create a PR if you need this to be fixed.

**Comment by smhendrickson** [comment]
Thanks James, I've sent a PR. we can go over the details there.
