### ISSUE TITLE
Is opencensus supporting pushgateway?

### ISSUE THREAD

**Issue by Icarus9913** [census-instrumentation/opencensus-go#1254]
I wanna know whether opencensus supports push gateway, cause I did not find anything related in the docs

**Comment by punya** [comment]
OpenCensus doesn't have any built-in support for Prometheus Pushgateway. However, the [OpenCensus Prometheus exporter](https://github.com/census-ecosystem/opencensus-go-exporter-prometheus) uses [Prometheus client_golang](https://github.com/prometheus/client_golang) under the hood, so you can try [configuring a push client yourself](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/push).
