### ISSUE TITLE
Remove rakyll from being an auto-assignee for reviews

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#1255]
I'm being auto-assigned as a reviewer to the incoming PRs even though I can't review/approve them. I also can't remove myself from the reviewers list, leaving Google revoked my admin rights on this org.

Can you remove me to avoid me being auto assigned?

cc @rghetia @nilebox

**Comment by nilebox** [comment]
@punya @jsuereth could you help with this?

**Comment by punya** [comment]
@nilebox I'm working on it already (there's a PR above). You can help by approving #1257 😄

**Comment by rakyll** [comment]
Thanks :)
