### ISSUE TITLE
Is there a function or way to transfor `view.Data` to `WriteRequest`

### ISSUE THREAD

**Issue by jwcesign** [census-instrumentation/opencensus-go#1281]
## What I want?
I want implement my own `remote write` and push data to thanos.
But when I use customer exporter, I get `view.Data`:
```go
func (w *metricsRemoteWriter) ExportView(data *view.Data) {
    ...
}
```

For thanos, it needs struct:
```go
func (h *Handler) receiveHTTP(w http.ResponseWriter, r *http.Request) {
	...
	var wreq prompb.WriteRequest
	if err := proto.Unmarshal(reqBuf, &wreq); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
...
type WriteRequest struct {
	Timeseries []TimeSeries     `protobuf:"bytes,1,rep,name=timeseries,proto3" json:"timeseries"`
	Metadata   []MetricMetadata `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata"`
}
```

Is there a good way to implement it?

**Comment by dashpole** [comment]
You would need to implement this yourself, which would be a significant undertaking to do correctly for the general case.  But you might be able to get enough right that it would work for your use-case.

Alternatively, you could use the OpenTelemetry collector with the [OpenCensus receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/opencensusreceiver) and the [prometheus remote write exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusremotewriteexporter).

Or, you could use the OpenCensus [prometheus exporter](https://github.com/census-ecosystem/opencensus-go-exporter-prometheus), and scrape it with a prometheus server, which can send remote write to thanos.

**Comment by jwcesign** [comment]
Thanks, I use `simpleprometheus` with `prometheus remote write`, it works for me
