### ISSUE TITLE
exporter/stackdriver: missing distribution value for CountAggregation

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#146]
Consider the following view:

```
        view := stats.NewView(
		"my.org/views/video_size_cum",
		"processed video size over time",
		nil,
		videoSize,
		stats.CountAggregation{},
		stats.Cumulative{},
	)
```
It fails with:

2017/11/21 14:52:52 Failed to export to Stackdriver Monitoring: rpc error: code = InvalidArgument desc = Request was missing field timeSeries[0].points[0].distributionValue.

**Comment by rakyll** [comment]
This case happens if the measure descriptor is already created to represent a distribution value.

@songy23, what's our strategy here? We will just fail with this error?

**Comment by songy23** [comment]
In Java we keep track of all the views that are registered previously. If the exporter gets a view that has a registered name but with different attributes (e.g different aggregations), we will just skip and log it: https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerThread.java#L85.
