### ISSUE TITLE
Provide View related APIs as View methods

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#15]
Currently the stats API contains quite a few package-level APIs works primarily with a View instance.

```
func RegisterView(v View) error
func RetrieveData(v View) ([]*Row, error)
func StopForcedCollection(v View) error
func SubscribeToView(v View, c chan *ViewData) error
func UnregisterView(v View) error
func UnsubscribeFromView(v View, c chan *ViewData) error
```

They could instead accept a View as a receiver. There are two advantages: (a) some function names will be shorter because we will be able to drop the "View" suffix from their names, (b) godoc will render them under the View type and it is easy for their discoverability.

```
func (v View) Register() error
func (v View) RetrieveData() ([]*Row, error)
func (v View) StopForcedCollection() error
func (v View) Subscribe(c chan *ViewData) error
func (v View) Unregister() error
func (v View) Unsubscribe(c chan *ViewData) error
```

Happy to send a PR.

/cc @acetechnologist @bogdandrutu

**Comment by acetechnologist** [comment]
I had that originally but I changed it to make the library code cleaner/easier to follow

With the methods as they are now we have a tree dependency graph:
Methods --dependOn--> Worker --dependOn--> Views/Measures

With the methods attached  the Views/Measures instead, we create a circular dependency graph:
Worker --dependOn--> Views/Measures --dependOn--> Worker ...

I prefer the linear dependencies as it makes it easier to reason about the code and to maintain it down the road.

Adding @jcd2 for his opinion/preference as starting next week he'll become the main owner of all this code.

**Comment by rakyll** [comment]
Closed via https://github.com/census-instrumentation/opencensus-go/commit/76e3d89057cdbcb76b496079933563e168513620.
