### ISSUE TITLE
exporter/stackdriver: Support custom MonitoredResource labels

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-go#166]
For now the Stackdriver Stats Exporter will always use a global MonitoredResource with no associated labels: https://cloud.google.com/monitoring/api/resources#tag_global.

In the next version we may consider allowing users to set custom labels (e.g GCE instance-id) for their MonitoredResource in the exporter.

**Comment by odeke-em** [comment]
Milestone moved since @songy23 is rocking this already with a PR.
