### ISSUE TITLE
exporter/prometheus: implement one

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#168]
Assigned to me by @rakyll, this issue is a placeholder for that exporter.

**Comment by rakyll** [comment]
Thanks for this tracking bug!

I was explaining the other day what the API may look like:

```
package prometheus

type Exporter struct {} ...

func (e *Exporter) Handler() http.Handler {}
```

**Comment by odeke-em** [comment]
@rakyll I am going to close this issue since the  first version of the exporter was implemented. Any bugs that we find can be independently reported.
