### ISSUE TITLE
exporter/stats/stackdriver: key sanitization issues

### ISSUE THREAD

**Issue by jcd2** [census-instrumentation/opencensus-go#173]
Keys have to start with a letter, they can't start with a digit or underscore.  We could sanitize in those cases by adding "key_" or some other string at the front.

The key should be sanitized in the equalAggWindowTagKeys check -- otherwise when we read back the MetricDescriptor it won't appear to be compatible with the view.

A more subtle issue is that sanitizing two different tag keys in a view could result in the same label, which could cause the CreateMetricDescriptor and CreateTimeSeries calls to fail.  To fix it we'd have to use a sanitization scheme that applied to the whole set of tag keys and avoided duplicates.

**Comment by rakyll** [comment]
Also, make sure the key size is still equal or below the allowed limit after sanitization.

**Comment by odeke-em** [comment]
So for the checks

Check | Completed | Source Code
---|---|---
Keys have to start with a letter, they can't start with a digit or underscore. We could sanitize in those cases by adding "key_" or some other string at the front. | Yes | https://github.com/census-instrumentation/opencensus-go/blob/41d5f3842541ca8c85e96e15688ef0472d2daaf2/internal/sanitize.go#L33-L39
Keys should be sanitized in the equalAggWindow | Yes | https://github.com/census-instrumentation/opencensus-go/blob/41d5f3842541ca8c85e96e15688ef0472d2daaf2/exporter/stats/stackdriver/stackdriver.go#L494-L497
Also, make sure the key size is still equal or below the allowed limit after sanitization. | Yes | https://github.com/census-instrumentation/opencensus-go/blob/41d5f3842541ca8c85e96e15688ef0472d2daaf2/internal/sanitize.go#L30-L32
A more subtle issue is that sanitizing two different tag keys in a view could result in the same label, which could cause the CreateMetricDescriptor and CreateTimeSeries calls to fail. To fix it we'd have to use a sanitization scheme that applied to the whole set of tag keys and avoided duplicates.| No |

We are only left with one check on that wishlist of sanitization i.e.
`
A more subtle issue is that sanitizing two different tag keys in a view could result in the same label, which could cause the CreateMetricDescriptor and CreateTimeSeries calls to fail. To fix it we'd have to use a sanitization scheme that applied to the whole set of tag keys and avoided duplicates.
`
which we can do by perhaps a sanitization method that memoizes its previously sanitized keys and would be invoked as a first time key sanitization method, returning an error if something failed.

**Comment by odeke-em** [comment]
I've sent https://github.com/census-instrumentation/opencensus-go/pull/283 which will fix this.

**Comment by ramonza** [comment]
Stackdriver exporter is no longer in this repo. Looks like this issue was addressed anyway, so closing.
