### ISSUE TITLE
stats: clearRows called incorrectly

### ISSUE THREAD

**Issue by jcd2** [census-instrumentation/opencensus-go#183]
At the end of reportUsage, clearRows is being called for views with Interval windows, but this means intervals will only contain data since the last export.  (And it's being called for Cumulative windows too, because the type assertion is *Cumulative instead of Cumulative.)

I think we should delete the call to clearRows for now, and add a TODO to implement a garbage-collection scheme instead.

**Comment by odeke-em** [comment]
Am assuming we should tie these issues together https://github.com/census-instrumentation/opencensus-go/issues/184, that is #184 is the precursor to this one?

**Comment by rakyll** [comment]
I agree that we should tie them, we can update https://github.com/census-instrumentation/opencensus-go/issues/184 with the details explained here and close this as a duplicate.

**Comment by ramonza** [comment]
Going to leave this for the stats changes that @rakyll is working on

**Comment by rakyll** [comment]
clearRows is only called to cleanup the collection for cumulative windows at unsubscription, we can close it now.
