### ISSUE TITLE
exporter/stats/prometheus: metric collection time

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#185]
We are currently using the Collector API provided by the Prometheus Go package but it is not clear if it is possible to timestamp the collected metrics via it. Investigate whether we can use (ViewData).Start and (ViewData).End timestamps instead of letting collector time-stamping the recordings.

/cc @odeke-em

**Comment by odeke-em** [comment]
So I was reading from the Prometheus "Writing exporters" page at https://prometheus.io/docs/instrumenting/writing_exporters/
and they talk about using
https://github.com/prometheus/pushgateway or https://godoc.org/github.com/prometheus/pushgateway
https://prometheus.io/docs/practices/pushing/

if we want to set the timestamps our selves
<img width="1116" alt="screen shot 2017-11-30 at 3 29 37 pm" src="https://user-images.githubusercontent.com/4898263/33458409-51783cd4-d5e3-11e7-88da-d0064eb8fbd2.png">

**Comment by odeke-em** [comment]
The other seemingly plausible option is to use, `WithLabels` for Histograms and Summaries:

* https://godoc.org/github.com/prometheus/client_golang/prometheus#HistogramVec.WithLabelValues 
* https://godoc.org/github.com/prometheus/client_golang/prometheus#SummaryVec.WithLabelValues 

For example:
```go
// For prometheus.HistogramVec
histogramVec.WithLabelValues("start_time").Observe(vd.Start.Unix())
histogramVec.WithLabelValues("end_time").Observe(vd.End.Unix())

// For prometheus.SummaryVec
summaryVec.WithLabelValues("start_time").Observe(vd.Start.Unix())
summaryVec.WithLabelValues("end_time").Observe(vd.End.Unix())
```

**Comment by rakyll** [comment]
For cumulative windows, we don't need this to be done right now. I am moving the issue to R2, so we can come back at it when we are thinking about the interval support.

**Comment by rakyll** [comment]
Given we are not considering to support interval views from the Prometheus exporter, I am closing this issue for now.
