### ISSUE TITLE
exporter/promethues: wrong count data

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#188]
Prometheus exporter currently adds the CountData to an existing counter. CountData is already the aggregated count. We should only add the difference between since last Collect.

```
counter := sc.(prometheus.Counter)
counter.Add(float64(*data))
```

/cc @odeke-em

**Comment by rakyll** [comment]
An easier fix looks possible via NewConstMetric, will send a change.

**Comment by odeke-em** [comment]
Interesting that these fixes require usage of New*Metric
