### ISSUE TITLE
exporter/prometheus: DistributionData is not observed

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#189]
We need to observe the DistributionData for the DistributionAggregation. We are currently observing the boundaries of the distribution.

Since we only keep the aggregated data in memory, this seems to be impossible to implement by using the Histogram type.

/cc @odeke-em

**Comment by rakyll** [comment]
We just need to use NewConstHistogram, sending a change soon.

**Comment by odeke-em** [comment]
Cool, thanks.

**Comment by rakyll** [comment]
Closed via https://github.com/census-instrumentation/opencensus-go/commit/a7bfe253256f6623febf0eda458222389ba5a1ce.
