### ISSUE TITLE
Move the code snippets from README to godoc

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#19]
Go provides [testable examples](https://blog.golang.org/examples). Move the snippets to the godoc examples. In the alpha stage, while the APIs are being broken often, it will help us to keep the examples up to date.

**Comment by acetechnologist** [comment]
Sounds good to me.
/cc @jcd2 @bogdandrutu for input

**Comment by bogdandrutu** [comment]
Having examples always up to date is great. I think this is a good idea.

**Comment by rakyll** [comment]
I need we can keep both. I am suggesting to use a tool like [embedmd](https://github.com/campoy/embedmd/) to generate the README with up-to-date examples that compiles all the time.
