### ISSUE TITLE
remove golang.org/x/net/context from all non gRPC packages

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#199]

**Comment by odeke-em** [comment]
Thank you for the ping @rakyll. So I am curious, do we run the risk of this code not being able to run on Google App Engine? Please see https://github.com/GoogleCloudPlatform/golang-samples/pull/323#issuecomment-334817771 in which @jba cautions about this.

**Comment by rakyll** [comment]
We currently already don't support 1.6. There are some files importing the wrong package. We should import context from the standard library everywhere where possible.

**Comment by odeke-em** [comment]
Aye aye, roger that!
