### ISSUE TITLE
stats: start time in ViewData

### ISSUE THREAD

**Issue by jcd2** [census-instrumentation/opencensus-go#200]
For views with a cumulative window, this should be the time from which the data has been accumulated.

**Comment by jcd2** [comment]
This fix wasn't correct -- the current time is still needed to be passed to View.collectedRows, and "start" is being overwritten inside the loop, leaving it with a different value for the next view.

I would put "now" back as the name of the input parameter of worker.reportUsage, not modify it inside the function, and compute "start" for each view, as a variable defined inside the loop.

**Comment by rakyll** [comment]
We can close this now, start time is always returned as the beginning of the collection for cumulative windows and we only have cumulative windows now.
