### ISSUE TITLE
exporter/stats/stackdriver: name metrics consistently

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#209]
OpenCensus Java names the metric descriptors in the form of:

```
OpenCensus/grpc.io/rountrip_latency/cumulative
```

We use lowercase "opencensus" as a prefix. Fix the inconsistency problem.

**Comment by odeke-em** [comment]
Thanks for creating this issue @rakyll, in deed. For posterity here is what @rakyll is referring to https://github.com/census-instrumentation/opencensus-java/blob/2b464864e3dd3f80e8e4c9dc72fccc225444a939/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java#L89
vs what the Go client does
https://github.com/census-instrumentation/opencensus-go/blob/2237b123f1e72228dd0bbe11fb038462d15f6fbb/exporter/stats/stackdriver/stackdriver.go#L329

PR coming up shortly.
