### ISSUE TITLE
Remove ValueAsString?

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#21]
```
func (k *KeyString) ValueAsString(b []byte) string
```
is not accessing any of the Key fields and is doing a redundant job of casting a []byte into string.

/cc @acetechnologist

**Comment by rakyll** [comment]
I understand now that this is there if the Key implementation want to provide a custom serializer for the value.

**Comment by acetechnologist** [comment]
Yes. For example when KeyInt64 and KeyBool are added they will need to have their own: ValueAsString(b []byte) string.
Which is not just a casting. For example:
For KeyInt64 []byte { 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1} could return "3"
For KeyBool []byte { 0 } could return "False"
For KeyBool []byte { 0 } could return "True"

**Comment by rakyll** [comment]
I will add more godoc to explain what it does instead.
