### ISSUE TITLE
plugin/grpc/grpcstats: views should be consistent with the Java views

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#210]
There are some inconsistencies in the views we are providing from the grpcstats package with what Java provides.

For example, grpc.io/client/error_count/cumulative is a mean aggregation in Java, a count aggregation in Go.

Use https://github.com/census-instrumentation/opencensus-java/blob/master/contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java as a reference to find out the mismatching cases and fix them.

**Comment by odeke-em** [comment]
Roger that, I sent a PR #217, PTAL.
