### ISSUE TITLE
stats: improve DistributionData.multiplyByFraction

### ISSUE THREAD

**Issue by jcd2** [census-instrumentation/opencensus-go#221]
DistributionData.multiplyByFraction currently ignores the fraction.  Changing it to keep min, max, and mean the same but scale the other values by the fraction would improve ViewData for interval views.

**Comment by songy23** [comment]
I remember we had a cross-language discussion about this long time ago, and the conclusion was to not scale stats in DistributionData by fraction, and that's the case for Java and C++ implementations.

**Comment by rakyll** [comment]
I am closing this issue given this is not the behavior in other languages. Cross-language improvements can be filed against the specs repo, https://github.com/census-instrumentation/opencensus-specs.
