### ISSUE TITLE
plugin/grpc/grpcstats: error tag values

### ISSUE THREAD

**Issue by jcd2** [census-instrumentation/opencensus-go#222]
The tag value for rpc status is the full text of the error, but it should just be a string of the error code.

**Comment by rakyll** [comment]
The view tags used in the grpcstats package don't match with the tags used in other languages for the same views.

@odeke-em, can you make the Go ones consistent with the Java? See https://github.com/census-instrumentation/opencensus-java/blob/master/contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java for reference.

**Comment by odeke-em** [comment]
SGTM! Let me jump on that.

**Comment by rakyll** [comment]
I assigned this to myself and working on it!
