### ISSUE TITLE
trace: API is hard to navigate

### ISSUE THREAD

**Issue by jba** [census-instrumentation/opencensus-go#230]
This is an experience report. Yesterday was my first time actually using the trace API. My goal was to add spans to some top-level methods in the Cloud Spanner client (cloud.google.com/go/spanner).  I ended up with [this CL](https://code-review.googlesource.com/c/gocloud/+/20550).

Since I wanted my spans to follow the shape of the call stack, I looked for a way to implement the pattern
```
func foo() {
    // start a child span
    // defer ending that span
}
```
I had trouble finding the right first line. With `StartSpan`, `Span.StartSpan` and `NewSpan` all providing similar functionality, I wasn't sure which to choose. I ended up with
```
ctx = trace.StartSpan(ctx, name)
defer trace.EndSpan(ctx)
```
which I assume is the intended approach, but it took me a while to find it.

I think there should be package-level documentation and examples that explain common use cases. I started this in #229.

Also, I suggest removing rarely-used convenience methods. This package will itself be used infrequently. Many "convenience" methods will be lucky if they are called once in a thousand lines of code, provide little convenience, and clutter the API, making it hard to find useful functions. Some suggestions:

  - Remove AddLink, AddMessageReceiveEvent, AddMessageSendEvent, IsRecordingEvents, IsSampled, SetSpanAttributes, SetSpanStatus, SetStackTrace, SpanContextFromContext. These can all be trivially expressed as `trace.FromContext(ctx).XXX()`.

  - Remove `StartSpanWithOptions`. I may be biased, but while `StartSpan` may be used relatively frequently to add a child span to an existing trace, I don't see that anyone using it for that purpose would want to change sampling or recording decisions. (If they do, they can still use `FromContext(ctx).StartSpanWithOptions`.)

  - Add `Printf(ctx, attrs, format, args...)` and remove all other related functions and methods. (I anticipate that this will be used a lot for this package, but that is still rarely, so writing an extra 'nil' for the attributes is not a big deal.) Add `Span.Annotate(message, attrs)` as a low-level way to add an annotation. (This assumes that the current `LazyPrintf` implementation, which calls `fmt.Sprintf` after checking `IsRecorded`, is correct. If it isn't and you intend to defer the `Sprintf` until later, then have a top-level `LazyPrintf` with the same signature and a related `Span` method.)

  - Remove `Attribute` and its implementations. Let callers provide a `map[string]interface{}` for attributes. In addition to shortening the API, there are other advantages:

    - Users will actually type less if they have more than one or two attributes. Compare `map[string]interface{}{"key1": num, "key2": str}` with `trace.Int64Attribute{"key1": int64(num)}, trace.StringAttribute{"key2", str}`

    - You can accept more value types. For example, as shown above, you can accept `int` instead of   making the user write a cast.

    - Consistency with `Link`, which has an `Attributes` field of type `map[string]interface{}` that the user must fill in.

    I understand the desire for compile-time type safety, but I believe the cost is too great for the benefit here. Since this is fundamentally a reporting API, there is no serious harm if you take a value that is not an int, bool or string and call `fmt.Sprint` on it (or better, `fmt.Sprintf("%#v", val)`. That is still likely to be useful to a human reader.

  - Move ActiveSpans, ConfigureBucketSizes, ErrorSampledSpans, LatencySampledSpans, SampledSpansSummary, BucketConfiguration, LatencyBucketSummary and PerMethodSummary to another package. They don't feel like they're part of this one.

**Comment by odeke-em** [comment]
Thank you @jba for the input, great ideas and points.
Also thank you for starting the `trace/doc.go` PR in #229!
In regards to the Printing APIs, @rakyll had similar thoughts and had opened https://github.com/census-instrumentation/opencensus-go/issues/129.

I'll digest and think about your input and work on something related to your suggestions with the other team members.

**Comment by jba** [comment]
One point I'd like to make: I would recommend valuing Go taste and idioms over consistency with other languages. That's how we work on the Google Client Libraries team: each language builds the best client for that language. I mention that because it seems like some of the design might be coming from Java or other languages where convenience is valued over simplicity. That's a fine tradeoff, but Go typically does the opposite.

**Comment by odeke-em** [comment]
I agree @jba, and thank you for the tips. In deed, we are working to improve the APIs as we progress and hopefully in the near future, we'll roll something out.

**Comment by rakyll** [comment]
Closed via https://github.com/census-instrumentation/opencensus-go/pull/287.

**Comment by ramonza** [comment]
I would like to re-open this because I think some of the issues are still not addressed, in particular:

> Move ActiveSpans, ConfigureBucketSizes, ErrorSampledSpans, LatencySampledSpans, SampledSpansSummary, BucketConfiguration, LatencyBucketSummary and PerMethodSummary to another package. They don't feel like they're part of this one.

>Remove Attribute and its implementations. Let callers provide a map[string]interface{} for attributes. In addition to shortening the API, there are other advantages:

**Comment by rakyll** [comment]
We are closing this because introspection related functions are moved.
