### ISSUE TITLE
README: update section "Creating an aggregation" to document the types of aggregations available

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#232]
So PR https://github.com/census-instrumentation/opencensus-go/pull/220 documented in the `stats/doc.go` file that we support not just count and distribution aggregations but also sum and mean. However, the README now contains stale information https://github.com/census-instrumentation/opencensus-go#creating-an-aggregation
<img width="1054" alt="screen shot 2017-12-11 at 1 21 18 pm" src="https://user-images.githubusercontent.com/4898263/33852055-391fed8a-de76-11e7-821e-b57488a54caa.png">
 
Could we update this please? /cc @songy23 @rakyll

**Comment by songy23** [comment]
Sure, I can update that in a minute.
