### ISSUE TITLE
exporter/stats/prometheus: support interval windows

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#234]
This is a tracking bug for the interval window support for the Prometheus exporter.

**Comment by odeke-em** [comment]
I think this issue is blocked on https://github.com/census-instrumentation/opencensus-go/issues/185 or at least the research related to it for example https://github.com/census-instrumentation/opencensus-go/issues/185#issuecomment-348342508

**Comment by rakyll** [comment]
(I am closing this for the reasons explained above and will open it ever becomes a valid case to upload interval data to Prometheus.)
