### ISSUE TITLE
stats: split package into two

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#237]
To improve the usability, we should consider splitting the stats package into two:

- stats: views and exporters
- stats/measure: measures and measurement

This split allows third party code owners to focus on the stats/measure package and scope the API surface they have to understand. For users who cares about the export path, include everything else in the stats package.

With this distinction, we will be able to explain the core concepts to different audiences more easily.

**Comment by rakyll** [comment]
This split requires a lot of reorganization of the internals and I am not sure if we have enough time in R2 to work on this change. Beyond R2, it will be considered a significant API breakage.

**Comment by ramonza** [comment]
It seems like part of #230 is to suggest a similar splitting by audience for trace:
> Move ActiveSpans, ConfigureBucketSizes, ErrorSampledSpans, LatencySampledSpans, SampledSpansSummary, BucketConfiguration, LatencyBucketSummary and PerMethodSummary to another package. They don't feel like they're part of this one.

**Comment by rakyll** [comment]
I tried a few different strategies to split this package and couldn't find a good way so far without publicizing many internal types. I am going to close this issue right now because I am not actively working on it apart from some improvements that might land via https://github.com/census-instrumentation/opencensus-go/pull/315.
