### ISSUE TITLE
Unsafe code isn't executable in AppEngine Standard

### ISSUE THREAD

**Issue by clanstyles** [census-instrumentation/opencensus-go#239]
We're trying to use Google Spanner and the driver depends on this package. ```go.opencensus.io/internal/tagencoding/tagencoding.go``` contains unsafe code, and AppEngine wont execute it.

**Comment by rakyll** [comment]
Removing the dependency to unsafe.

**Comment by jcd2** [comment]
oh, bdrutu asked me to do it a little while ago.

**Comment by jcd2** [comment]
should be fixed by #240 

Let us know if you have any other problems using this with App Engine.

**Comment by clanstyles** [comment]
@jcd2 thank you for the prompt fix! Seems to be working great!
