### ISSUE TITLE
plugin/grpc/grpcstats: method should include both service and method name

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#245]
Currently, the grpcstats package attaches service name and method name separately to the tags. Instead, we should concatenate them in the following format and only populate the method name tag.

```
[service]/[method]

Example:
helloworld.Greeter/SayHello
```

**Comment by odeke-em** [comment]
Interesting.

**Comment by songy23** [comment]
FYI this is what gRPC did for Java:
https://github.com/grpc/grpc-java/blob/4c483ef7a0434fd4a703fdeb9e5031a89fca89e3/core/src/main/java/io/grpc/internal/CensusStatsModule.java#L672 and https://github.com/grpc/grpc-java/blob/4c483ef7a0434fd4a703fdeb9e5031a89fca89e3/core/src/main/java/io/grpc/internal/CensusStatsModule.java#L332

**Comment by rakyll** [comment]
@songy23, should we tag with the full name instead? That's what the Java implementation is doing. The full name contains a `/` as a prefix. I don't see views exported from Java to Stackdriver contains a `/` as a prefix.

**Comment by songy23** [comment]
That's a long story: in gRPC Java the full method name doesn't have a `/` prefix, while previously gPRC C++ and Go have the leading `/`, but we later agreed that it should be omitted. 

So in gRPC Java, the full method name will always be "service/method", while in C++ and Go it will be "/service/method", and we need to manually remove the leading `/`.
