### ISSUE TITLE
exporter/stats/stackdriver: enforce singleton on exporter per process

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-go#258]
Each process should have at most one running Stackdriver exporter.

**Comment by odeke-em** [comment]
@songy23 what's your definition of a "process"? Do you mean that on program start the following
```go
stats.RegisterExporter(exp1)
stats.RegisterExporter(exp2)
stats.RegisterExporter(exp3)
```
where exp1, exp2, exp3 are *stackdriver.Exporter instances

that only exp1 should be registered?

**Comment by rakyll** [comment]
We shouldn't have more than one Stackdriver exporter per GCP project ID in the lifetime of a Go process. stackdriver.NewExporter can return an error if user wants to construct more than one.

**Comment by songy23** [comment]
@odeke-em That's right, if there are more than one exporter exporting to Stackdriver within one process, Stackdriver will start to return error due to race conditions.

**Comment by odeke-em** [comment]
Awesome, thanks y'all for the clarifications. I'll submit the PR in a second.

**Comment by odeke-em** [comment]
I've mailed https://github.com/census-instrumentation/opencensus-go/pull/264, PTAL.

**Comment by odeke-em** [comment]
@songy23 and @rakyll what do think we should do on an empty projectID ""? I'd say stay strict and not allow more than one Exporter per process as well.

**Comment by rakyll** [comment]
@odeke-em reject empty project IDs.

IMHO, it is still useful to support multiple exporters for those who want to export to multiple GCP projects.

**Comment by odeke-em** [comment]
@rakyll:
1. sure, I'll reject empty ProjectIDs upfront 
2. Totally agree, reject NewExporter with the same ProjectID but allow multiple invocations with unique ProjectIDs

**Comment by odeke-em** [comment]
I've incorporated the feedback in there, y'all. PTAL.
