### ISSUE TITLE
README: add snippets for the tracing package

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#259]
It would be good to have a few snippets to demonstrate how to create a span, add some annotations, end it.

**Comment by odeke-em** [comment]
Just a random idea: Could we perhaps make fully fledged applications or microservices and add tracing and metric collection to them? That way we can actually point people to show them how to use our package lest there is the mindblock of them having to figure out how to integrate the app by themselves. I also believe that this is DevExp improvement and could even be translated into a blog post/talk.

**Comment by freddygv** [comment]
Hi, @odeke-em! I'd like to take a stab at this next. So basically the goal is a non-trivial example that incorporates multiple features of OpenCensus, right? (various measures, views, and traces)

**Comment by freddygv** [comment]
Actually @odeke-em I just came across this draft of yours: https://medium.com/@odeke_et/3636820d98c8 

Does that mean you're already working on this issue?

**Comment by odeke-em** [comment]
@freddygv ahah interesting that you found that URL, I wonder how? I actually just published it a few hours ago, please see https://twitter.com/orijtech/status/971890040304480257.

That was a comprehensive example though. I believe @rakyll already worked on this with https://github.com/census-instrumentation/opencensus-go/pull/507.

**Comment by rakyll** [comment]
We can close this issue, we have enough examples already.
