### ISSUE TITLE
trace: support Trace context header

### ISSUE THREAD

**Issue by mhindery** [census-instrumentation/opencensus-go#285]
We are currently using https://godoc.org/cloud.google.com/go/trace for tracing a microservice to Stackdriver. Seeing as it is declared obsolete, we are moving to the replacement package https://godoc.org/go.opencensus.io/trace. These seems to be an important feature for us missing, namely taking over a trace context from an incoming request header. The introduction code after the first example code block on the old package's godoc page describes it:

`Calling SpanFromRequest will create a new trace span for an incoming HTTP request. If the request contains a trace context header, it is used to determine the trace ID. Otherwise, a new trace ID is created.`

This allows to create and link traces crossing boundaries over multiple services. I can't find any similar functionality in the new package, so traces are confined within a single 'program'. Is this intentional? Are we supposed to implement this ourselves by checking and parsing the header and creating new child Spans with custom SpanOptions having set the TraceID and Span ID? I do think this is convenient functionality which is useful enough to be provided out-of-the-box for everybody and like to have it added.

**Comment by rakyll** [comment]
We are working on a vendor agnostic approach to propagate traces via HTTP. Until the multi-vendor support is in, we might provide a Stackdriver-specific utility.

@bogdandrutu, thoughts?

**Comment by rakyll** [comment]
Also please consider taking a look at [httptrace](https://godoc.org/github.com/rakyll/goutil/opencensus/plugin/http/httptrace). It provides a reference how to propagate the header for Stackdriver Trace.
