### ISSUE TITLE
trace: new*Locked function names are misleading and should instead actually lock the mutex inside of them

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#288]
I was just reading through the source code and noticed that we have functions:

https://github.com/census-instrumentation/opencensus-go/blob/0fb819a6f29ea632c158fde21ee508705930c838/trace/trace.go#L688-L699

and 

https://github.com/census-instrumentation/opencensus-go/blob/0fb819a6f29ea632c158fde21ee508705930c838/trace/trace.go#L701-L710

which claim to be `Locked` but nowhere in their bodies do we see them locked. The only mention of locking is in the comments. Later on we see such usage
https://github.com/census-instrumentation/opencensus-go/blob/0fb819a6f29ea632c158fde21ee508705930c838/trace/trace.go#L194-L200

which IMHO is cognitive overload for maintainers and new developers alike. If the name didn't have `Locked` as a suffix, perhaps then it'd be fair game to assume that it wasn't goroutine safe, but `*Locked` as a suffix to me implies a guarantee that the function is goroutine safe. Let's fix this.

**Comment by ramonza** [comment]
Seems like the `Locked` suffix was added to call attention to the need to hold the Mutex before calling these methods. My reading is that it was intentional to avoid locking inside the methods (I assume) to batch two operations under one lock acquisition for efficiency.

**Comment by ramonza** [comment]
@odeke-em can this be closed?

**Comment by odeke-em** [comment]
Sure, @ramonza.
