### ISSUE TITLE
Fast path for stats.Record when no views are impacted

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#302]
When no views are defined for a set of Measures passed to stats.Record, the call is essentially a no-op. If our goal is to encourage pervasive instrumentation, having stats.Record calls throughout your code without any views actually using them should be as close to free as possible. 

In other words, you shouldn't need to pay the cost (or force all users of your library to pay the cost) of metrics collection just because your code is instrumented, but only if you (or your library consumers) actually use that instrumentation (by defining views over it).

**Comment by ramonza** [comment]
Added some very basic benchmarks in #301. stats.Record call with 10 measurements. Note that stats.Record doesn't wait for the views to actually be updated (it's fire and forget to the worker goroutine) so this isn't the full cost.

**Comment by ramonza** [comment]
cc @bogdandrutu

**Comment by ramonza** [comment]
@rakyll this is part of the stats work and will likely be affected (at least) by what you're working on, so I will leave this for now. I have a few thoughts on it that we could discuss at some point.

**Comment by rakyll** [comment]
Can we achieve this with little contention on the critical without having to look up whether measurement has any view subscriptions?

I think the idea is to burn CPU and drop records with additional use of memory (our current strategy) is the only option we currently have to defer this lookup. Are we optimizing something wrong if there is another strategy we haven't discussed?

**Comment by ramonza** [comment]
> Can we achieve this with little contention on the critical without having to look up whether measurement has any view subscriptions?

No, but it should be very fast to look up whether a measurement has any view subscriptions -- subscriptions almost never change so with a copy-on-write strategy this seems like it could be just a single atomic load (of the root data structure holding all views).

**Comment by rakyll** [comment]
Closed via https://github.com/census-instrumentation/opencensus-go/pull/600.
