### ISSUE TITLE
Implement trace exporter for Jaeger

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#308]

**Comment by adriancole** [comment]
current workaround is to use jaeger's zipkin POST endpoint

https://jaeger.readthedocs.io/en/latest/getting_started/#migrating-from-zipkin

**Comment by ramonza** [comment]
Removed the "help wanted" label since @rakyll is planning on doing this

**Comment by rakyll** [comment]
Closed via https://github.com/census-instrumentation/opencensus-go/pull/350.
