### ISSUE TITLE
move everything stackdriver-related under a single package

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#312]
We added Stackdriver trace propagation to the Stackdriver exporter package in #310 and this prompted a discussion that even though propagation and exporting are independent, it is more convenient to have everything related to Stackdriver in one place. 

This avoid a lot of boilerplate initialization when most of the time you want to do all these things at once:
* Set up Stackdriver trace exporter
* Set up Stackdriver stats exporter

**Comment by rakyll** [comment]
This requires an API change given trace.Exporter and stats.Exporter both have Export method with different signatures. I think we should execute on this issue soon. It is becoming harder to break the fundamental APIs as the adoption is growing.

**Comment by odeke-em** [comment]
If we do this for StackDriver, I believe we have to do the same for every other exporter, because:
a) Under exporter/stats, we've got:
* prometheus
* stackdriver
b) Under exporter/trace, we've got:
* stackdriver
* zipkin

If we were to make say: stackdriver.TraceExporter, stackdriver.StatsExporter
then we'd have to do the same for prometheus i.e. prometheus.StatsExporter
and for zipkin: zipkin.TraceExporter

so perhaps our directory layout might become:

```
|- exporters
   |-prometheus
      |-api.go --> StatsExporter
      |-internal
   |-stackdriver
      |-api.go --> TraceExporter, StatsExporter
      |-internal
         |-trace
         |-stats
   |-zipkin --> TraceExporter
```

**Comment by rakyll** [comment]
I didn't understand the case for stackdriver.TraceExporter.

stackdriver.Exporter will be the only type exported which will implement both stats.Exporter and trace.Exporter.

**Comment by rakyll** [comment]
The package organization can be like the following:
```
|- exporter
    |- prometheus -> exports Exporter implements stats.Exporter
    |- stackdriver -> exports Exporter implements stats.Exporter and trace.Exporter
    |- zipkin -> exports Exporter implements trace.Exporter
```

**Comment by odeke-em** [comment]
>I didn't understand the case for stackdriver.TraceExporter.
>
>stackdriver.Exporter will be the only type exported which will implement both stats.Exporter and trace.Exporter.

Gotcha gotcha, makes sense, thanks for the clarification. I was a little hung up on not changing the signatures/name for the various exporters i.e. keeping stats.Exporter as `Export(*stats.ViewData)` and trace.Exporter  as `Export(*trace.SpanData)` but that's a silly thing for me to be hung up on.

The above suggestion would perhaps mean that we then need to declare different signatures for stats.Exporter and trace.Exporter e.g:
* stats.Exporter --> `ExportStats(*stats.ViewData)`
* trace.Exporter --> `ExportTrace(*trace.SpanData)`
