### ISSUE TITLE
Support X-Amzn-Trace-Id HTTP propagation format

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#314]
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html

**Comment by adriancole** [comment]
forgive it being java, but here is work in zipkin (relies on
timestamp-based trace IDs)

https://github.com/openzipkin/brave/blob/master/propagation/aws/src/main/java/brave/propagation/aws/AWSPropagation.java

cc @abhiksingh

**Comment by savaki** [comment]
I've included this in the xray exporter support pr.

**Comment by rakyll** [comment]
Closed via https://github.com/census-instrumentation/opencensus-go-exporter-aws.
