### ISSUE TITLE
stats: New aggregation "Last" to return the last value

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#318]
We need a new aggregation function called "Last" or "Current" that just returns the most recently submitted value. This is needed for gauge-type metrics.

**Comment by rakyll** [comment]
Yes and this needs a spec! We briefly brainstormed about this late last year but haven't addressed it yet. Do you want to open an issue at https://github.com/census-instrumentation/opencensus-specs?

**Comment by ramonza** [comment]
Filed census-instrumentation/opencensus-specs#38

**Comment by rakyll** [comment]
Can we track this via the specs repo? Let's reopen this when census-instrumentation/opencensus-specs#38 is accepted to track the status of the Go implementation.
