### ISSUE TITLE
trace: Annotation and MessageEvent have suboptimal String() output

### ISSUE THREAD

**Issue by danchia** [census-instrumentation/opencensus-go#319]
trace.Annotation and trace.MessageEvent both embed time.Time, but don't override String().
This means they inherit the String() method from time.Time, leading to misleading stringified forms.

Recommend either not embedding time.Time if it's not necessary for the structs to behave like time.Time structs, if not then redefining the String() methods on both.

**Comment by adriancole** [comment]
Nice to see you!

**Comment by danchia** [comment]
Cheers!
