### ISSUE TITLE
stats: Provide an explicit way of flushing to exporters

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#322]
For testing, you need to know when all stats.Record operations have been sent to all exporters. Provide a mechanism that ensures this, perhaps confined/scoped to each Exporter.

**Comment by rakyll** [comment]
Why don't we assume collection is failed if we didn't get the expected data after collection period + some amount of extra time?

**Comment by ramonza** [comment]
This sounds like a reasonable workaround, but it will slow down tests or require very short collection period.
