### ISSUE TITLE
closing a Span multiple times causes it to be re-submitted to Exporter

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#328]
Instead, we should just ignore closing more than once.

**Comment by odeke-em** [comment]
We can also add to each span an endOnce sync.Once field whose .Do method will only be invoked once ever during End.

**Comment by ramonza** [comment]
A related issue that I'm lumping in here is that when you end a span and start a span on the same context, the second span get's added as a child of the first (ended) span.
