### ISSUE TITLE
Setup vanity import paths

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#33]
To reduce to dependencies to a specific git provider and to enhance the the current long and noisy import path, setup a vanity URL for the package and enforce the vanity URL everywhere. The vanity URL is either going to be "go.opencensus.io" or "opencensus.io/go".

**Comment by rakyll** [comment]
We are going with go.opencensus.io.

/cc @tags07 @mtwo

**Comment by rakyll** [comment]
go get go.opencensus.io finally works!

I will document how to deploy the vanity URL server before closing this issue.

**Comment by bogdandrutu** [comment]
Thanks @rakyll.

**Comment by bogdandrutu** [comment]
Probably also to track the update of the documentation and examples to use the vanity import in this issue.
