### ISSUE TITLE
trace.StartSpanWithOptions should use the functional options pattern

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#330]
https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

Something like:
```go
ctx := trace.StartSpanWithOptions(ctx, "span-1", trace.AlwaysSample, trace.RecordEvents)
```

**Comment by rakyll** [comment]
We don't prefer optional patterns anymore. We had a lot of issues with this pattern in the past especially when other libraries wrap our library, they are restricted to provide a a similar-style constructor and it limits them not being able to expose their own option type.

We prefer option structs right now. It is verbose but more more enabling.

(I should write a blog post about functional options to clarify some of the other anti patterns we came up with. For a long time, we suggested this pattern but it is good to document the cons.)

**Comment by derekperkins** [comment]
@rakyll I'd love to hear your experiences with functional options. We've been widely adopting them over the past 6 months.
