### ISSUE TITLE
exporter/trace/stackdriver: revise and fix spanID encoding assumptions

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#333]
So in https://github.com/census-instrumentation/opencensus-go/pull/332 the reporter encountered a spanID that required more than 8 bytes to represent because of our use of binary.PutUvarint. We assumed naturally that we could represent upto `1<<64-1` in 8 bytes, but binary doesn't act that way. It crashes because our buffer was too small, they possibly encountered one that was > `1>>57-1` which requires at least 9 bytes.

The relevant code is
https://github.com/census-instrumentation/opencensus-go/blob/38381063fc2e146b7b20f389e35f505153a89a5b/exporter/trace/stackdriver/stackdriver.go#L222-L229

Taking a look at the spec https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md#span-id
<img width="1201" alt="screen shot 2018-01-19 at 8 32 34 am" src="https://user-images.githubusercontent.com/4898263/35158108-5606fc40-fcf3-11e7-9bbf-56a8dd476e62.png">

which says the hex encoding of the spanID in 8 bytes, something that binary.PutUvarint doesn't offer us.

With the above and the fact that we are using binary.PutUvarint, seems to me that we are wrong to use it plus perhaps overkill with it, and that we could simply do something like this
```go
copy(sc.SpanID[:], fmt.Sprintf("%016x\n", sid)
```
and that should always encode even `1<<64-1` in 8 bytes as expected, faster, simpler and more concisely.

**Comment by rakyll** [comment]
We need to hex encode the span IDs for the incoming and decode for the outgoing from the exporter.

**Comment by rakyll** [comment]
We also shouldn't decode/encode the traceID. I will send a fix soon if you are already not working on one.

**Comment by odeke-em** [comment]
All yours, please go for it, thank you.

**Comment by rakyll** [comment]
Reading the spec again, it doesn't say that trace ID and span ID needs to be kept internally hex encoded. It only gives a few examples and they are hex encoded for readability of the doc. I will ask @bogdandrutu to clarify the spec.
