### ISSUE TITLE
Use prometheus metrics with custom opencensus

### ISSUE THREAD

**Issue by dearcj** [census-instrumentation/opencensus-go#334]
I want to have both my custom opencensus metrics and prometheus metrics like go_memstats at the same time. I'm trying to do some middleware to write from handlers consistently but it seems  both handlers reset repsone bodies
```
http.HandleFunc("/metrics",
		func(w http.ResponseWriter, r *http.Request) {
			promhttp.Handler().ServeHTTP(w,r)
			server.stats.Exporter.ServeHTTP(w,r)
		})
```

**Comment by rakyll** [comment]
Isn't it possible to create a new Writer and buffer the output on it and then, write to the outgoing w?

```
buf := bytes.NewBuffer(...)
promhttp.Handler().ServeHTTP(buf,r)
server.stats.Exporter.ServeHTTP(buf,r)

io.Copy(w, buf)
```

**Comment by dearcj** [comment]
@rakyll It's not that easy, I made my struct over bytes buffer, overwrited Headers function
overwrited Content-length header and it seems the problem is promhttp use gzip comression and opencensus not 

So for now as a solution I will stick to two prometheus jobs with different routing

**Comment by rakyll** [comment]
We haven't considered providing a way to mutually serve these endpoints yet.

Even if we provide some low-level primitives, it seems like Prometheus Go library is not providing any other APIs other than the http.Handler-specific one. For now, we will suggest serving two endpoints. Let's revisit this issue if it is far from ideal.

**Comment by lukmdo** [comment]
```
 import (
+   oprometheus "github.com/prometheus/client_golang/prometheus"
+
...
-   exporter, err := prometheus.NewExporter(prometheus.Options{})
+   exporter, err := prometheus.NewExporter(prometheus.Options{Registry: oprometheus.DefaultRegisterer.(*oprometheus.Registry)})
```
@dearcj @rakyll not sure but perhaps that will help ?

**Comment by Dentrax** [comment]
@lukmdo Thanks for this, you just saved my time!

---

I wonder why this is not documented on https://opencensus.io/quickstart/go/metrics page. (Maybe new option?) It'd be nice to mention `prometheus.Options{Registry: oprometheus.DefaultRegisterer.(*oprometheus.Registry)}` option for awareness and also document the corresponding function of `promhttp.Handler()` -> `prometheus.DefaultGatherer` to people whom not very familiar with opencensus or newcomer like me. (It seems https://github.com/census-instrumentation/opencensus-website/tree/master/content/quickstart/go uncommitted for ~2 years and curious if still up-to-date and maintaining (or moved))

/cc @odeke-em @songy23

**Comment by dashpole** [comment]
@Dentrax The OpenCensus community largely moved to work on OpenTelemetry, so there haven't been many changes over the past 2 years.  New feature work is happening in the opentelemetry-go and opentelemetry-go-contrib repositories.  There is an [OpenCensus bridge](https://github.com/open-telemetry/opentelemetry-go/tree/main/bridge/opencensus#opencensus-bridge) to help you migrate, and a Prometheus exporter which allows [providing your own registerer](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/prometheus/config.go#L68), which is what this issue asks for.
