### ISSUE TITLE
plugin/http/httptrace: do not replace req.URL.Scheme unless it is set

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#335]
httptrace_test.go:231: invalid name: Recv./.e.x.a.m.p.l.e./.u.r.l./.p.a.t.h.?.q.p.a.r.a.m.=.v.a.l.
	httptrace_test.go:226: invalid name: Sent.://127.0.0.1:59761/example/url/path?qparam=val

**Comment by odeke-em** [comment]
@ramonza that code looks like we are invoking strings.Replace with to replace "" with "." for a string that doesn't have a substring. Culprit looks somewhere in plugin/http/httptrace

**Comment by odeke-em** [comment]
And in deed
https://github.com/census-instrumentation/opencensus-go/blob/285e18479bb9cee87377b7eedb34154fd62e786d/plugin/http/httptrace/httptrace.go#L51

https://github.com/census-instrumentation/opencensus-go/blob/285e18479bb9cee87377b7eedb34154fd62e786d/plugin/http/httptrace/httptrace.go#L167

Seems like we expect every URL to have a scheme, but in cases after redirects we might URLs such as "/opencensus" and running that over them is bound to trip out

With a sample illustration here https://play.golang.org/p/pfDgxn2ytbT.
I think we should fix this code by checking first if we have a scheme before trying to do the mass "." replace.

**Comment by odeke-em** [comment]
Thank you @ramonza for finding this bug!

**Comment by rakyll** [comment]
Sending a fix soon.
