### ISSUE TITLE
Use Google Kokoro CI build

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-go#347]
Similar to grpc

**Comment by rakyll** [comment]
We decided to postpone this. At this moment, Travis and Appveyor wait times are not a big deal for OpenCensus Go. They both provide friendly UX and are community-friendly. We are going to reconsider this switch if Travis and Appveyor are not sufficient.

**Comment by rakyll** [comment]
Closing the issue for now.
