### ISSUE TITLE
Add support for "summary" metric type to Prometheus exporter

### ISSUE THREAD

**Issue by falzm** [census-instrumentation/opencensus-go#351]
Currently the Prometheus exporter only supports the Prometheus *histogram* metric type for measuring distribution. Could it be possible to also support the [summary metric type](https://prometheus.io/docs/concepts/metric_types/#summary)? The *histogram* type is [quite difficult to manage](http://linuxczar.net/blog/2017/06/15/prometheus-histogram-2/) (especially regarding bucket sizing).

**Comment by ramonza** [comment]
We need an opencensus-specs proposal for this, so I'm going to close this issue for now.

My opinion on this is that the histogram type is a much better default than summary. Summaries cannot be added together and aggregated, so you cannot get an accurate view across instances of your service for example. Histograms are straightforward to aggregate.

**Comment by ramonza** [comment]
See:  https://prometheus.io/docs/practices/histograms/

**Comment by songy23** [comment]
`Summary` type is added to `Metrics` protos recently, in https://github.com/census-instrumentation/opencensus-proto/pull/110. I think the `Summary` type will be supported in Go once `Metrics` is implemented, so probably don't need a particular issue to track this.
