### ISSUE TITLE
tag.MustKey

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#353]
Provide tag.MustKey that doesn't return an error but panics similar to regex.MustCompile to simplify the common case of global initialization with a static string.

**Comment by odeke-em** [comment]
Thanks @ramonza. How about `tag.MustCreateKey`, `tag.MustKey` feels a little off with the missing verb, as it is must + a noun as opposed to `MustCompile` which is is must + a verb.

**Comment by ramonza** [comment]
An alternative here is that we drop the notion of Key and just use strings. Seems like the purpose of Key is to validate that the string is short enough for transmission. Now that we're considering using tags for multiple purposes other than transmission, e.g. profiler labels (already implemented) and trace attributes (not yet implemented) maybe we need to move the validity checking to serialization time. Also, it seems reasonable that keys would be serialized under a different name than the name they are using in process for reasons discussed in https://github.com/census-instrumentation/opencensus-specs/issues/45.

**Comment by rakyll** [comment]
We are closing it because users can always ignore the returned error for hardcoded valid values or write their own MustKey function.
