### ISSUE TITLE
exporters: split propagation.HTTPFormat implementations from exporters

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#358]

**Comment by odeke-em** [comment]
@rakyll what's the rationale behind this? Seems to me like we are going to end up with an assortment of exporters that implement propagation for their respective backends hence we should keep them as they are, in exporters.

**Comment by adriancole** [comment]
B3 and trace-context are examples of formats that work across different
backends. In-band propagation formats are a bit less opinionated than the
data model.

That said a lot of commerical options.. they are the same right now (hence
trace-context format work going on)

**Comment by odeke-em** [comment]
Thank you @adriancole, I was initially pushing back to the new package but your explanation makes sense and justifies the change, nice!
