### ISSUE TITLE
exporter/stats/prometheus: MeanAggregation should be type Summary

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-go#363]
Currently `MeanAggregation` is converted to a Prometheus [`UntypedValue`](https://github.com/census-instrumentation/opencensus-go/blob/master/exporter/prometheus/prometheus.go#L238). Instead I think it should be type [`Summary`](https://github.com/prometheus/client_golang/blob/master/prometheus/summary.go#L576) with sum and count, but no quantiles.

**Comment by odeke-em** [comment]
@songy23 would you like to work on this?

**Comment by songy23** [comment]
@odeke-em sure I can update this - should be an easy fix.
