### ISSUE TITLE
Make stats exporters pull by default

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#372]
stats exporters are today push by default, with an internal timer that fires every SetReportingPeriod. Instead, we should make stats exporters pull by default because it's much more natural to implement push on top of pull (with an internal timer in the exporter) than the other way round (like we have it now). This should also make testing easier.

**Comment by bogdandrutu** [comment]
Currently the 3 implementations (SD, Prometheus, SignalFX) that we have in OpenCensus 2 use push and one pull. I think for the moment still push makes more sense.

**Comment by ramonza** [comment]
It's not really an issue of what a more common modality is, but which way around is easier to implement. 

The desire here is really:
1. Make it easier to test code that generates stats
2. Remove the global timer

As we discussed yesterday, I think we can achieve that by having an internal stats rollup timer that is not user-configurable  (that will only be used once we improve the stats rollup implementation to buffer updates internally) and moving the submission timers onto the push exporters.

**Comment by rakyll** [comment]
Can we close this issue for now and have a discussion in the specs repo for the future plans?
