### ISSUE TITLE
Calculate span duration using the monotonic clock

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#381]

**Comment by ramonza** [comment]
I thought Go's time package "just worked" when comparing times? https://golang.org/pkg/time/#hdr-Monotonic_Clocks

**Comment by rakyll** [comment]
time uses the monotonic clocks when you use Add, Sub, etc. We export an end time retrieved from time.Now() which is the wall clock. We should calculate the end time by using the monotonic clock.

**Comment by bogdandrutu** [comment]
I agree that all times should be calculated using the monotonic time but I would prefer to keep the API with endtime for consistency with all the other languages.

**Comment by rakyll** [comment]
I don't have strong opinions but will prefer to keep the EndTime field and document that it is calculated by using the monotonic clock.

**Comment by adriancole** [comment]
Ps we have some pretty "interesting" work in brave which tries to keep the
same monotonic+real clock offset for the whole trace. This helps the spans
from not looking crap if ntp shift happens. Locking in this offset at trace
still allows ntp adjustments between traces to be visible. If we locked
larger scope we would end up with same host skew which can happen with
multiple containers
