### ISSUE TITLE
Add attributes to HTTP spans

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#385]
Currently, attributes such as HTTP URL, method, request size, response size and error status are not automatically added to the HTTP spans. Add the attributes and provide support from the exporters.

**Comment by bogdandrutu** [comment]
I would add request size/response size as message events.

**Comment by rakyll** [comment]
I will add a mini spec with all HTTP-specific attributes and how they map to the reserved labels/attributes in tracing backends.
