### ISSUE TITLE
Allow customizing the Stackdriver display name of metrics

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#397]
Currently the display name is constructed as: path.Join("OpenCensus", viewName)

We should support some way to customize this. Putting the name OpenCensus on every view with no way to change it seems a little obnoxious.

Perhaps we need some kind of view metadata that different exporters might support or interpret in different ways.

**Comment by rakyll** [comment]
Why is this a problem?

**Comment by ramonza** [comment]
This was actually implemented in #583
