### ISSUE TITLE
Make Measure a struct

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#400]
Measures looks like it should be a struct with Name, Description and Unit fields.

**Comment by rakyll** [comment]
How does this affect the measure types such as MeasureInt64 and MeasureFloat64?

**Comment by ramonza** [comment]
The least we could do is provide a common type for them to embed. I also dislike that exposing Measure allows anyone to record a value. You only want to expose the name of the measure really, not the ability to record it (that should be private to the module defining the measure).

**Comment by ramonza** [comment]
We prototyped a nice way to do this by making stats.Int64/Float64 return the Measure struct and a record function. The Measure remains public but the record function can be kept private to the declaring package.

**Comment by odeke-em** [comment]
```go
type Measure struct {
    Name string
    Description string
    Value Value
}

type Value interface {
     float64() bool
     int64() bool
}

func Int64Value(i int64) Value { return &int64{v: i} }
func Float64Value(f float64) Value { return &float64{v: f} }
```
and if we want to keep the nice stats.Int64 and stats.Float64 we can too.

**Comment by rakyll** [comment]
@odeke-em Measure is the kind not representing the value. Measurement type is what represents the data points.

@ramonza, are we planning to keep working on this issue? I think the current stats API look decent enough and I wouldn't mind if we close the this.

**Comment by ramonza** [comment]
ok, closing
