### ISSUE TITLE
Consider supporting older versions of Go

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#407]
At least as old as AppEngine supports since that's what google-cloud-go will need (1.6).

**Comment by rakyll** [comment]
We have been told 1.6 support may go away soon (in a few months).

**Comment by odeke-em** [comment]
Interestingly sometime late last year, I spun up https://github.com/census-instrumentation/opencensus-go/pull/227 but it was shutdown as it seems internal Google teams didn't see a need to support it.

**Comment by ramonza** [comment]
might be worth just stubbing out specific APIs on 1.6 to avoid consumers from having to do that

**Comment by odeke-em** [comment]
@ramonza what do you mean by

> might be worth just stubbing out specific APIs on 1.6 to avoid consumers from having to do that

I ask because that's the approach that I used in that PR; build tags in the respective files for Go1.6 and below. I only heard rumors about it and my PR was shutdown without much explanation, but I never ever got a confirmation, that the gRPC folks were planning on dropping Go1.6 support soon.

**Comment by ramonza** [comment]
I don't have the context on that but it looks like that PR makes the library actually work for pre-1.8. I worry that that approach creates a lot of maintenance burden. 

I was asking if there's a way to make a non-functional version of the library, basically just the public functions and methods with empty implementations, work on pre-1.8,  and only of the parts that will be used by libraries (i.e. not exporters, or zpages only the instrumentation code and plugins).

**Comment by rakyll** [comment]
This is a duplicate of an earlier issue and we decided not to proceed. We are trying to move everyone off of these legacy version.
