### ISSUE TITLE
plugin/http/propagation: Should Propagator.FromRequest return (trace.SpanContext, error) instead of (trace.SpanContext, bool)?

### ISSUE THREAD

**Issue by elgris** [census-instrumentation/opencensus-go#408]
Hi everyone!
I'm looking at [Cloud Tracer propagator](https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/http/propagation/google/google.go) and wondering if method
```
func (f *HTTPFormat) FromRequest(req *http.Request) (sc trace.SpanContext, ok bool)
```

should be defined in a different way and return error instead of a bool result. Like this:
```
func (f *HTTPFormat) FromRequest(req *http.Request) (sc trace.SpanContext, err error)
```

The reason is that `bool` result removes the opportunity to tell why request parsing actually failed. For  Cloud Tracer propagator possible cases could be:
1. missing `/` symbol
2. the string representing trace ID is not a hex-string
3. span ID is not an integer

...and others.

As a developer trying to integrate OpenCensus into an application, I can benefit from having more details about the failure (especially during the first steps of integration).

Also, looks like this pattern was reused in a definition of [general `HTTPFormat` interface](https://github.com/census-instrumentation/opencensus-go/blob/master/trace/propagation/propagation.go#L103), which affects #393 .

Should we consider a change of `FromRequest` method definition?

**Comment by odeke-em** [comment]
Hello @elgris thank you for the request and welcome to OpenCensus!

That's actually a great point, we are not relaying back a bunch of reasons why a propagation failed
as in
https://github.com/census-instrumentation/opencensus-go/blob/aa2b39d1618ef56ba156f27cfcdae9042f68f0bc/plugin/http/propagation/google/google.go#L48-L84

Seems like the signature was predicated by the usage such as
https://github.com/census-instrumentation/opencensus-go/blob/65d32661a6ad0a76920f38d1d6dcc21aec56cfce/plugin/http/httptrace/httptrace.go#L174-L177

/cc @rakyll @ramonza

**Comment by ramonza** [comment]
I think the tension is that it's not really an error if a request just doesn't have tracing information. That's kind of expected in the presence of sampling. I'm curious how you would use the error? If you're just instrumenting a library with OpenCensus, you shouldn't need to create an HTTPFormat yourself.

**Comment by elgris** [comment]
@ramonza at some point in a big company (I currently work for) `service A` may start sending requests to `service B` using incorrect `HTTPFormat`. There is no standard format defined (yet), so everyone is free to use one of many available formats: B3, Google Cloud, something completely custom as long as it implements `HTTPFormat` interface, etc.

In case of custom implementation the bugs are inevitable :) Especially when it comes to communication between services written in different languages (we have at least Java, Python, Go, JS, Scala, there is more). 

Having this, it would be nice to distinguish between "request has no tracing data at all" (which we either can drop or talk to corresponding team so add implement tracing to their app) and "request contains malformed trace data" which is clearly a bug.

What do you think about this?

Also, the code snipped can be modified like this:
```
 sc, err = f.FromRequest(r) 
 if err !=nil { 
 	break 
 } 
```

Standard HTTPTrace plugin may drop it, but nothing stops of implementing your own plugin that does error processing on top of other customisations (e.g. changing naming scheme or adding mandatory attributes to the span).

**Comment by adriancole** [comment]
Provided propagation impl is pluggable, This could be done internally
right? Particulary with setups that do composite inject and extract a
single error doesnt seem to work in practice.

Composite will be routine for many sites considering the trace context
format will require this for transition.

**Comment by ramonza** [comment]
That makes sense. I think we'd be open to making a change along those lines if you want to make a PR.

**Comment by ramonza** [comment]
Posted before seeing @adriancole's reply. The case of composite format (accepting a wide range of possible inputs) does seem to be in conflict with returning an error. I think it might be best to wait until we have a concrete need for returning an error and then we can review a PR in the context of that concrete need and maybe look at different ways of handling the situation.

**Comment by elgris** [comment]
got it, thanks @ramonza and @adriancole.
