### ISSUE TITLE
gRPC package names are inconvenient

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#409]
Package go.opencensus.io/plugin/grpc is inconveniently named to conflict with the grpc. They are often used in the same source file. We should consider renaming this package. The same applies to the http package contemplated in #394 so I'm going to call this something other than "http".

**Comment by rakyll** [comment]
@ramonza, do you want to work on this change?

**Comment by rakyll** [comment]
I am doing it instead.

**Comment by ramonza** [comment]
Fixed in #425
