### ISSUE TITLE
Provide a method for flushing all exporters

### ISSUE THREAD

**Issue by jadekler** [census-instrumentation/opencensus-go#411]
When my program panics, I'd like to:

- log
- flush all exporters
- exit

**Comment by odeke-em** [comment]
Thank you @jadekler for the request, and welcome to OpenCensus!

Seems straightforward to implement, but I'll wait on the consensus of the team.

```go
stats.FlushAllExporters() error?
trace.FlushAllExporters() error?
```

**Comment by jadekler** [comment]
Thanks @odeke-em. 🙂Those methods look exactly like what I'm looking for!

**Comment by ramonza** [comment]
@odeke-em on the error question, I am on the side of not returning an error. You have to ask yourself, which error do I want to return and then what do you expect the caller to do with it. In this case I think it's better to leave it up to the Exporter to log the error appropriately.

**Comment by rakyll** [comment]
How is this different than flushing individual exporters? Not every exporter has a buffer. I'd suggest us not leaking this implementation detail to the stats and trace packages.

Flush the flushable exporters if it is required.
