### ISSUE TITLE
all: git precommit hook to check for go-fmt issues

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#418]
Raised and fixed by @ferhatelmas in https://github.com/census-instrumentation/opencensus-go/pull/417, that was an issue in which we hadn't run go-fmt on a file. Let's perhaps explore the possibility of a git precommit hook to handle checking if all go files are go-fmt'd. The Go project does this.

**Comment by rakyll** [comment]
We can do this at CI, need to fix https://github.com/census-instrumentation/opencensus-go/blob/master/.travis.yml#L19 to do the right thing to check the formatting errors rather than rewriting.

**Comment by odeke-em** [comment]
Awesome, thanks for tackling this. I had seen that CI line but with the new PR I see we actually now use the result to enforce go-fmt-ing
