### ISSUE TITLE
AWS X-Ray implementation of opencensus

### ISSUE THREAD

**Issue by savaki** [census-instrumentation/opencensus-go#421]
Would you be interested in accepting an opencensus implementation for aws x-ray?  I've written one for opentracing, but after reading through opencensus, I like your approach better.

**Comment by rakyll** [comment]
Yes please!!!

**Comment by rakyll** [comment]
Also please feel free to take a look at https://github.com/census-instrumentation/opencensus-go/issues/314.

**Comment by savaki** [comment]
Sweet.  I'll have a look this weekend.

**Comment by ramonza** [comment]
This has been moved to: https://github.com/census-instrumentation/opencensus-go-exporter-aws/
