### ISSUE TITLE
Fix the naming of exported measures and views from ochttp

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#424]
For example, ClientRequest should be called ClientRequestCount, ClientRequestCount should be called ClientRequestCountView.

Name the measures and views consistently with the gRPC measures/views. https://godoc.org/go.opencensus.io/plugin/grpc/grpcstats.

There is no need to have multiple naming conventions.

**Comment by ramonza** [comment]
ClientRequestCount as a view doesn't seem right. "Count" is an aggregation function so part of the view, not the measure. I will think about it some more. 

I also think that the views should maybe be all collected into a single `var DefaultViews []*View` to make it clearer that these are just defaults, not the only ones that you can define.

**Comment by rakyll** [comment]
Maybe it should be called ClientRequests.

Regardless of what we are doing here, we should apply it to the grpcstats packages. It is confusing to have inconsistent naming of measures/views in the same project.

**Comment by ramonza** [comment]
Agh, wrong issue number in Fixes comment
