### ISSUE TITLE
Provide an option to set Sampler on HTTP and gRPC server integration

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#431]
This caused this ochttp.TestHandler to fail unexpectedly due to action-at-a-distance. I think it makes much more sense to configure ochttp.Handler (and it's gRPC counterpart) with an instance of Sampler if required. The default should be trace.ProbabilitySampler(0.0): this is *different* from NeverSample in that it will respect the TraceContext IsSampled flag.

**Comment by rakyll** [comment]
Please discuss cross-language decisions under the specs repo. This change will require https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/Sampling.md spec to be modified.

**Comment by ramonza** [comment]
Perhaps the behavior of the ProbabilitySampler is cross language but I think it is really up to us to provide a Sampler on the HTTP/gRPC plugin server instrumentation, so I'm going to retitle and reopen.

**Comment by rakyll** [comment]
We provide users to provide StartOptions for HTTP and gRPC integrations now, closing the issue.
