### ISSUE TITLE
Add a flag to gRPC and HTTP server instrumentation to indicate whether to trust the caller

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#436]
As discussed in-person with @bogdandrutu, right now we always trust the headers/metadata passed to HTTP/gRPC server integration. In most cases this is fine (if you are a backend service or your LB strips all unknown headers) but in many cases it isn't acceptable to just accept the SpanContext from the incoming requests which is untrusted.

We should add an option in the HTTP and gRPC server integrations to trust or not trust the incoming headers. In HTTP, this might be handled by just configuring an empty slice of propagation.HTTPFormat, but we should document this.

**Comment by rakyll** [comment]
We discussed offline that we are not sure if the lack of trust should be the default case.

gRPC servers are secure by default and we might need to understand more of the canonical way of exposing a gRPC server to public before finalizing this option.

**Comment by rakyll** [comment]
Closed via the IsPublicEndpoint field on the plugins.
