### ISSUE TITLE
tag: add pprof.Do equivalent to record profiler samples with a tag map

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#45]
Add a [pprof.Do](https://golang.org/pkg/runtime/pprof/#Do) like utility to record profiler samples with a given tag map. Do looks for the tags inside the given context and sets them as pprof labels. Any goroutine started in f needs to propagate the tag map via c in order to be able to keep setting the labels in the new goroutines. 

```
func Do(ctx context.Context, m *Map, f func(c context.Context))
```

**Comment by wcn3** [comment]
The proposed signature precludes the user from adding their own labels to the profiler, which would be annoying. At least calls to pprof.Do() are nestable, so I could call it twice, once for the tag map, then once for my labels, but that feels clunky.

A signature of 

func Do(ctx context.Context, m *Map, l *pprof.LabelSet, f func(c context.Context)) or

func Do(ctx context.Context, m *Map, f func(c context.Context), l ...pprof.LabelSet)

might be more helpful to the user, with a clearly defined behavior that keys in the tag map clobber user-provided keys (for example). The downside of this suggestion is that the collision behavior for identical keys is baked into Do, whereas with the previous approach, calls to Do determine the collision behavior.

Alternatively, if the runtime/pprof API could be modified to include a capability to merge LabelSets into a single LabelSet, that'd be powerful. LabelSets are opaque in the same way tag maps are, so a function to convert tag maps to a LabelSet would be sufficient while retaining the opacity properties of the tag map.

I have a somewhat pressing need for this functionality, and would be delighted to contribute if it can help expedite its existence, hence the thoughts exploring the potential design spaces.

**Comment by rakyll** [comment]
I haven't done a very comprehensive survey but the mutual use of pprof labels with tags was not that common. That's the main reason the suggested API is opinionated to work against the tags but we need to make the mutual use possible.

@matloob, this case seems to be a very common use case for instrumentation libraries. What do we suggest them to do?  I don't have a good  background how the standard library pprof labels APIs have been emerged. In `Do`, we don't want to apply profiler labels from the incoming context automatically. Is this to avoid user having to write one more line (pprof.WithLabels) or we want them to avoid passing a context with lots of profiler labels around?

**Comment by matloob** [comment]
I think tag.Do is exactly what we need.
