### ISSUE TITLE
Benchmark for HTTP client tracing

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#461]
We'd like to integrate tracing into the Google Cloud libraries. Before we do this, we need a benchmark showing the overhead of tracing. Things we might want to explore:

* Different sampling rates
* Exporter enabled / not enabled
* ZPages enabled / not enabled

**Comment by odeke-em** [comment]
Cool @ramonza.
Could we try sketching out the work we want to do, or are you already working on this already?

I was thinking
### Different sampling rates:
a) Make a handler with no tracing enabled and no span creation either
b) Make the same handler with a created span and end the span on deferral
c) If the probability is x, send at least 1 + (1/x) requests e.g if x = 0.5, send at least 1 + 1/0.5 = 3 requests
d) Run them through a benchmarking func

### Exporter enabled/not enabled
Perhaps repeating what we did above?

### zPages enabled/not enabled
Ditto

**Comment by ramonza** [comment]
Fixed in #467
