### ISSUE TITLE
Prometheus exporter example returning errors to /metrics endpoint

### ISSUE THREAD

**Issue by freddygv** [census-instrumentation/opencensus-go#469]
**What did you do?**
Downloaded and executed [this example](https://github.com/census-instrumentation/opencensus-go/blob/master/examples/stats/prometheus/main.go), then pulled up the localhost:9999/metrics endpoint in Chrome.

**What did you expect to see?**
There should be output along the lines of:
```
opencensus_video_count 33
opencensus_video_cum_bucket{le="0"} 0
opencensus_video_cum_bucket{le="65536"} 0
opencensus_video_cum_bucket{le="4.294967296e+09"} 0
opencensus_video_cum_bucket{le="+Inf"} 17
opencensus_video_cum_sum 6.671402338140933e+19
opencensus_video_cum_count 17
```

**What did you see instead? Under which circumstances?**
```
An error has occurred during metrics gathering:

2 error(s) occurred:
* collected metric opencensus_video_count counter:<value:225 >  was collected before with the same name and label values
* collected metric opencensus_video_cum histogram:<sample_count:225 sample_sum:1.0183722549263512e+21 bucket:<cumulative_count:0 upper_bound:0 > bucket:<cumulative_count:0 upper_bound:65536 > bucket:<cumulative_count:0 upper_bound:4.294967296e+09 > >  was collected before with the same name and label values
```

**More context**
I tried commenting out either of the stats.Record statements at the bottom of the file, and it seems like each one works individually. The problem seems to happen when measurements are recorded for more than one measure.

I followed the example to include OpenCensus in a Go project of my own and also encountered the same thing. Recording measurements of a single measure look fine, but then when a second measure's measurement is recorded I see errors.

**Environment**

* System information:
Darwin 17.4.0 x86_64

* Package versions:
go.opencensus.io v0.3.0
prometheus client_golang v0.8.0

**Comment by odeke-em** [comment]
Hello @freddygv, thank you for reporting this issue and welcome to OpenCensus!

This bug seems to have been introduced by PR https://github.com/census-instrumentation/opencensus-go/pull/456 /cc @rdallman @rakyll

**Comment by rakyll** [comment]
@odeke-em, can we revert the change and investigate what we can do?
