### ISSUE TITLE
zpages HandlerFuncs are named Handler

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#478]
Both RpczHandler and TracezHandler are HandlerFuncs but they are named as handlers. It is confusing for the user.

/cc @ramonza

**Comment by ramonza** [comment]
I think we should deprecated them. Having to consider using one or the other independently complicates the HTML. For example, it precludes creating links between them.

**Comment by rakyll** [comment]
Closed via 6e008f8971f53840fe7b528ab3d733a38e54a4bb.
