### ISSUE TITLE
Think about tags.Set design

### ISSUE THREAD

**Issue by zombiezen** [census-instrumentation/opencensus-go#48]
It's unclear whether `tags.Set` is intended to be mutable or immutable.  @rakyll mentioned wanting to hide the encoding details from the user, so I recommended the following:

```go
type Set map[Key]Value

func (set Set) Copy() Set

type Value struct {
  b []byte
}

func StringValue(s string) Value {
  return Value{[]byte(s)}
}

func Int64Value(i int64) Value {
  return Value{[]byte{/* encode the int */}}
}
```

**Comment by rakyll** [comment]
We are considering to have only string values in the future, so I am going to keep this on hold until the data model is finalized.

**Comment by rakyll** [comment]
This issue is now obsolete due to https://github.com/census-instrumentation/opencensus-go/pull/98.
