### ISSUE TITLE
Stackdriver example should subscribe to view

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#482]
In our Stackdriver example we don't show subscribing to any views. This means that no stats will be collected.

**Comment by ramonza** [comment]
We should also probably show explicitly recording a measure.

**Comment by freddygv** [comment]
Hi @ramonza is this still needed? Seems like it was covered by your latest ergonomics PR. 

I'm looking to contribute to the examples in the repo, but maybe I'll make one for the zipkin exporter instead.

**Comment by ramonza** [comment]
yup, closing
