### ISSUE TITLE
Reduce the number of steps required to get stats

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#484]
Currently there are many hoops to jump through before you can get stats out of this library:

1. Register a stats exporter
2. Create a measure
3. Create a view
4. Register the view
5. Subscribe to the view
6. call stats.Record

This is not a good experience for users wanting to instrument their code and get metrics out.

(I know you can skip the "Register" step, but we don't in our examples in README so it's not clear that you can.)

**Comment by jadekler** [comment]
+1000

**Comment by ramonza** [comment]
As a first step, I am going to do the following:
* Make view.New() not return errors but defer these to subscription time
* Provide a Subscribe function that takes multiple views

**Comment by rakyll** [comment]
Just FYI, @dinooliva suggested to keep the registration for the libraries that only wants to claim the view name. Then, two libraries cannot expose different views that exports to the same view.

**Comment by ramonza** [comment]
I think it would be better to surface such conflicts at view subscription time by returning an error from subscribe. The alternative would be to crash inside the library at initialization time, which seems unexpected and less useful.

**Comment by ramonza** [comment]
Reduced by 1 step - registering the view. Also added a batch subscribe which amortizes the syntax over multiple views.
