### ISSUE TITLE
trace: Sampler interface should just return a boolean instead of a struct with one boolean field

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#490]
Sampler is defined as
https://github.com/census-instrumentation/opencensus-go/blob/e2fe6beaf0d96b99036db72e68f97157c140cde7/trace/sampling.go#L43-L47

where SamplingDecision is a struct with a single field that's the boolean Sample
https://github.com/census-instrumentation/opencensus-go/blob/e2fe6beaf0d96b99036db72e68f97157c140cde7/trace/sampling.go#L58-L61

I propose we just define Sampler as
```go
type Sampler interface {
   Sample(p SamplingParameters) bool 
}
```

Unless we plan on expanding SamplingDecision to include other fields, I don't see the need for us to have to an extra level of indirection

**Comment by ramonza** [comment]
What about:
    type Sampler func(SamplingParameters) bool

**Comment by rakyll** [comment]
I now learned that initial argument behind having SamplingParameters is to have a field for deferred tracing (probably another bool).

**Comment by ramonza** [comment]
what is deferred tracing? meaning that we keep the trace events in-memory but don't export it until some condition is met?

**Comment by rakyll** [comment]
Deferred tracing is we keep the trace events in-memory but don't export them until some condition is met.
