### ISSUE TITLE
Change copyright

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-go#5]
* Please add a file called AUTHORS with one line for the moment Google Inc.
* Change all licenses headers to: Copyright [YEAR], OpenCensus Authors

See census-instrumentation/opencensus-java#539

**Comment by adriancole** [comment]
Isn't NOTICE more used than AUTHORS? AUTHORS might mislead people.

Ex I placed this in a repo for zipkin on request from pinterest
https://github.com/openzipkin/zipkin-sparkstreaming/blob/master/NOTICE.md

**Comment by tags07** [comment]
Usually the NOTICE file has license notices along with copyright information. example, https://github.com/android/platform_system_core/NOTICE

I have seen CREDITS file(https://github.com/torvalds/linux) and have also seen AUTHORS that list names (https://github.com/grpc/grpc-java)
