### ISSUE TITLE
Rate limited Sampler

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#503]
Add a rate-limited sampler. Rate-limiting is a way to ensure that even low QPS apps get some traces but high QPS apps don't overwhelm the system. This is a local rate-limiter, probably implemented as a simpler wrapper around `golang.org/x/time/rate` - distributed rate-limiting is out of scope.

**Comment by isaachier** [comment]
While you're at it, there's a bunch of others here: https://github.com/jaegertracing/jaeger-client-go/blob/master/sampler.go. My favorite is the guaranteed throughput sampler. @black-adder

**Comment by adriancole** [comment]
https://github.com/aws/aws-xray-sdk-go/tree/master/strategy/sampling has
the reservoir policy used by amazon

**Comment by rakyll** [comment]
Can we discuss this issue on the specs repo? This is not the place to debate cross-language feature requests.
