### ISSUE TITLE
stats: remove Record in favor of Measure.Measure(context.Context, value float64) to encapsulate Record's work

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#504]
As a user of these APIs, after I've created a Measure, I expect to invoke methods like Increment/Add on the Measure itself. An addition shouldn't have to indulge the user's mind into the notion of Recording. That should be handled by the library itself

Currently Measure is an interface but in a follow-up issue I'll show how we can further simplify our APIs. As I'll show below, with succinct examples, the cognitive load for users and API surface reduce with this simplification.
```go
func init() {
   numQueries, err = stats.Int64("org.orijtech.com/num_queries", "the number of queries processed over time", "query")
   if err != nil {
      log.Fatal
   } 
}
```

#### Before
```go
func handleAuth(w http.ResponseWriter, r *http.Request) {
     ctx, span := trace.StartSpan(r.Context(), "/auth")
     defer span.End()

     defer stats.Record(ctx, numQueries.Add(1))
}
```

#### After
```go
func handleAuth(w http.ResponseWriter, r *http.Request) {
     ctx, span := trace.StartSpan(r.Context(), "/auth")
     defer span.End()

     defer numQueries.Add(ctx, 1)
}
```

**Comment by rakyll** [comment]
Add only makes sense for CountAggreagtion. It is not applicable for the others.

We also preferred to go with stats.Record but it serializes the tags for once for many measurements. There is a performance concern to collect measurements separately.

**Comment by odeke-em** [comment]
> Add only makes sense for CountAggreagtion. It is not applicable for the others.

Measure*.Add surely only works for CountAggregation but also for SumAggregation.

Actually I made a mistake in the `before section` by invoking `.Add`, we don't have such a method in https://godoc.org/go.opencensus.io/stats, we have `m.M(n)`

We can cover all of them by still using the M method, basically this proposal asks to remove `stats.Record(ctx, m.M(n))`. I have updated the title.

> There is a performance concern to collect measurements separately.

That's a great point and I believe a counter that my proposal can't satisfy, thank you for raising it!

**Comment by rakyll** [comment]
We will soon have a gauge type that only records the latest value.

The split between measure and view in OpenCensus is that values you record and the aggregation you apply on them are separate steps. Add itself is an aggregation algorithm.

The expected API should have two sections: allowing recording of arbitrary data points and allow users to apply various aggregation algorithms we provide.

**Comment by ramonza** [comment]
@odeke-em discussed in person, can we close this?

**Comment by odeke-em** [comment]
Perhaps we'll revisit this if need be, but sure let's close it.
