### ISSUE TITLE
trace: make clear that the computation in setting Span.EndTime in Span.End() is using the monotonic clock

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#506]
While editing a bunch of code I noticed this
https://github.com/census-instrumentation/opencensus-go/blob/6e008f8971f53840fe7b528ab3d733a38e54a4bb/trace/trace.go#L231

That code is an unnecessary computation, because:
a) time.Since(startTime) = time.Now().Sub(startTime)
b) startTime.Add(time.Since(startTime)) = startTime.Add(time.Now().Sub(startTime)) == time.Now()

that line should just be time.Now()

I'd send a PR but am deep in edits on my branch.

**Comment by odeke-em** [comment]
It comes from this PR https://github.com/census-instrumentation/opencensus-go/pull/384 but now I don't see why we made that change

**Comment by rakyll** [comment]
This is to calculate the span time by using the monotonic clock. https://golang.org/pkg/time/#hdr-Monotonic_Clocks

Maybe add a comment noting that.

**Comment by odeke-em** [comment]
https://play.golang.org/p/80eR712AM1K
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	start := time.Now()
	<-time.After(5 * time.Millisecond)

	end1 := time.Now()
	end2 := start.Add(time.Since(start))
	end3 := time.Now().UTC()
	fmt.Printf("end1: %+v\nend2: %+v\nend3: %+v\n", end1, end2, end3)
}
```
gives 
```shell
end1: 2009-11-10 23:00:00.005 +0000 UTC m=+0.005000001
end2: 2009-11-10 23:00:00.005 +0000 UTC m=+0.005000001
end3: 2009-11-10 23:00:00.005 +0000 UTC
```
where both end1 and end2 have their monotonic clocks intact and
only the 3rd one has the monotonic clock stripped out.
Please educate me as I missed the whole memo about monotonic clocks sometime mid last year.

**Comment by odeke-em** [comment]
If it is additions and subtractions that we want to only keep the monotonic clock,
```go
time.Now().Add(0)
```

**Comment by odeke-em** [comment]
Thanks @rakyll for breaking this down for me offline and as the docs say
<img width="941" alt="screen shot 2018-02-28 at 7 32 37 pm" src="https://user-images.githubusercontent.com/4898263/36825786-297d21d2-1cbe-11e8-97a4-6147cfff85b5.png">

So the current code is correct. As you suggest, perhaps let's make it more obvious say an internal function since this might be something we'll use e.g.
```go
func MonoticTimeSince(start time.Time) time.Time {
    // Monotonic time is used by subtractions
    return start.Add(time.Now().Sub(start))
}
```
