### ISSUE TITLE
stats/view: remove DistributionData's Sum method in favour of a field 

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#511]
This is an issue that'll perhaps alleviate the fast path quite a lot. See in 
https://github.com/census-instrumentation/opencensus-go/blob/f0425986078cf0a0fac57cae520a23c1da26a5a8/stats/view/aggregation_data.go#L158-L159

we compute the Sum through that multiplication. However, the two ingredients needed to compute the sum: Mean and Count are computed in
https://github.com/census-instrumentation/opencensus-go/blob/f0425986078cf0a0fac57cae520a23c1da26a5a8/stats/view/aggregation_data.go#L170-L188

Makes me wonder why we have Sum in the fast place yet we could compute it on every modification of Count and Mean and then prevent future spurious multiplications.
If stats are collected every 5 seconds but only n samples were added, in a minute that'll be 60/5 = 12 multiplications going on for data that hasn't changed, and in fact even with the default reporting period of 10 seconds, that's 60/10 = 6 multiplications every minute yet it could have just been n multiplications (that is 1 multiplication per sample)

**Comment by rakyll** [comment]
I don't have strong opinions but it makes sense to provide setters for values that can be dynamically calculated to be less error prone. I don't think it is odd to have Sum as a method instead of a field.

**Comment by rakyll** [comment]
You keep extra bytes as state for nothing, I am going to close this.

**Comment by odeke-em** [comment]
The point behind it is to make a single calculation like we do for Mean and Count, what "extra bytes as state are we talking about"? As I exhibited in https://github.com/census-instrumentation/opencensus-go/issues/511#issue-301572867
