### ISSUE TITLE
tag: provide a range method to iterate over the keys and values of a Map

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#521]
We need a method to range over all the keys of a Map.

This need arose from the interoperability test requirements and actively here https://github.com/census-instrumentation/opencensus-experiments/pull/3.

**Comment by odeke-em** [comment]
Just for clarity, in order for the interop server to reliably echo the tags back to the caller it needs to be able to retrieve keys and values and populate a map[string]string. This issue isn't for comparison but actually for retrieval in order to verify that tags were received, at least according to the interop requirements.

**Comment by rakyll** [comment]
We chatted offline and suggested to tweak the interop requirements. can we close this issue now?

**Comment by odeke-em** [comment]
In deed, thanks @rakyll.

For posterity, the solution that was found to satisfy tests was to just invoke `tag.Encode(tag.Map)` and then `tag.Decode([]byte)`  to decode all the content.
