### ISSUE TITLE
SpanKind support

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#525]
SpanKind is now part of OpenCensus trace proto. We should support it as a first class citizen in Go. See: https://github.com/census-instrumentation/opencensus-proto/pull/51

**Comment by rakyll** [comment]
Is this API breaking anymore? We are going to make it an option.

**Comment by ramonza** [comment]
Guess not

**Comment by adriancole** [comment]
fwiw in zipkin-go @basvanbeek made lack of kind a special kind (at the api level which is not strictly bound to the format) https://github.com/openzipkin/zipkin-go/blob/master/model/kind.go

**Comment by rakyll** [comment]
Closed via https://github.com/census-instrumentation/opencensus-go/pull/610 and https://github.com/census-instrumentation/opencensus-go/pull/616.
