### ISSUE TITLE
Create a zipkin example

### ISSUE THREAD

**Issue by victormn** [census-instrumentation/opencensus-go#531]
We already have a Jeager example of tracing. Could you write a Zipkin example, please?

**Comment by odeke-em** [comment]
Hello there @victormn, thank you for the request and welcome to OpenCensus!

So we have an example test in https://github.com/census-instrumentation/opencensus-go/blob/52b12e1eb8fdf769ad0bf5fd73a2af9484e6b196/exporter/zipkin/example_test.go#L15-L40

However, if you'd like to create a conventional example like Jaeger's in the example's  directory, you are more than welcome and I'll tag other teammates @ramonza @rakyll.

**Comment by freddygv** [comment]
Hi, I was planning on adding this. Will get a PR in this weekend.

**Comment by odeke-em** [comment]
Perfect, thank you again @freddygv!
