### ISSUE TITLE
exporter/prometheus: fix doc description

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#542]
I was just making a test integration and noticed this
<img width="769" alt="screen shot 2018-03-08 at 10 32 14 pm" src="https://user-images.githubusercontent.com/4898263/37193920-a9045d22-2320-11e8-8fc5-d3c98759bb54.png">

Notice the wording:
"Package prometheus contains the Prometheus exporters for Stackdriver Monitoring."

Let's fix this.

**Comment by rakyll** [comment]
This is easily one of the worst copy/paste bugs I have ever contributed.
