### ISSUE TITLE
go get -u go.opencensus.io   ---  package go.opencensus.io/...: remote origin not found

### ISSUE THREAD

**Issue by ljcremer** [census-instrumentation/opencensus-go#543]
For some reason the package cannot be installed. 

I can install other packages but this one is giving me issues

**Comment by rakyll** [comment]
What's your Go version and what's the out of "git remote -v" in $(go env GOPATH)/src/go.opencensus.io?

**Comment by ljcremer** [comment]
Go version is : go1.9.2 windows/amd64

Output ot git remote -v is as follows:
fatal: Not a git repository (or any of the parent directories): .git

**Comment by rakyll** [comment]
I have little idea how you ended up in that bad state but please remove the go.opencensus.io directory and go get again.

**Comment by ljcremer** [comment]
Not sure myself. I deleted it and now the process started fine. It then processes for quite a long time and then I get the following error:
C:\Users\ljcremer\Google Drive\Development\Go>go get -u go.opencensus.io
# cd .; git clone https://github.com/census-instrumentation/opencensus-go C:\Users\ljcremer\Google Drive\Development\Go\src\go.opencensus.io
Cloning into 'C:\Users\ljcremer\Google Drive\Development\Go\src\go.opencensus.io'...
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
package go.opencensus.io: exit status 128


Not sure if this is maybe some network issue?

**Comment by rakyll** [comment]
No problem, I am going to close this issue now. Please reopen if there is anything we need to fix.

**Comment by ljcremer** [comment]
Perfect. Thanks
