### ISSUE TITLE
Creating measures and checking errors is inconvenient

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#544]
The issue of having Must* variants to create Measures has come up before. Previously, the argument against having such variants was that the caller in most cases knows that the measure name is valid and so can simply ignore the error.

This is true for tag.Key where the only validation is that the key name is valid syntactically. With stats.Int64 and stats.Float64, you also need to know that the name is *unique*. This is not something that the caller can know just from the text of the program. I have actually run into this multiple times, especially in tests where you create measures inline. 

I think we should either add a Must variant for stats.Int64 and stats.Float64 or make duplicating the measure name not an error.

/cc @rakyll

**Comment by rakyll** [comment]
I agree that there is a compelling reason to add this for measures but the other question how effective the uniqueness check is. Although it gives us integrity within a single process, it doesn't help us with uniqueness beyond a single process. IMHO, we can prefer to stop retuning an error if from stats.Int64 and stats.Float64 if returning errors doesn't add significant value.

**Comment by rakyll** [comment]
We chatted with @bogdandrutu offline and decided that we should keep returning errors. We might implement a global uniqueness check later on and want to be facilitate the current API.

Bogdan also agrees in-process uniqueness check doesn't add much value and we can remove it.

**Comment by ramonza** [comment]
A global uniqueness check happening implicitly in package init (which is where these functions are mostly called) sounds unlikely to be implementable. 

The way I can imagine this playing out (if we really wanted to check global consistency of measures) is that there would be some initialization function which would do a single remote call to validate all the defined methods that the user could call from their main. This function would be able to return errors. 

Therefore, I think there's no reason to return an error in this function and I would prefer that we remove it from the function signature. 

@rakyll @bogdandrutu
