### ISSUE TITLE
Double-negative NoTrace, NoStats options in ocgrpc and ochttp

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#547]
We should try to find a way to avoid these double-negatives.

**Comment by rakyll** [comment]
We don't have to. It is an explicit request from user and it is little cost if both are disabled.

**Comment by ramonza** [comment]
what do you mean "little cost if both are disabled"? Do you mean if neither option is specified, or if they are specified (meaning that trace and stats are disabled)? 

What was the user requested feature?

**Comment by rakyll** [comment]
If the user both disables stats and traces (NoStats=true, NoTrace=true), it doesn't add additional performance overhead to the Transport or Handler.

OTOH, having (NoStats=true, NoTrace=true) will be a valid case once we have tag propagation over HTTP implemented. User might just want to use ochttp for tag propagation.

**Comment by ramonza** [comment]
I wasn't really thinking about performance, I was thinking about how confusing it sounds having a `NoTrace bool` parameter rather than `Trace bool` just so that the zero value is what we want.

**Comment by rakyll** [comment]
If we have `Trace bool` and `Stats bool`, they are most likely to be set by every user all the time. I expect users coming to this plugin to enable at least trace or stats. Making it optional to enable them sounds like the opposite of why this package exists in the first place.

Most of the time, users shouldn't care about disabling but they have the option to disable.

**Comment by ramonza** [comment]
Yeah I know, I don't want people to type that either. For stats, I think we can get to the point where if there are not views defined there is very little cost, so we can simply remove the option. For trace, we can maybe get to the same point if we allow the user to customize the StartOptions and replace the Sampler with something that never samples. To avoid tag/trace propagation, they can set the propagation format (for HTTP) or we can provide a toggle (for gRPC).

**Comment by rakyll** [comment]
We briefly chatted about this issue offline and also removed NoTrace from ochttp and octrace. I assume renaming NoStats to DisableStats is the last thing left to do. Once the rename is in, we can close this issue.

**Comment by rakyll** [comment]
Closed via 283e9037189fd258e9fffc6263e9aa0f0890ab95.
