### ISSUE TITLE
Trace Attributes are verbose

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#550]
BoolAttribute, Int64Attribute, StringAttribute are verbose to construct. Instead of providing these types, we can provide attribute constructing functions.

```
func StringAttribute(key, value string) Attribute
func Int64Attribute(key string, value int64) Attribute
func BoolAttribute(key string, value bool) Attribute 
```

On the export path, we report the attributes as a `map[string]interface{}` so it is not going to affect how exporters access to the attributes.

Link.Attributes are represented as a `map[string]interface{}` but it is confusing for the users given the rest of the user-facing APIs require them interact with the Attribute types. We can also replace it with `Attributes []Attribute` for API consistency.

/cc @ramonza @odeke-em

**Comment by ramonza** [comment]
So Attribute would become:
```go
type Attribute struct {
  Key string
  value interface{}
}
func (attr *Attribute) Int64Value() (int64, bool) {
   return attr.value.(int64)
}
...
```
