### ISSUE TITLE
Move vendor-specific propagation formats under vendor directories

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#553]
We cannot maintain all vendor propagation formats in the core repos. `plugin/ochttp/propagation/google` should be closer to the vendor-specific exporter package, /exporter/stackdriver. In case we decide to split exporter packages into different repos, vendor package will contain all the vendor-specific implementation.

Additionally, we can make stackdriver.Exporter implement propagation.HTTPFormat for convenience.

/cc @ramonza

**Comment by ramonza** [comment]
Began in #555

**Comment by ramonza** [comment]
This is now done
