### ISSUE TITLE
Possible race in default worker

### ISSUE THREAD

**Issue by kazegusuri** [census-instrumentation/opencensus-go#556]
A default worker starts in goroutine at `init()` of stats/view/worker.go. The worker refers time package to use `time.Now()`.
When I overwrite `time.Local` of package variable to ensure that `time.Now()` returns specific timezone, this will cause data race.  This would be an abuse of package variable but it is exposed.

This is a log of race (partially modified).
```
WARNING: DATA RACE
Read at 0x0000015e3db0 by goroutine 9:
  time.Now()
      /usr/local/go/src/time/time.go:1049 +0xd3
  time.sendTime()
      /usr/local/go/src/time/sleep.go:141 +0x44

Previous write at 0x0000015e3db0 by main goroutine:
  [failed to restore the stack]

Goroutine 9 (running) created at:
  runtime.(*timersBucket).addtimerLocked()
      /usr/local/go/src/runtime/time.go:160 +0x106
  go.opencensus.io/stats/view.newWorker()
      go.opencensus.io/stats/view/worker.go:152 +0x8c
  go.opencensus.io/stats/view.init.0()
      go.opencensus.io/stats/view/worker.go:28 +0x33
  go.opencensus.io/stats/view.init()
      <autogenerated>:1 +0x101
  go.opencensus.io/plugin/ocgrpc.init()
      <autogenerated>:1 +0xa5
  google.golang.org/api/transport/grpc.init()
      <autogenerated>:1 +0xb4
  google.golang.org/api/transport.init()
      <autogenerated>:1 +0xb4
```

**Comment by rakyll** [comment]
Are you mutating time.Local to have a new global Location? I think this is an anti-pattern. You should instead use any preferred Location only when displaying time info. See https://github.com/golang/go/issues/10701#issuecomment-148777945.

**Comment by kazegusuri** [comment]
Thanks for reply. That is the issue what I realy see! Anyway alright the reason.
