### ISSUE TITLE
Usually exporters can generate more traces than the real traffic.

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-go#557]
Every time when we upload to SD (for example) we start a new trace in the gRPC client, which uses the default sampler (and sometimes for low traffic services 1qps for example) using the default sampler as always sample we have a lot of traces for the exporter.

I think we have few options here:
* Wrap the "uploadToStackdriver" (or equivalent for other exporters) in a Span that uses "never sample" sampler.
* Wrap the "uploadToStackdriver" (or equivalent for other exporters) in a Span that uses "1/1000 sample" sampler (this is implemented in Java).
* We can expose the sampler that we use in the option with a default of 1/1000, but I don't think these traces are that useful.
* Recommend users to set a larger BundleDelayThreshold (the current default is 2 seconds) and make probably the default 5 or 10 seconds. (We may want to do this anyway)

/cc @groob who reported similar problem on gitter channel.

**Comment by ramonza** [comment]
Took a cursory look and from what I can tell this should only happen if you explicitly pass ocgrpc.ClientHandler to stackdriver.NewExporter (via ClientOptions). Is that what's happening here?

**Comment by ramonza** [comment]
Confirmed by running stackdriver.TestExport with a dummy project that at least with a very vanilla configuration this should not happen

**Comment by ramonza** [comment]
Actually, I think what's happening here is that the grpc client used by the Stackdriver exporter is also instrumented because of the instrumentation of `google.golang.org/api/transport/grpc`.
