### ISSUE TITLE
ocgrpc: missing service and version fields in Stackdriver

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#570]
Traces created in Stackdriver by the ocgrpc ClientHandler don't display service names or versions in the Stackdriver UI.

**Comment by odeke-em** [comment]
@ramonza in regards to this bug, we are asking to send the following attributes right?
* service names -- gRPC service, which would basically be the "method" that we just got rid of https://github.com/census-instrumentation/opencensus-go/issues/541
* version -- what do we mean here?

**Comment by odeke-em** [comment]
Okay I've just been re-reading the Stackdriver Trace docs and I believe what you @ramonza meant by "service" is say some runtime information e.g "Go" or say "spanner", and version being say "Go1.9.1" or "v2.3"
https://cloud.google.com/trace/docs/overview
<img width="835" alt="screen shot 2018-03-13 at 8 09 08 pm" src="https://user-images.githubusercontent.com/4898263/37381504-bbc824ba-26fa-11e8-802c-5631b772f2a2.png">

**Comment by rakyll** [comment]
Stackdriver Trace allows service and version can only be settable by the AppEngine at this point.

It would be good if they allow Stackdriver Trace API users to set them but that's not the case right now.

**Comment by odeke-em** [comment]
Thank you @rakyll, in that case I'll unassign myself from that as AppEngine is out of my control and scope.

**Comment by rakyll** [comment]
We cannot set these attributes anyways. They are only available via an internal API. I am closing this issue for now.
