### ISSUE TITLE
Span.SetStatus is awkward

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#572]
Assuming you have an err error:
```go
span.SetStatus(trace.Status{Code: 2, Message: err.Error()})
```

There are a few problems with this:

1. It's possible (easy) to construct a Status with no Code but an error message; this is considered successful but is probably not meant as such
2. "Code 2" is pretty non-descript, we should have constants
3. It's quite high ceremony - you have to mention both the package and the object in that line; we could replace it with a function taking the error message and code directly. Perhaps we should even remove the trace.Status type, or only use it in Exporters.

**Comment by rakyll** [comment]
I wonder if there are plans to have more fields on the Status type. That's why I am not confident about #3.

**Comment by ramonza** [comment]
@bogdandrutu are there any future planned additions to Status?

**Comment by rakyll** [comment]
@bogdandrutu mentioned offline we may extend the Status type, closing the issue.
