### ISSUE TITLE
exporter/stackdriver/trace grpc latency with datastore call

### ISSUE THREAD

**Issue by chemidy** [census-instrumentation/opencensus-go#593]
Currently with opencensus-go-v0.4.0 the stackdriver exporter produces this trace with a gRPC server.

```
	exporter, err := stackdriver.NewExporter(stackdriver.Options{ProjectID: cfg.ProjectID})
	if err != nil {
		log.Fatalf("Error creating stackdriver exporter: %v", err)
	}
	view.RegisterExporter(exporter)
	trace.RegisterExporter(exporter)
	// Let's ensure that data is uploaded before the program exits
	defer exporter.Flush()

	// Subscribe to views to collect data.
	if err := view.Subscribe(ocgrpc.DefaultServerViews...); err != nil {
		log.Fatal(err)
	}

        grpcServer := grpc.NewServer(
		grpc.StatsHandler(&ocgrpc.ServerHandler{}),
	)
```
![screen shot 2018-03-16 at 10 08 29](https://user-images.githubusercontent.com/3128770/37512614-ee3998de-2902-11e8-86f7-bb53c9b6783a.png)

But with opencensus-go-v0.3.0 (the version shown in stackdriver was 0.1.0) with the same code, the stackdriver exporter produces this trace, the datastore call is interpreted differently ?

![screen shot 2018-03-16 at 10 09 02](https://user-images.githubusercontent.com/3128770/37512616-ee532696-2902-11e8-9521-78dd22818ee4.png)

I'm not sure, which version is correct, because the latency of my service is not 1ms but around 280ms, due to the datastore call ? Is it a bug ?

**Comment by rakyll** [comment]
I assume that ListUsersBo handler is running the query in order the response to the incoming request. If yes, the second screenshot is correct. It takes ~260ms for the server to handle the request.

**Comment by chemidy** [comment]
Yes, the ListUsersBo handler is running the datastore query. 

Ok so, if the second screenshot is correct (which seemed logical to me), there is a maybe bug somewhere, because actually the first screenshot is produced on stackdriver (but with an older version of opencensus it was correct).

**Comment by chemidy** [comment]
Another example with firebase admin go SDK + datastore. Looks like just related to datastore ?

Now
![screen shot 2018-03-16 at 17 53 44](https://user-images.githubusercontent.com/3128770/37533791-3f7ad542-2943-11e8-9445-05bcd849bd7f.png)

Before
![screen shot 2018-03-16 at 17 53 59](https://user-images.githubusercontent.com/3128770/37533792-3f99cbaa-2943-11e8-8fd4-6070320f070b.png)

**Comment by rakyll** [comment]
This is a problem with the Datastore client, I am sending a PR soon.

**Comment by rakyll** [comment]
Closed via https://code-review.googlesource.com/c/gocloud/+/25310.
