### ISSUE TITLE
exporter/stackdriver/trace with grpc-web produce no traces

### ISSUE THREAD

**Issue by chemidy** [census-instrumentation/opencensus-go#594]
I'm using [grpc-web ](https://github.com/improbable-eng/grpc-web) from my angular webapp.

On client side i'm using this header to trace my gRPC request with gRPC-web :

````
 'X-Cloud-Trace-Context': `${uuid().replace(/-/g, '')}/0;o=1`

````

It was working very well, on stackdriver there was traces like that : 

![screen shot 2018-03-16 at 10 09 02](https://user-images.githubusercontent.com/3128770/37516465-7c548ace-290e-11e8-8ca4-ad640629b559.png)

If i use a go client it works as expected.
But for few days (around 1/2 march 2018)  it's stop working with grpc-web, no traces on stackdriver, any ideas ?

**Comment by rakyll** [comment]
I am not familiar with grpc-web. Can you give us a small reproducible case so we can debug?

**Comment by chemidy** [comment]
Ok, i will provide a sample code tonight or tomorrow.

**Comment by chemidy** [comment]
Ok, you can use the [example provided by grpc-web](https://github.com/improbable-eng/grpc-web/tree/master/example).

To add tracing on request just add the right metadata [after line 13 of index.ts](https://github.com/improbable-eng/grpc-web/blob/master/example/ts/src/index.ts) : 
`````
    request: getBookRequest,
    host: host,
    metadata: {'X-Cloud-Trace-Context': `${uuid().replace(/-/g, '')}/0;o=1`},
`````

**Comment by rakyll** [comment]
It seems like you are provisioning your trace IDs yourself in the Google Cloud format, right? gRPC plugin uses a gRPC-specific propagation metadata [key](https://github.com/census-instrumentation/opencensus-go/blob/67dfb45941af00bd9e91a20bce0222d8a9b8b896/plugin/ocgrpc/trace_common.go#L30:7). It expects IDs to be generated in the binary format.

Look at https://godoc.org/go.opencensus.io/trace/propagation#Binary for a reference implementation of the binary format.

**Comment by chemidy** [comment]
Thks, it works now with grpc-trace-bin metadata in binary format. 
I did not see that there was a lot of rework on plugins

**Comment by rakyll** [comment]
Glad that it is working. We moved to the binary format a while ago for better performance and consistency across Google.
