### ISSUE TITLE
Jaeger exporter service name

### ISSUE THREAD

**Issue by nov1n** [census-instrumentation/opencensus-go#604]
Using the jaeger exporter it seems like the service name is fixed on creation of the Exporter struct: 
```
exporter, err := jaeger.NewExporter(jaeger.Options{
	Endpoint:    "http://localhost:14268",
	ServiceName: "trace-demo",
})
```
In case we have a separate component constructing the spans on behalf of different services, it would be nice to change the service name for each span individually.

An example use case is in the context of istio. The mixer could generate spans on behalf of various services.

An obvious problem is the bundling that's happening in the exporter. A list of spans will be uploaded using whatever service name was set at that moment.

I am available to work on this.

**Comment by rakyll** [comment]
This issue requires to be discussed at https://github.com/census-instrumentation/opencensus-specs.

**Comment by rakyll** [comment]
Moved to https://github.com/census-instrumentation/opencensus-specs/issues/74.
