### ISSUE TITLE
Support Go 1.6?

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#61]
gRPC and AppEngine requires 1.6 support to be around for a little while. Support 1.6 by removing the sort.Slice and context package dependencies.

See also https://github.com/grpc/grpc-go/pull/1603.

**Comment by rakyll** [comment]
1.6 is not critical for gRPC users due to https://github.com/grpc/grpc-go/pull/1603#issuecomment-338323275. We are going to hold this issue for a while.

**Comment by odeke-em** [comment]
Once we've decided upon it, we'll also need to see about reverting the use of `sort.Slice` and instead doing it the old school way with `sort.Interface` as you already duly noted here https://github.com/census-instrumentation/opencensus-go#prerequisites

**Comment by rakyll** [comment]
The downgrade looks very trivial but IMHO, importing the context from golang.org/x/net is something I am not looking forward to do. Hence, not fixing this issue until OpenCensus Go 1.6 support is critical.
