### ISSUE TITLE
Rename View.TagKeys to View.Columns

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#613]
For consistency with OpenCensus C++ and Java

**Comment by ramonza** [comment]
Discussed with @rakyll and we do not think that the name Columns makes sense for Go. 

/cc @bogdandrutu

**Comment by bogdandrutu** [comment]
What is a better suggestion that can work?

**Comment by ramonza** [comment]
We would prefer to leave it as is.
