### ISSUE TITLE
Jaeger exported traces are incomplete

### ISSUE THREAD

**Issue by t-bast** [census-instrumentation/opencensus-go#621]
I was experimenting with OpenCensus (thanks for open-sourcing this, it's a great project) and it looks like there are quite a few things I can't get working properly when exporting traces to Jaeger.
I setup a simple project where I create a span and try to add attributes, annotations and a status:
`_, span := trace.StartSpan(ctx, "dummy/api")`
`defer span.End()`

`span.AddAttributes(trace.Int64Attribute("swag", 42))`
`span.Annotate([]trace.Attribute{trace.StringAttribute("attr", "this is an attribute")}, "this is an annotation")`
`span.SetStatus(trace.Status{Code: 2, Message: "failed"})`

The traces are correctly exported to Jaeger and visible in Jaeger UI, but:

- I see the key for the Int64Attribute but the value is empty
- I see a log in the Jaeger UI which contains my 'swag' and 'attr' attributes (but swag is still empty) but it doesn't contain my annotation
- the trace status isn't taken into account

Is there something I'm doing wrong, or is it because there are inconsistencies between Jaeger's format and OpenCensus'?

**Comment by rakyll** [comment]
Fixed but please let us know if there is anything odd.

**Comment by t-bast** [comment]
Thanks for the quick fix! It looks good now.
I'll keep experimenting and will let you know if I see anything weird.
