### ISSUE TITLE
Stackdriver metrics data doesn't show up

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#631]
Reported by @groob in Gitter that ochttp metrics data doesn't show up, even though the definitions of views do.

I reproduced this with my test appengine app: 
https://github.com/census-instrumentation/opencensus-experiments/tree/master/go/bookshelf
https://bookshelf-195421.appspot.com/

There is data for ocgrpc client views (generated from GCP client SDK integrations).

**Comment by ramonza** [comment]
I found a call to Stackdriver that returns an internal error in the logs and in tracez and filed b/76209250 to investigate.

My ochttp stats for my test app eventually showed up after refreshing the page a few times.

**Comment by groob** [comment]
I got this to work finally, it took a while for the metrics to start populating. It might have just been a transient issue as I can delete the timeseries and start them again and they show up within minutes.
