### ISSUE TITLE
ochttp views ClientResponseCountByStatusCode and ServerResponseCountByStatusCode are using *Latency measure

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-go#634]
https://github.com/census-instrumentation/opencensus-go/blob/a6469e13ef8736dd7671f2334f627c043631b28f/plugin/ochttp/stats.go#L106 and https://github.com/census-instrumentation/opencensus-go/blob/a6469e13ef8736dd7671f2334f627c043631b28f/plugin/ochttp/stats.go#L150.

There are no *response measures - is it intentional?

**Comment by ramonza** [comment]
This is intentional and should work as expected after #635 

I know it looks weird. But the idea is that you don't need another measure just for response code: you just use a Count aggregation when you record latency.
