### ISSUE TITLE
jaeger exporter build is broken

### ISSUE THREAD

**Issue by rdallman** [census-instrumentation/opencensus-go#640]
Hello again. thanks for recently fixing up jaeger! I've had issues updating to master and 0.6.0 with the build for the jaeger exporter, it appears some files need to be re-genned and I do not consider myself an expert here, I hope it is easy to fix. repro:

```
$ cd exporter/jaeger
$ git rev-parse HEAD
12aa45c27dd5d6f81b3d5d193c3e0a427263056d
$ go build
# go.opencensus.io/exporter/jaeger/internal/gen-go/jaeger
internal/gen-go/jaeger/agent.go:79:20: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
internal/gen-go/jaeger/agent.go:122:13: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
internal/gen-go/jaeger/jaeger.go:2146:13: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
internal/gen-go/jaeger/jaeger.go:2163:14: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
internal/gen-go/jaeger/jaeger.go:2176:14: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
internal/gen-go/jaeger/jaeger.go:2190:23: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
$ head internal/gen-go/jaeger/jaeger.go 
// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
```

I am not sure that I know what I am doing :)

thank you

**Comment by ramonza** [comment]
Do you use dep? You might want to use dep to fix the versions and play around with different Thrift versions.

**Comment by rdallman** [comment]
Thanks @ramonza - am using dep, I will try that. as a sanity test, I've attempted to build against this repo outside of the larger project and its dependencies to reproduce the above error just against the base repo. fwiw I see the noted files causing errors checked into the repo here, too https://github.com/census-instrumentation/opencensus-go/blob/master/exporter/jaeger/internal/gen-go/jaeger/agent.go#L79 and am not sure if I am missing something. it seems all that is needed to be done is change the parameters passed to oprot.Flush to go away, but the file seems generated and did not want to PR that myself as it was not clear to me how to generate them.

**Comment by ramonza** [comment]
you might want to pin thrift and open census on the latest from the default branches of both projects since that definitely works according to travis CI

**Comment by rdallman** [comment]
yea, have locked where we needed to, we are good, thanks. trying to help upstream now :) 

it appears that updating thrift has fixed this. all i needed was a coffee... *sigh*, mondays. thank you!

**Comment by ramonza** [comment]
thank you for taking the time to work through the issue. I know it's really frustrating, we also experienced a lot of problems with this dependency and we considered vendoring thrift or moving to the HTTP endpoint.

**Comment by lukasmalkmus** [comment]
@rdallman Can you share which version of thrift was used? I wasn't able to get it working with `0.10.0`, `0.11.0` and `master`. I used dep aswell.

**Comment by rdallman** [comment]
hey @lukasmalkmus am using 272470790ad6db791bd6f9db399b2cd2d5879f74 for thrift. cheers.

**Comment by lukasmalkmus** [comment]
Thanks fore the fast response. Unfortunately I can't get it to work. Maybe it's just late and I need a coffee 😄 Since thrift isn't a direct dependency I used an `[[override]]` in the Gopkg.toml but the version I get doesn't expose the interface wanted by the generated code in the opencensus package.

**Comment by rdallman** [comment]
rats. when i was battling this I did end up doing a full:

* `rm -rf $GOPATH/pkg/dep`
* `rm -rf vendor/`
* `rm Gopkg.lock`

and the relevant bits of `Gopkg.toml` are as you describe:

```
[[constraint]]
  name = "go.opencensus.io"
  version = "0.6.0"

[[override]]
  name = "git.apache.org/thrift.git"
  revision = "272470790ad6db791bd6f9db399b2cd2d5879f74"
```

sometimes dep can be mean, maybe nuking could help. with glide it was usually the magic touch required *sigh*

**Comment by lukasmalkmus** [comment]
Ah thanks! I used the wrong import path (the thrift mirror on Github) which I did use in another project.  Would have taken me a night and a full can of coffee to get that by myself. Cheers mate 👍
