### ISSUE TITLE
Make it possible to replace the TraceID/SpanID generation algorithms

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#643]
To support special formats as required by some backends (XRay) we should make the TraceID/SpanID algorithms pluggable. 

See: https://github.com/census-instrumentation/opencensus-specs/issues/64

**Comment by odeke-em** [comment]
Am not sure what @bogdandrutu will think of this change but the last time I spoke with him, there was a reservation towards allowing this.

**Comment by ramonza** [comment]
I think his concern was with replacing the algorithm entirely (which was my original suggestion). This is a more gradual change that users can opt in to.

**Comment by rakyll** [comment]
We briefly chatted about this issue to depend on NewSpanWithRemoteParent with custom ID generation. Btw, Bogdan's concern was not to introduce a new generator.
