### ISSUE TITLE
We need a way to explicitly check errors from stats exporters

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#645]
Stats exporters should provide an optional method to explicitly type-check all views on registration. 

When we make changes to view definitions, these will silently fail if the view definitions are already defined e.g. in Stackdriver.

**Comment by odeke-em** [comment]
I thought that the common use case was never changing a view's definition?

**Comment by ramonza** [comment]
@odeke-em  that makes it all the more important to know when you have accidentally done this in an incompatible way.

**Comment by rakyll** [comment]
Is this a real problem?

**Comment by ramonza** [comment]
spoke offline. for now, we can rely on logging and/or OnError function (which I forgot about)
