### ISSUE TITLE
plugin/ochttp: invalid Measures for *ResponseCountByStatusCode views cause prometheus `inconsistent label cardinality` error

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#659]
Running the program below
```go
package main

import (
	"context"
	"log"
	"net/http"

	"go.opencensus.io/exporter/prometheus"
	"go.opencensus.io/plugin/ochttp"
	"go.opencensus.io/stats"
	"go.opencensus.io/stats/view"
)

func main() {
	pe, err := prometheus.NewExporter(prometheus.Options{})
	if err != nil {
		log.Fatalf("Creating prometheus Exporter error: %v", err)
	}
	view.RegisterExporter(pe)

	if err := view.Register(ochttp.DefaultServerViews...); err != nil {
		log.Fatalf("Register ochttp.DefaultServerViews error: %v", err)
	}

	points := []float64{0, 1, 10, 20, 40, 80, 160, 180, 250, 500, 800, 1e3, 1.2e3, 2.2e3, 4.3e3,
		9.7e3, 5e2, 17.2e2, 20e1}
	go func() {
		ctx := context.Background()
		for _, point := range points {
			stats.Record(ctx, ochttp.ServerLatency.M(point))
		}
	}()

	mux := http.NewServeMux()
	mux.Handle("/metrics", pe)
	log.Fatal(http.ListenAndServe(":9988", pe))
}
```

I get
```shell
$ go run main.go 
2018/03/29 23:51:15 Failed to export to Prometheus: inconsistent label cardinality
2018/03/29 23:51:15 Failed to export to Prometheus: inconsistent label cardinality
```
and from examining
https://github.com/census-instrumentation/opencensus-go/blob/8069fe56546c2cdcfbeb5290f5c6130590927308/plugin/ochttp/stats.go#L102-L109

and

https://github.com/census-instrumentation/opencensus-go/blob/8069fe56546c2cdcfbeb5290f5c6130590927308/plugin/ochttp/stats.go#L146-L153

those measures look wrong. Did we really mean to set those to *Latency yet the view is `ServerResponseCountByStatusCode`. I believe @songy23 once raised such a question in a conversation somewhere about `ServerResponseCountByStatusCode` but perhaps got lost in a meeting or so.

**Comment by odeke-em** [comment]
Also the Aggregation looks off, unless am wrong but I believe that's supposed to be a Distribution.

**Comment by ramonza** [comment]
Using Count on the latency measure is intentional and I think it should work. The latency is recorded at the end of each request, so Count()-ing should yield the number of requests.

Can we investigate more where the error comes from? Does this happen with a fresh Prometheus install? I suspect that it might be some metric definitions left over from previous versions of the code that might have had different view definitions. I would be concerned if this happens on a fresh Prometheus - in which case we need to get to the bottom of the cause of the error.

**Comment by johanbrandhorst** [comment]
Thanks, this was my opinion as well. Should this be added to the spec for clarification?

**Comment by johanbrandhorst** [comment]
So it seems the java exporter might already be checking for this: https://github.com/census-instrumentation/opencensus-java/blob/af71ea859f16594eff64a46b9c4773d6ea83aba9/exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java#L143-L144. I'm not sure if that means a decision has been made that this should be disallowed, but IMO the user experience is pretty bad if that was the case. As a user, ensuring that all measurements that a view is defined for have the tag in the context if the tag is in the view is... hard and confusing for new users I think.

**Comment by johanbrandhorst** [comment]
I've added https://github.com/census-instrumentation/opencensus-go/pull/988 to explore a fix for this, but lets decide what the correct behavior is first.
