### ISSUE TITLE
Traces don't appear in Stackdriver Traces

### ISSUE THREAD

**Issue by t-bast** [census-instrumentation/opencensus-go#662]
Hey guys,

I'm trying to instrument a set of micro-services running in Kubernetes on GCP with OpenCensus.
I've added code to create spans to some of my methods and deployed to GCP, but the Stackdriver Traces page stays empty.

I'm sure the code that creates the spans is running: I added a standard log line just before the span.End() and I see it in my pods' logs.
I'm also pretty sure the exporter is running: the first time I deployed, it was writing many errors to stderr because I didn't have a Stackdriver account associated with the GCP project. I created the Stackdriver account and those errors disappeared.

At that point I don't know how I can troubleshoot this, I don't have anything in my process' output and no obvious errors on the cloud console...
Are there some tips & tricks to figure out what could have gone wrong?

Thanks!

EDIT: I didn't see the recent change that made trace.SetDefaultSampler obsolete. The issue is that now we need to use trace.ApplyConfig. I think the Stackdriver exporter's GoDoc should be updated to reflect that :). Once that's changed I see my spans trying to get out (I have an error because of "insufficient authentication scopes" so it's not all good yet, but now I have a lead on what to investigate).

**Comment by rakyll** [comment]
> I think the Stackdriver exporter's GoDoc should be updated to reflect that 

Which godoc are you referring to? https://godoc.org/go.opencensus.io/exporter/stackdriver doesn't mention sampling.

**Comment by t-bast** [comment]
I thought I saw in the example a call to set the sampler but I'm not seeing it now so I was probably wrong :)

Everything works properly now, you can close the issue. Thanks!
________________________________
