### ISSUE TITLE
Issue getting Jaeger

### ISSUE THREAD

**Issue by bweston92** [census-instrumentation/opencensus-go#674]
```
$ docker run --rm -it golang go get "go.opencensus.io/exporter/jaeger"
# cd .; git clone https://git.apache.org/thrift.git /go/src/git.apache.org/thrift.git
Cloning into '/go/src/git.apache.org/thrift.git'...
fatal: repository 'https://git.apache.org/thrift.git/' not found
package git.apache.org/thrift.git/lib/go/thrift: exit status 128
```

**Comment by johanbrandhorst** [comment]
See https://github.com/census-instrumentation/opencensus-go/pull/672

**Comment by johanbrandhorst** [comment]
This is making it impossible to use opencensus-go with `golang/dep` right now, while I appreciate that we depend on Zipkin here, how can we track their progress on updating this?

**Comment by johanbrandhorst** [comment]
I temporarily forked opencensus-go with the imports replaced: https://github.com/johanbrandhorst/opencensus-go. If you need something right now, feel free to clone it. I will destroy it once this has been resolved upstream.

**Comment by johanbrandhorst** [comment]
For reference: https://issues.apache.org/jira/projects/THRIFT/issues/THRIFT-4542?filter=allopenissues

**Comment by bweston92** [comment]
Thanks

**Comment by johanbrandhorst** [comment]
I've since deleted my fork, see https://github.com/census-instrumentation/opencensus-go/issues/675 for a solution for dep users.

**Comment by bweston92** [comment]
Amazing, I did ask them in Slack yesterday with no reply, thanks!
