### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#675]
Build is broken due to the broken Thrift import paths, see https://issues.apache.org/jira/browse/THRIFT-4542.

This is affecting us due to the Jaeger and Zipkin exporters.

**Comment by johanbrandhorst** [comment]
This still doesn't fix the case for users of `golang/dep` which will still attempt to clone the old repo. I think we should reopen this issue or open a new tracking issue for migrating to the new import path.

**Comment by johanbrandhorst** [comment]
For dep users, the following will work (modify versions as necessary):

```
[[constraint]]
  branch = "master"
  name = "go.opencensus.io"

[[override]]
  name = "git.apache.org/thrift.git"
  source = "github.com/apache/thrift"
  version = "0.11.0"
```
