### ISSUE TITLE
trace: Span.End should return ASAP if there are no exporters and perhaps drop spanData

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#681]
Just examining this code 
https://github.com/census-instrumentation/opencensus-go/blob/ead56c48fbe540f3601b21ff9eeea1fb60300740/trace/trace.go#L214-L234

If we don't have any exporters and if not `(*Span).IsSampled()`, we'll be doing wasted work here
https://github.com/census-instrumentation/opencensus-go/blob/ead56c48fbe540f3601b21ff9eeea1fb60300740/trace/trace.go#L225-L233

Perhaps let's remove that? In addition perhaps we should drop `(*Span).data` so that any further invocations of `End()` will return asap on this call
https://github.com/census-instrumentation/opencensus-go/blob/ead56c48fbe540f3601b21ff9eeea1fb60300740/trace/trace.go#L215-L217

**Comment by rakyll** [comment]
We collect span data also for the zpages. It is not just for exporting.

**Comment by basvanbeek** [comment]
closed by #832
