### ISSUE TITLE
Publish explicit dependency version requirements

### ISSUE THREAD

**Issue by johanbrandhorst** [census-instrumentation/opencensus-go#684]
Using OpenCensus for Go with gRPC depends on recent versions of gRPC-Go. However, this dependency is never made explicit anywhere (such as a `Gopkg.toml` or `go.mod` file). I understand this is a bit in flux at the moment with the vgo proposal, but I think we should discuss how we make these version dependencies explicit, so I'm opening this issue for the purposes of that discussion.

Personally, I would welcome simply defining a `Gopkg.toml` and generate a `Gopkg.lock` and check those in right now. It would help users of `golang/dep` to get started with OpenCensus, and we could also include a fix for  https://github.com/census-instrumentation/opencensus-go/issues/675 in the dependency declaration.

Later on, as vgo is merged into the standard tool, we can move to defining a `go.mod` file.

**Comment by rakyll** [comment]
I am happy with this approach as long as we don't vendor library dependencies.

/cc @odeke-em @ramonza for input.
