### ISSUE TITLE
exporter/stackdriver: separate ClientOptions for monitoring and trace

### ISSUE THREAD

**Issue by zombiezen** [census-instrumentation/opencensus-go#691]
I would like to pass OpenCensus the gRPC connections directly for Monitoring and Trace, but the current API uses the same ClientOptions list for both of them, which doesn't let me pass in `option.WithGRPCConn`.

**Comment by ramonza** [comment]
This sounds reasonable. Out of curiosity, what difference gRPC options are needed for Monitoring vs Trace?
