### ISSUE TITLE
Make all span starting APIs take a context

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#694]
Go runtime/trace package is soon going to support user events. See http://tip.golang.org/pkg/runtime/trace.

In order to provide execution tracer tasks and spans from the OpenCensus library, we should make sure we are not dropping the parent runtime/trace tasks and spans.

Hence I am suggesting us to remove NewSpanXXX functions and replace them with:

```
func StartSpanWithOptions(ctx context.Contex, name string, o StartOptions) (context.Context, *Span)
func StartSpanWithRemoteParent(ctx context.Contex, name string, parent SpanContext o StartOptions) (context.Context, *Span)
```

**Comment by hyangah** [comment]
Alternatively, if the Span carries the associated context in it, you can do the following without changing the API.

<pre>
type Span struct {
   ...
   tracedCtx context.Context
   traceEnd func()
   ...
}

func NewSpan(name string, parent *Span, o StartOptions) *Span {
    var parentSpanContext SpanContext
    pctx := context.Background()
    if parent != nil {
        parentSpanContext = parent.SpanContext()
        pctx = parent.tracedCtx
    }  
    return startSpanInternal(pctx, name, parent != nil, parentSpanContext, false, o)
  }
</pre>

One caveat is the newly added reference to the context.Context object - the parent context and its ancestors will live until the Span is ready for being GC'd.

**Comment by ramonza** [comment]
Proposal for this: https://github.com/census-instrumentation/opencensus-go/pull/696
@rakyll what do you think?

**Comment by rakyll** [comment]
@hyangah, we didn't want to pin the context given it is not recommended due to the different lifetimes of span and context objects. I think #696 is quite better.

**Comment by hyangah** [comment]
If it's okay to deprecate old apis, great. 

BTW the difference between span and context objects (so how the current API looks) will still prevent from wiring up the span's methods (e.g. Annotate) with trace.Log.

**Comment by ramonza** [comment]
@rakyll just to confirm, the ultimate goal here: is the idea that we want to automatically invoke runtime/trace methods when the similar OpenCensus functions/methods are called? E.g. we would call "runtime/trace".NewContext from within trace.NewSpan, and "runtime/trace".Logf from within span.Annotatef?

**Comment by rakyll** [comment]
@ramonza 

> the ultimate goal here: is the idea that we want to automatically invoke runtime/trace methods when the similar OpenCensus functions/methods are called? E.g. we would call "runtime/trace".NewContext from within trace.NewSpan, and "runtime/trace".Logf from within span.Annotatef?

Yes, we are considering about creating a runtime/trace task for each OpenCensus span. So if the user wants to see the runtime events, they can momentarily turn on the execution tracer and output some data that correlates with their distributed span.

Maybe we should pin the ctx in order to support runtime/trace.Logf in the future but we always need the incoming context anyways in order to runtime/trace.
