### ISSUE TITLE
plugin/ochttp: http.Handler doesn't set its span's Status, derived from the statusCode

### ISSUE THREAD

**Issue by brycekahle** [census-instrumentation/opencensus-go#700]
Reviewing the code in https://github.com/census-instrumentation/opencensus-go/blob/02b14064ad5f94ef466ddacdc1a90f03ae7e0cfa/plugin/ochttp/server.go I do not see the status code being recorded in the trace, only in stats.

**Comment by odeke-em** [comment]
Thank you very much for noticing and reporting this. I noticed it too late last night and early this morning when my server got a request for a non-existent file but the stackdriver trace showed no indication of the error
![screen shot 2018-04-12 at 1 31 58 pm](https://user-images.githubusercontent.com/4898263/38702608-e9f57f82-3e55-11e8-8c2b-455150f07e91.png)

I believe we can fix this by in server.go at the end of the tracker, doing a `span := trace.FromContext(t.ctx); span.SetStatus(status(t.statusCode))`

/cc @ramonza @rakyll

**Comment by rakyll** [comment]
@odeke-em, want to open a PR?

**Comment by bogdandrutu** [comment]
@odeke-em  Keep in mind that SD Trace may not show the status (need to check with the SD team about this).

**Comment by odeke-em** [comment]
>@odeke-em, want to open a PR?

@rakyll for sure :)


>@odeke-em Keep in mind that SD Trace may not show the status (need to check with the SD team about this).

@bogdandrutu with the change that I am thinking about, I was able to test and verify that bad status are shown by Stackdriver :)
### Before
![screen shot 2018-04-12 at 1 45 01 pm](https://user-images.githubusercontent.com/4898263/38703306-c614cefe-3e57-11e8-8cc3-160b9e4a8a0a.png)


### After
![screen shot 2018-04-12 at 1 45 11 pm](https://user-images.githubusercontent.com/4898263/38703303-c23dba5c-3e57-11e8-88d4-8f4a78ac5aec.png)
