### ISSUE TITLE
Reflect spec changes to the gRPC plugin

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#702]
The ocgprc package is not compatible with https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/gRPC.md anymore. Implement the recent changes on the spec.

**Comment by ramonza** [comment]
Isn't this a duplicate of https://github.com/census-instrumentation/opencensus-go/issues/687 for which there is https://github.com/census-instrumentation/opencensus-go/pull/689?

**Comment by rakyll** [comment]
Yes, it is a duplicate and is closed via https://github.com/census-instrumentation/opencensus-go/pull/689.
