### ISSUE TITLE
Problematic inner mapping of HTTP Status code to OC Status

### ISSUE THREAD

**Issue by basvanbeek** [census-instrumentation/opencensus-go#713]
ochttp uses an unexported function to map HTTP status codes to unexported trace status codes which locks out usage by other instrumentation that might want to do this. 

Since this contains mappings that we really want to be consistent across instrumentation dealing with HTTP it might be better to refactor this and place the mappings in a separate package of opencensus-go.  Since it is suggested that OC Status codes should follow https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto it might make sense to create a new package holding generated source from this proto together with idiomatic mappings for instrumentations to re-use. This could expand beyond HTTP. 

Currently we lack explicitness and proliferation of instrumentation will probably degrade the quality of Status reporting and usage in the various tracing exporters.

**Comment by rakyll** [comment]
We should export status codes from the trace package ideally, we haven't done it yet because we were debating about the status codes and whether we should follow the rpc/code.proto.

/cc @bogdandrutu
