### ISSUE TITLE
Issues with Zipkin backend

### ISSUE THREAD

**Issue by mdemirhan** [census-instrumentation/opencensus-go#719]
## Setup
Using a GKE kubernetes cluster with Istio installed. When my application receives a call, it is decorated by Istio sidecar with B3 propagation headers. Upon receiving a request, my code calls 3 other URLs within the cluster and use OpenCensus to instrument the end to end traces.

The outcome looks as follows in Zipkin:
![osscreen1](https://user-images.githubusercontent.com/4033879/39073910-571f5f8e-44a4-11e8-8d9a-6970b782a572.png)

With OpenZipkin library instead of OpenCensus, result is:
![osscreen2](https://user-images.githubusercontent.com/4033879/39074131-1617affe-44a5-11e8-9d3c-c6377685f370.png)

With OpenCensus, the calls are not ended properly. For example, the first child seems like a new parent span for all upcoming children, but it is not. It is just one call and another one and so on. With OpenZipkin, the graph looks correct.

Code is as follows:
```go
	// Tracing setup
	reporter := httpreporter.NewReporter("http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans")
	defer reporter.Close()
	localEndpoint, err := openzipkin.NewEndpoint("TelemetrySample", "localhost:8080")
	if err != nil {
		log.Fatalf("Unable to create zipkin local endpoint: %+v\n", err)
	}

	zipkinExporter := zipkin.NewExporter(reporter, localEndpoint)
	trace.RegisterExporter(zipkinExporter)
	trace.ApplyConfig(trace.Config{DefaultSampler: trace.AlwaysSample()})

	// Use an http.RoundTripper that instruments all outgoing requests with stats and tracing.
	client := &http.Client{Transport: &ochttp.Transport{Propagation: &b3.HTTPFormat{}}}

	// Implements an http.Handler that automatically extracts traces
	// from the incoming request and writes them back to the response.
	handler := &ochttp.Handler{Propagation: &b3.HTTPFormat{}, Handler: rootHandler(client)}

	mux := http.NewServeMux()
	mux.Handle("/", handler)
	http.ListenAndServe(":8080", mux)
...
func rootHandler(client *http.Client) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		getWithContext := func(url string) (*http.Response, error) {
			req, err := http.NewRequest("GET", url, nil)
			if err != nil {
				return nil, err
			}
			req = req.WithContext(r.Context())
			return client.Do(req)
		}

		// Simulate a few extra calls to other services to demostrate the distributed tracing capabilities.
		// In sequence, call three different other services.
		res, err := getWithContext("http://prometheus-system-np.monitoring.svc.cluster.local:8080")
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		defer res.Body.Close()

		res, err = getWithContext("http://grafana.monitoring.svc.cluster.local:30802")
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		defer res.Body.Close()

		// Let's call a non-existent URL to demonstrate the failure scenarios in distributed tracing.
		res, err = getWithContext("http://invalidurl.svc.cluster.local")
		if err != nil {
			log.Printf("Request failed: %v", err)
		} else {
			defer res.Body.Close()
		}

		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.WriteHeader(status)
		w.Write([]byte("Hello world!\n"))
		log.Printf("Request complete. Status: %v", status)
	}
}
```

**Comment by rakyll** [comment]
IMHO, we should have another round of discussion whether we want to end the span at (*Request).Body.Close.

Pro:

- More realistic latency for large and multipart responses.

Cons:

- In the Go ecosystem, most callsites defer Close already and we expect user to modify their source.
- Body reading can be represented as message receive events.

/cc @ramonza @odeke-em

**Comment by rakyll** [comment]
I agree that we should keep ending the span at Body.Close.

@mdemirhan, can we close this issue?

**Comment by mdemirhan** [comment]
@rakyll Yes, thanks for the follow up.

**Comment by adriancole** [comment]
Fyi most zipkin tracers complete on headers received. some do on body end,
some make subspans for the body. there is a doc somewhere about http model
we can chat about on the workshop next week
