### ISSUE TITLE
Proposal: trace.Span.Annotate should instead take the description then variadic attributes

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#723]
Currently trace.Span.Annotate's signature is 
https://github.com/census-instrumentation/opencensus-go/blob/785d2fa8133705aee38cf228ff1e8ac6c0055c25/trace/trace.go#L380

which means that I always have to create a slice of attributes, even though at times while annotating I just want to set the description e.g.
```go
span.Annotate([]trace.Attribute{}, "Started video batching")
```
I find myself tediously using the current API above.

This is quite an awkward method, I propose
```go
func (s *Span) Annotate(description string, attributes ...Attribute)
```

which naturally makes annotating a span equivalent to telling a story about the span and being variadic also means that users can add as many attributes without firstly making that slice
```go
span.Annotate("Processing features in the index",
          trace.Int64Attribute("count", n),
          trace.StringAttribute("stage", "processing"), 
          trace.BoolAttribute("pre_processed", true))
```
or even just
```go
span.Annotate("Queuing up content for indexing")
```

**Comment by rakyll** [comment]
You don't need to create a new slice, you can simply pass nil.

```
span.Annotate(nil, "Started video batching")
```

We preferred so the API is consistent with Annotatef.

**Comment by odeke-em** [comment]
Let's hold off before closing this issue.

Am not sure that consistency with Annotatef is a good API either. Sure passing `nil` works for my first use case, but
compare the other example that I had prepared
```go
span.Annotate("Processing features in the index",
          trace.Int64Attribute("count", n),
          trace.StringAttribute("stage", "processing"), 
          trace.BoolAttribute("pre_processed", true))
```

vs the current one

```go
span.Annotate([]trace.Attribute{
          trace.Int64Attribute("count", n),
          trace.StringAttribute("stage", "processing"), 
          trace.BoolAttribute("pre_processed", true),
}, "Processing features in the index")
```

I believe we are restricting ourselves to try to get to parity with Annotatef which is something that can be solved by using`fmt.Sprintf`. The first parameter should be the description which tells the story of the annotation and then any other annotations follow, not the other way, IMHO.

**Comment by basvanbeek** [comment]
Since not all of the officially supported tracing backends allow for attributes to be part of an annotation (ex. Zipkin) it would be also better to go for the variadic version as suggested by @odeke-em. This highlights the optionality of attributes better while description really is a required parameter.

**Comment by rakyll** [comment]
> I believe we are restricting ourselves to try to get to parity with Annotatef which is something that can be solved by using fmt.Sprintf

We never want to format the string if we are not going to export it. The evaluation is always done lazily for formatted strings.

**Comment by ramonza** [comment]
I would propose that we leave it as-is. There is no easy way to change the argument order - we would need to deprecate it and come up with a new method name.

**Comment by ramonza** [comment]
If we really hate it I think we need to introduce a new method name and deprecate both Annotate and Annotatef.

**Comment by rakyll** [comment]
I agree that breaking this API is quite complicated at this point. Btw, with the following formatting, the message still stands out better:

```
span.Annotate(
    []trace.Attribute{
        trace.Int64Attribute("count", n),
        trace.StringAttribute("stage", "processing"),
        trace.BoolAttribute("pre_processed", true),
    },
    "Processing features in the index",
)
```

**Comment by basvanbeek** [comment]
I really dislike this API call's signature and personally think that by keeping it this way we immediately have technical debt as explained previously

I think it also highlights that the project shouldn't have been at a stage where API breakage is considered a bigger problem then getting the initial API right.

**Comment by bogdandrutu** [comment]
Agree that we should finalize this asap. Maybe this can be our last breaking change. We have to stop doing breaking change at some point @basvanbeek

**Comment by ramonza** [comment]
Let's come up with a new method then we can deprecate the old ones. Changing an existing method causes all sorts of pain. We can eventually remove the deprecated method in line with the [deprecation policy](https://github.com/census-instrumentation/opencensus-go#deprecation-policy).

**Comment by basvanbeek** [comment]
I think it is. First 0.1.0 release was mid December which is only 4 months ago. Obviously we don't have visibility into all projects referencing the Annotate methods but doing a quick lookup on sourcegraph reveals it has not widely proliferated yet in public github projects: https://sourcegraph.com/github.com/census-instrumentation/opencensus-go/-/blob/trace/trace.go#L380:16$references:external

**Comment by ramonza** [comment]
This is used by Go Cloud SDK: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/48541a8078698ecfa389e0bc6e005ee3363e5f85/bigtable/go18.go#L67

We have given them assurances that we will not break backwards compatibility except as outlined in the deprecation policy and so the only way to change the signature would be to add a new method and deprecate the old.

**Comment by basvanbeek** [comment]
@ramonza so I'm not sure how anyone can think it is a good idea for a young project that has a scope to work on establishing really good interop with existing tracing / metricss system to give such guarantees with a code base as young as a few months... that's basically asking for problems, chopping off legs and promising items you really shouldn't and honestly can't.

**Comment by rakyll** [comment]
I am wondering what's the cost of breaking this API. If we need to fix the SDK, it is trivial.

If we are ok to name it differently, I am suggesting us to name it `Log`.

We also had a performance concern about lazily evaluating strings. We shouldn't necessarily undermine the cost, especially tracing is almost every time aggressively downsampled. IMHO, performance concern is more critical than the usability of this API.

**Comment by basvanbeek** [comment]
@rakyll I agree with performance being critical that should be a first. 

@ramonza I'm not contesting the soundness of the idea of the deprecation policy, i'm saying it came too early and the project is too young for the given guarantees.

**Comment by rakyll** [comment]
@odeke-em, what's your solution to the lazy evaluation problem? We try to make these libraries as low overhead as possible if user don't want to collect and utilize the data. We cannot format annotations all across  and should provide a lazy annotatef.

**Comment by ramonza** [comment]
I don't think we can break the deprecation policy for this case. If we want to continue this discussion I am happy to review a pull request that's compatible with the deprecation policy. Otherwise we should close this issue.

**Comment by odeke-em** [comment]
>Agree that we should finalize this asap. Maybe this can be our last breaking change. We have to stop doing breaking change at some point @basvanbeek

@bogdandrutu, in deed, although I believe @basvanbeek just got familiar with this project recently :)
I think the hard deadlines for API stability precluded the experience and exposure that @basvanbeek brings from his tracing and monitoring engagements, and moreover we encounter API awkwardness when making integrations of which these are going on currently.


>This is used by Go Cloud SDK: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/48541a8078698ecfa389e0bc6e005ee3363e5f85/bigtable/go18.go#L67

@ramonza we are talking about `Annotate` though :) Although I guess removing or deprecating `Annotate` alone would leave `Annotatef` inconsistent :(
`Annotatef` has a different internal makeup, but I agree about the points about the trade off between stability and adoption.


>@odeke-em, what's your solution to the lazy evaluation problem?

@rakyll, TBH I don't have one yet. If the goal is to return if `!s.IsRecording()` and only invoke `fmt.Sprintf` when necessary, we can keep `Annotatef` as is(but now that's an inconsistency) I think now that the only API that had a thousand ways to add an annotation still gave us the flexibility of having an API that focuses on description being the most important part of an annotation before it was simplified in https://github.com/census-instrumentation/opencensus-go/pull/287.
 I think that the lazy printing was an early optimization that then dictated the future APIs. I am tending towards perhaps sunsetting `Annotate` in favour of `AddAnnotation` which matches the other languages. Lazy print evaluation has great advantages like we've noticed though.

In regards to similarity with other languages, and the value of `AddAnnotation`, almost all the other language implementations already have `add_annotation`, `put_annotation`, `annotation` that concretely express that the description is the most import part of the time event addition method `*nnotate`

Language|Method name| Links
---|---|---
C++|AddAnnotation|https://github.com/census-instrumentation/opencensus-cpp/blob/8bcb145972d877cb838bb7984db10e70ff2b9d47/opencensus/trace/span.h#L105-L106
Erlang|annotation|https://github.com/census-instrumentation/opencensus-erlang/blob/394992f0fbb118dc49223d5953a27b73e69d35a9/src/oc_span.erl#L104
Java|addAnnotation|https://github.com/census-instrumentation/opencensus-java/blob/86dadeeae96698c24489ce5817e6474224be8802/impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java#L299 and https://github.com/census-instrumentation/opencensus-java/blob/86dadeeae96698c24489ce5817e6474224be8802/impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java#L319
~~PHP~~|~~addTimeEvent~~|~~https://github.com/census-instrumentation/opencensus-php/blob/cd2b4d574488382e37e4e49d998947f54fa6c14c/src/Trace/Span.php#L348~~
Python|add_annotation|https://github.com/census-instrumentation/opencensus-python/blob/fbbe9c56810e3e2129d6e8dafba78dde6584dfd0/opencensus/trace/span.py#L179
Ruby|put_annotation|https://github.com/census-instrumentation/opencensus-ruby/blob/214cce7fa1d3ac5ea68f2efde284673f9a6db46e/lib/opencensus/trace/span_builder.rb#L206

**Comment by rakyll** [comment]
I'd defer this to @bogdandrutu and wait for him to say something about how critical it is for us to lazily evaluate annotation description.

**Comment by bogdandrutu** [comment]
@odeke-em can you draft a PR to show me how your proposal will look.

@rakyll I think it is important for performance, but this can be achieved also by writing:
```go
if (span->IsRecordingEvents()) {
  span->AddAnnotation(...);
}
```

Is it any best practice in Go to achieve something like C++ macros?
```cpp
#define PRINTF(span, ...) \
  do {
    if (span->record_events()) {\
      span->AddAnnotation(...);
    }\
  } while (0)
```

**Comment by rakyll** [comment]
We don't have a way to replace the behavior of fmt package.

The only other suggestion I have is to expect a fmt.Stringer (like we did at https://godoc.org/golang.org/x/net/trace#Trace) and provide utilities that builds a fmt.Stringer. But it'd be a disaster in terms of usability.

```
func Annotate(desc fmt.Stringer, a ...Attribute)
```

**Comment by odeke-em** [comment]
@rakyll this looks like we are in a stalemate, if we want lazy printing yet would like to keep description as the first parameter. To break that stalemate, we can go with chaining, but that can easily be misused by users. Here is a prototype for the chaining

```go
type Attributer interface {
	AddAttributes(attributes ...Attribute)
}

func (s *Span) BuildAnnotation(fmt_ string, args ...interface{}) Attributer {
	if !s.IsRecording {
		return noopAttributer
	}
	return s.chainAttributer(fmt_, args...)
}

type noopAttributer int

func (noopAttributer) AddAttributers(_ ...Attribute) {}

var aNoopAttributer = noopAttributer(0)
var _ Attributer = aNoopAttributer

func (s *Span) chainAttributer(msgFmt_ string, args ...interface{}) Attributer {
	if len(attributes) != 0 {
		a = make(map[string]interface{})
		copyAttributes(a, attributes)
	}
	return &annotationAdder{
           span: s,
           cur: Annotation{
		Time:    time.Now().UTC(),
		Message: fmt.Sprintf(msgFmt_, args...),
	}}
}

type annotationAdder struct {
	cur *Annotation
        span *Span
}

func (ad *annotationAdder) AddAttributes(attrs ...Attribute) {
       if ad == nil || ad.span == nil {
               return
       }
       ad.span.Lock()
       s := ad.span
       ad.cur.Attributes = append(ad.cur.Attributes, attrs...)
       s.Annotations = append(s.Annotations, ad.cur)
       ad.span = nil
       s.Unlock()
}
```

```go
span.Annotatef("Retrying in %d seconds", backoff).Annotate(trace.BoolAttribute("failed", "true"), trace.Int64Attribute("n", n))
```

Okay, in regards to the lazy printing it begs the question as for best practices ephemeral or non-ephemeral descriptions?
Is it better to have an ephemeral annotation description (with the variable `delay`) as in
option 1)
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/b26d29c8b23531b39f5f0d67a3f668d5d92bc5c3/spanner/read.go#L507
```go
tracePrintf(d.ctx, nil, "Backing off stream read for %s", delay)
```

or to instead to make a non-ephemeral annotation description and then include delay as the attribute?
option 2)
```go
tracePrintf(d.ctx, []trace.Attribute{trace.Int64("delay", delay)}, "Backing off stream read")
```

 If the better practice is to use `delay` as the attribute as in option 2, then we've spent time solving a problem that is non-existent and based off perhaps misuse unfortunately.

@bogdandrutu in regards to
>@odeke-em can you draft a PR to show me how your proposal will look.

For starters, it looks like this:

```go
func (s *Span) Annotate(description string, attributes ...Attribute)
```
and the lazy printing option can be the Annotatef variant with chaining or as is currently.

## Sample usage
### Without attributes
```go
span.Annotate("Pipeling requests")
```

### With one attribute
```go
span.Annotate("Pipelining requests", trace.Int64Attribute("count", n))
```

### With attributes
```go
span.Annotate("Pipelining requests",
          trace.Int64Attribute("count", n),
          trace.StringAttribute("stage", "processing"), 
          trace.BoolAttribute("pre_processed", true))
```

**Comment by ramonza** [comment]
I don't think it's useful to keep this open. Happy to review PRs that add methods (maybe Log/Logf?) in a backwards-compatible way and/or deprecate the existing methods.
