### ISSUE TITLE
Support for introducing custom tags to gRPC/HTTP metrics

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#746]
Consider the example of a server that serves results either from database or a cache. One important dimension you might want to capture as part of all your HTTP/gRPC metrics is whether a particular request was served from cache or not. 

Currently it isn't possible to augment the set of tags applied to the stats.Record call made by ocgrpc or ochttp. In OpenCensus Java I believe it is possible to accomplish this by changing the thread-local tags in the thread processing of the request but in Go, Context is immutable so a similar approach is not possible.

**Comment by zeako** [comment]
I don't understand how the context immutability is an issue, you can pass along a context with your own set of keys (for example you can make your own handler which wraps `ochttp.Handler` and passes along a context to it), 
still though it isn't possible (yet?) to pass mutators for to the relevant handler.

**Comment by ramonza** [comment]
Consider the caching example above. You only know the correct value of the "was_cached" tag after the request has finished processing. How do you pass this up from inside your HandlerFunc to the ochttp.Handler that wraps it?

**Comment by groob** [comment]
could the oc handler take a custom finalizer callback as an option?

**Comment by ramonza** [comment]
Another use of this would be for HTTP responses that are logically errors but that return a 200 OK code for compatibility reasons. It would be interesting for the user to be able to add an "error" tag which could be used to break out errors, otherwise they would have no way to tell error responses from OK responses.

**Comment by groob** [comment]
I like the functions that Go-Kit provides that enable you to instrument the HTTP handler. 

```
// RequestFunc may take information from an HTTP request and put it into a
// request context. In Servers, RequestFuncs are executed prior to invoking the
// endpoint. In Clients, RequestFuncs are executed after creating the request
// but prior to invoking the HTTP client.
type RequestFunc func(context.Context, *http.Request) context.Context


// ServerFinalizerFunc can be used to perform work at the end of an HTTP
// request, after the response has been written to the client. The principal
// intended use is for request logging. In addition to the response code
// provided in the function signature, additional response parameters are
// provided in the context under keys with the ContextKeyResponse prefix.
type ServerFinalizerFunc func(ctx context.Context, code int, r *http.Request)
```

so the request func can be use to [Populate a context](https://github.com/go-kit/kit/blob/1b1a55c53e898557056c7f3fe05be3760a48f172/transport/http/request_response_funcs.go#L49) which is then used in the finalizer.

**Comment by ramonza** [comment]
So you would install something internally mutable (like a pointer to a struct) into the context in RequestFunc, mutate it in your handler/endpoint and then read it back in ServerFinalizerFunc?

**Comment by rakyll** [comment]
"was_cached" is a dimension you want to collect at the handler that does caching or not, not at the client.

**Comment by rakyll** [comment]
This is again a cross-language proposal and needs to be discussed at the specs repo.
