### ISSUE TITLE
Would you like this linkerd-flavoured-Zipkin trace propagator?

### ISSUE THREAD

**Issue by negz** [census-instrumentation/opencensus-go#752]
https://github.com/negz/linkin

👋 Is there any interest in adding the above linkerd-flavoured-Zipkin-propagation package to Opencensus proper?

As I'm sure you're aware [linkerd](http://linkerd.io/) is a popular service mesh. It offers semi-automatic Zipkin tracing, but propagates trace context via a linkerd-specific HTTP header (`l5d-ctx-trace`) in order to avoid interfering with any existing `X-B3-*` headers.

linkerd requires the services that leverage its proxy mesh to forward the `l5d-ctx-trace` from parent requests to any children they spawn in order to form a full trace. Opencensus's API makes it a great fit for handling that propagation, as well as for creating in-application spans that don't relate to HTTP calls.

I've put this together for use at [Planet](http://planet.com), but I figure it may be useful to others. Note that per https://github.com/linkerd/linkerd/issues/1447 I'm not _really_ sure we're supposed to consume or modify the `l5d-ctx-trace` header, but it's the only option for the time being.

**Comment by ramonza** [comment]
Awesome, yes, I definitely think this is useful, happy to review PR against this repo. Probably fits alongside the existing B3 support in `plugins/ochttp/propagation`.

Alternative considered: put in it's own repo in census-ecosystem. I think this would be overkill for a propagation format that has no external dependencies and is for an open source project, so I am recommending to put this in the main opencensus-go repo where we already have the B3 propagation.

**Comment by rakyll** [comment]
I think  ecosystem organization is a great place for a linkerd specific package. We are trying to reduce the number of vendor specific components in the core repos. B3 is in the core repo because it is a common propagation format for many backends and our current default for HTTP.

**Comment by ramonza** [comment]
I will defer to @rakyll on this. @negz would you like us to create a repo in census-ecosystem for this? My opinion is that there's no real benefit to moving it into another org vs. just keeping the repo you already have. We could link to your repo in our README if we added a section on integrations (which I have been meaning to add anyway).

**Comment by adriancole** [comment]
Good citations.. I think it shouldn't go into the main repo even if it works because folks at linkerd aren't 100% keen on the idea. IOTW we shouldn't propagate something (hardy har har) that isn't encouraged upstream by bundling it in core. Meanwhile, it indeed is something asked about before, and sharing work is a good thing, disclaimers applied.

**Comment by negz** [comment]
@ramonza I'm happy for it to stay where it is, unless you all think there'd be value in adding it to the ecosystem repository. I'll close this for now; feel free to link it from said README section. :)

**Comment by ramonza** [comment]
I don't think there really would be value in moving it. It is unfortunately quite an arduous process for us to add new repos there so I don't think it is worth it. I will add it to the README soon. I'm sorry for causing you to do all this unnecessary work :(
