### ISSUE TITLE
ocgrpc: ClientHandler does not create a new trace

### ISSUE THREAD

**Issue by vaijab** [census-instrumentation/opencensus-go#767]
The behaviour that I am about to describe below might be intentional by design, if this is the case, it would be great to understand logic behind it.

On gRPC client end, I create a new gRPC client with:
```golang
c, err := grpc.Dial("localhost:8000", grpc.WithStatsHandler(
    &ocgrpc.ClientHandler{}), 
    grpc.WithInsecure()
)
```
I expect `ocgrpc.ClientHandler{}` to create a new trace, but it does not. I suspect trace isn't there is because `ClientHandler{}` creates a new context, then starts a new trace, writes it to the context, but the context object is never passed through to the client and then the client overwrites the context with `ctx := context.Background()`, because one is needed to make a gRPC call.

The only way to create a new trace from within a client is to do it explicitly with:
```golang
ctx := context.Background()
ctx, span := trace.StartSpan(ctx, "NewTrace", trace.WithSampler(trace.AlwaysSample()))
// Then make a gRPC call using ctx
```

I am happy to dig through the code to track down a bug, if indeed this is not a design feature?

**Comment by ramonza** [comment]
ocgrpc.ClientHandler should start new traces. Without any arguments, it is subject to the default sampling policy which you can change using trace.ApplyConfig.

The behavior should be tested by: plugin/ocgrpc/trace_test.go:119 (TestSingle)

StartSpan is called here: plugin/ocgrpc/trace_common.go:39 (traceTagRPC)

Is it the case that even when when setting the default sampler to AlwaysSample you see custom spans but no spans created by ocgrpc.ClientHandler?

**Comment by vaijab** [comment]
@ramonza you're absolutely right. The following did the trick:

```diff
c, err := grpc.Dial("localhost:8000",           
    grpc.WithStatsHandler(&ocgrpc.ClientHandler{
+       StartOptions: trace.StartOptions{       
+          Sampler: trace.AlwaysSample(),      
        }}),                                    
    grpc.WithInsecure(),                        
)                                               
```
Thank you!
