### ISSUE TITLE
add zpages AppendHandlers

### ISSUE THREAD

**Issue by nfisher** [census-instrumentation/opencensus-go#783]
Motivation
-----------

Currently the zpages init wires up the handler on behalf of the user. It would be nice if there were an alternative function that takes `*ServerMux` as a parameter. This would allow additional handler paths to be added to the Mux and allow the zpages to be anchored to the root path should it be desired.

Example
---------

```golang
func adminListener(adminAddr string, promExporter *prometheus.Exporter) {
  mux := http.NewServerMux()
  zpages.Handler = mux // let the GC clean up the mux
  mux.Handle("/metrics", promExporter)
  zpages.AppendHandlers(mux)
  adminServer := http.Server{
    Addr: adminAddr,
    Handler: mux,
  }

  log.Printf("binding admin server to %s", adminAddr)
  log.Fatal(adminServer.ListenAndServe())
}
```

Impact
-------

The addition of this function would provide an alternate way to initialise the mux and is therefore an expansion of the public API without impacting any existing interfaces.

There is a minor memory allocation overhead for the unused `zpages.Handler` which could be addressed by setting the Handler to the mux in the above example. I am not aware of any other impact that would result from this change.

In general my preference would be to avoid the use of `init` functions but I appreciate there is benefit in terms of usability and reduced boilerplate.

**Comment by rakyll** [comment]
Is https://github.com/census-instrumentation/opencensus-go/pull/774 improving this case?

**Comment by nfisher** [comment]
Commented in the PR. If changing `http.Handler` to `*http.ServerMux` works for you then I think this could be closed.

**Comment by nfisher** [comment]
#774 LGTM!
