### ISSUE TITLE
Mechanism for adding common tags (e.g. pid, service name, hostname, version)

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#786]
This might be solved a number of ways but I wanted to capture the abstract requirement before delving in to the various ways it could be solved now or in future.

It's a common requirement to want to annotate metrics with application-defined tags, that include characteristics of the host/container we are running in, the current binary and configuration etc.

The most straightforward approach for this might be to just add them to the context at a very high level. This would work but unfortunately it would mean that they would be propagated on all outgoing instrumented calls (e.g. all GCP client calls). This is not desired because these tags are only relevant to the current process.

**Comment by ramonza** [comment]
If we implemented https://github.com/census-instrumentation/opencensus-specs/issues/110 then we would be able to do this in the "obvious" way by scoping those tags as local only.

It still might be a little tricky to get these tags into all the instrumented places e.g. the HTTP and gRPC plugins.

I'm leaning towards a solution that involves configuring a global set of tags, something like:
```go

stats.ApplyConfig(stats.Config{
  DefaultTags: []tag.Mutator{
    tag.Upsert(key, val), ...
   }
})

```

What do you think @rakyll @g-easy  ?

**Comment by vaijab** [comment]
Does this cover stats/metrics only? What about traces?

**Comment by g-easy** [comment]
@ramonza Would the global tags be part of a default context? Or would they be applied at Record time?

@vaijab We already add the OpenCensus library version and language as an Attribute on Spans. It would make sense to add some of these common tags also.

**Comment by ramonza** [comment]
@vaijab I had only considered this for tags, not trace attributes.

@g-easy not sure what the difference would be. We would probably want contextual tags to overwrite the default if they have the same key. Perhaps the difference is in whether they need to be explicitly mentioned in the view: I think they should be.

**Comment by vaijab** [comment]
> I had only considered this for tags, not trace attributes.

@ramonza gotcha. What I am wondering about is (sorry if this is slightly unrelated to this issue), how can I add a tag/attribute/property to a trace that is then propagated across all spans and exported to Stackdriver Tracing?

**Comment by vaijab** [comment]
> It seems like if you have it on a single span you could always search for traces based on that attribute, no?

That's a very good point. Thanks!

**Comment by ramonza** [comment]
I implemented this for Stackdriver specifically to work around an issue a user was having with the opencensus_task label: https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/20

**Comment by rakyll** [comment]
How does this feature request relate to the monitored resources?

**Comment by ramonza** [comment]
MonitoredResources are a subset of what you might want to put into common tags. So they contain dimensions that identify the instance. I think there are use cases for common tags other than what goes into MonitoredResource.

**Comment by rakyll** [comment]
This is not a language-specific change. Please file a specs issue.
