### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by tamalsaha** [census-instrumentation/opencensus-go#788]
We develop tools for Kubernetes. I really like the idea of vendor neutral api for metrics and traces. Currently we use the prometheus client directly. Are there any limitations of using opencensus-go client over corresponding Prometheus go client? Same goes for Jaeger client for tracing? Is anyone using this is production?

**Comment by vaijab** [comment]
I have been using this in various services without any issues.

**Comment by ramonza** [comment]
I think it depends on a lot of factors - what your use case looks like, what exporters you would like to use etc. (Gitter)[https://gitter.im/census-instrumentation/Lobby] would be a better place to discuss the details.
