### ISSUE TITLE
Is it possible to avoid create a new thread in init?

### ISSUE THREAD

**Issue by bronze1man** [census-instrumentation/opencensus-go#797]
https://github.com/census-instrumentation/opencensus-go/blob/master/stats/view/worker.go#L27
```
func init() {
	defaultWorker = newWorker()
	go defaultWorker.start()
	internal.DefaultRecorder = record
}
```

Gcp storage sdk import this package.
I have a binary that only use gcp storage sdk rarely.
I have to optimization the memory usage of my server which start 10+ processes of that binary which do not touch Gcp storage sdk.
I have to choose:
* use gcp storage sdk in another binary 
* modify this package to use lazy init function
* modify this package to require call init before the call the Gcp storage sdk.

**Comment by ramonza** [comment]
I don't think Goroutines use much more than a page (4KB in most systems, I think) of stack space to start off with and this Goroutine should not have a deep stack. Do you have measurements of how much this is increasing memory usage?

**Comment by ramonza** [comment]
Unclear what the memory concern here is. Closing.
