### ISSUE TITLE
Additional span kinds

### ISSUE THREAD

**Issue by nfisher** [census-instrumentation/opencensus-go#811]
I'm not 100% sure of the implications of this but would it make sense to add additional span kinds? Would this break assumptions of the Kind ID's in APM systems like Stackdriver?

The use-case is to provide a mechanism of course-grained filtering/highlighting in tracing tools such as Stackdriver. See;

- https://twitter.com/natbobc/status/1014924839440789505
- https://groups.google.com/forum/#!topic/google-stackdriver-discussion/BZUSwfX4NZU

The current [kinds](https://github.com/census-instrumentation/opencensus-go/blob/master/trace/trace.go#L114) are;

- SpanKindUnspecified
- SpanKindServer
- SpanKindClient

Additional kinds I could see adding are;

1. Start.
2. Stop.
3. Deployment.
4. Offline (for streaming or batch processing).
5. Ready (for /readyz state transition and/or duration).
6. Healthy (for /healthz state transition and/or duration).

The last 2 might not be appropriate for tracing though. The 3rd I'm not wedded to the name. Perhaps all of them could be grouped under 1 kind "Status".

**Comment by adriancole** [comment]
interesting idea. didnt really think about statemachine stuff as span kind.
in zipkin it only clarifies (remote) communication pattern

**Comment by ramonza** [comment]
From the external discussion, it sounds like what you really want here is a way to annotate graphs/charts with events (like deployments, incidents) that might influence the resources being monitored. IMO this is better handled by a special-purpose annotation API that could also work against Stackdriver Monitoring charts (for example). 

Either way this would be a Stackdriver feature request, so I don't think this repo is the right place to discuss this. Going to close this for now, if you are a Stackdriver customer I recommend that you reach out to their support team with this request.

**Comment by nfisher** [comment]
Thanks @ramonza! There is the question of kind for batch jobs which is “work” but doesn’t fit in an obvious way into a client/server model. Do you see that as being placed into the server kind with a tag of batch? What would happen if I used the upper range of an int for user defined kinds?

**Comment by ramonza** [comment]
@nfisher why not just use SpanKindUnspecified? Maybe the name is a little misleading but SpanKind is really only used for linking the server and client side of a request in the UI. Most spans should just be SpanKindUnspecified in my opinion.

**Comment by rakyll** [comment]
> The use-case is to provide a mechanism of course-grained filtering/highlighting in tracing tools such as Stackdriver.

This doesn't have to be done with the span kind. Span kind is a part of the span identifiers, that's why it is expressed explicitly. You can specify additional categorization through attributes. Even though Stackdriver or other backends are not currently supporting custom highlighting.
