### ISSUE TITLE
proposal: trace: allow ending spans on the remote end

### ISSUE THREAD

**Issue by nmiculinic** [census-instrumentation/opencensus-go#833]
I want to use opencensus in the pub-sub pattern and want to see end-2-end latency over the wire. 

Thus I have the producer, which uses `propagate.Binary` for span serialization.
And consumer which uses `trace.StartSpanWithRemoteParent` and `propagation.FromBinary`. 

The producer doesn't call `End` on the original span.

Roughly:
Producer:
```go
		ctx, pushSpan := trace.StartSpan(ctx, "zmq/publish_async")
		_, err = publisher.SendMessage(ob.Symbol, propagation.Binary(pushSpan.SpanContext()), buff[:n])
```

Consumer
```go
				sc, ok := propagation.FromBinary(msg[1])
				if !ok {
					log.WithError(fmt.Errorf("propagation.FromBinary not ok")).Errorln("Cannot parse span from msg")
				}
				ctx, span := trace.StartSpanWithRemoteParent(context.Background(), "zmq/handleMessage", sc, trace.WithSampler(trace.AlwaysSample()))
				...
                                span.End()

```

However in the stackdriver I cannot see parent span encompassing the child span. Not sure how to fix this.

**Comment by basvanbeek** [comment]
Yes that won't work. Census does not have a concept of shared spans between nodes. 

Unfortunately we don't have a proper story for messaging spans yet either. It is being discussed though in various places. 

For more detail see also:
https://github.com/census-instrumentation/opencensus-specs/issues/54

In Zipkin there is the concept of PRODUCER and CONSUMER span kinds which aid in this situation. I hope OpenCensus will also implement this logic.

**Comment by odeke-em** [comment]
Thank you the proposal @nmiculinic  and welcome to OpenCensus! Thank you @basvanbeek for the response.

@nmiculinic, personally I don't know OpenTracing well but I can refer some of the many experts like @basvanbeek above, @rakyll @ramonza @bogdandrutu @adriancole who might have some ideas.

**Comment by adriancole** [comment]
opentracing defines a span kind producer/consumer just like zipkin does. Main thing is that ending a stream or workflow is different than ending a span. A span is terminated where it began, even if the workflow continues in one direction. Ex in zipkin we describe the duration of message production as the time spent waiting for the message to go out.

**Comment by ramonza** [comment]
This discussion should probably happen on opencensus-specs.

**Comment by rghetia** [comment]
If more discussion is required then please open the issue on [spec repo](https://github.com/census-instrumentation/opencensus-specs).
