### ISSUE TITLE
ochttp client or handler global tags

### ISSUE THREAD

**Issue by julianvmodesto** [census-instrumentation/opencensus-go#843]
Currently, there isn't a way to provide a set of default or global tags for an ochttp handler or client. For example, I'd like to set my `span.type` tag to `web`.

**Comment by julianvmodesto** [comment]
What do you think the API for this should look like? A list of initialized tags and values? A hook to initialize the tags and values?

Could we somehow pass a context to the http handler?

**Comment by ramonza** [comment]
Any tags passed in the context before the ochttp.Handler should be effective. So you would need to install your own http.Handler wrapper around ochttp.Handler that replaces the request Context with one that contains the "global" tags.

**Comment by julianvmodesto** [comment]
Makes sense! Closing.
