### ISSUE TITLE
AddAttributes has no impact

### ISSUE THREAD

**Issue by nfisher** [census-instrumentation/opencensus-go#845]
**Describe the bug**

Current behaviour for AddAttributes seems to work as expected when used with a span created using `StartSpan`. When it is used with a span retrieved with `trace.FromContext(ctx)` where ctx is  `http.Request.Context()` the specified attributes are not attached to the span.

**To Reproduce**

1. Create a handler func registered with `http.HandleFunc`
2. Register listener with the ochttp handler `http.ListenAndServe(config.ListenAddr, &ochttp.Handler{})`
3. Add the following to the handler func in step 1;
```go
	ctx := req.Context()
	span := trace.FromContext(ctx)
	// this latency is a measurement of an in memory search algo not the request
	span.AddAttributes(trace.Int64Attribute("latency", int64(time.Now().Sub(start))))
```

**Expected behavior**

As an example this works and displays the attributes correctly with the span;

```go
	ctx := context.Background()
	ctx, span := trace.StartSpan(ctx, "catalogue/updateCatalogue")
	defer span.End()
	span.AddAttributes(
		trace.StringAttribute("operator", operator),
		trace.StringAttribute("catalogue", catalogueID),
		trace.StringAttribute("feed", catalogueFeedID),
	)
```

**Comment by nfisher** [comment]
Apologies closing... bonehead mistake on my end.

**Comment by julianvmodesto** [comment]
What was your mistake?
