### ISSUE TITLE
tests: provide mode to run on various architectures

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#868]
This feature request is a suggestion that might be very helpful: this repository is critical to many infrastructure projects and we are getting to the point where it would be beneficial to have code tested on various architectures to avoid surprises such as:
* https://github.com/census-instrumentation/opencensus-go/issues/587
* https://github.com/census-instrumentation/opencensus-go/issues/865
which were reported after users' programs crashed. Those issues manifest from bugs in Go themselves but it would be nice to catch this during development beforehand and not from users

Go allows us to test on various architectures out of the box by using `GOARCH` for say
* amd64
* 386
* arm
* arm64
etc

For example both #587 and #865 could have trivially been caught during development and by CI, by running:
```shell
GOARCH=arm go test ./...
```
and 
```shell
GOARCH=386 go test ./...
```
respectively, but also perhaps on the various architectures if we can get access to real hardware.

**Comment by ramonza** [comment]
Big +1
We should definitely do GOARCH=386, I think that will work on the existing CI hardware.
