### ISSUE TITLE
Move OC agent exporter to this repository

### ISSUE THREAD

**Issue by SergeyKanzhelev** [census-instrumentation/opencensus-go#885]
It may be a good idea to move the OCD exporter https://github.com/census-instrumentation/opencensus-service/blob/master/exporter/exporter.go to this repository as this exporter will be a default one in many cases

**Comment by adriancole** [comment]
ps probably OCD is not the best abbreviation ;)

**Comment by songy23** [comment]
This makes sense. Our plan is to update [exporter.go](https://github.com/census-instrumentation/opencensus-service/blob/master/exporter/exporter.go) to use the RPC client of the [new protocol](https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/agent/trace/v1/trace_service.proto). Ultimately the OC agent exporter/OCD exporter should be migrated to each OC library.

**Comment by rakyll** [comment]
@SergeyKanzhelev, thanks for filing this issue.

This was the initial plan but decided not to do it until the exporter is not mature. I think the current plan is to switch to the new protocol and stabilize it at https://github.com/census-ecosystem/opencensus-go-exporter-ocagent and merge it to this package.

**Comment by songy23** [comment]
Per our discussion yesterday I think the path forward is to:
- Keep OC-Agent exporter in its own repo.
- Have OC-Agent implemented both the OC-Go exporter interface and OC-Service exporter interface (https://github.com/census-instrumentation/opencensus-service/issues/339). The OC-Go exporter interface cannot have proto dependency while the OC-Service one can.

Closing this issue as this is not applicable now.

/cc @bogdandrutu @rghetia @sjkaris
