### ISSUE TITLE
Thrift import in go1.11 is broken

### ISSUE THREAD

**Issue by jeanbza** [census-instrumentation/opencensus-go#888]
## Problem

On `golang:1.11` docker image I get the following error during `go get -u` that involves opencensus:

```
# cd .; git ls-remote https://go.opencensus.io/vendor/git.apache.org/thrift
fatal: https://go.opencensus.io/vendor/git.apache.org/thrift/info/refs not valid: is this a git repository?

# cd .; git ls-remote git+ssh://go.opencensus.io/vendor/git.apache.org/thrift
ssh: connect to host go.opencensus.io port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

## Steps to reproduce

Create the following dockerfile:

```
FROM golang:1.11
RUN go get -u github.com/GoogleCloudPlatform/golang-samples/...
RUN go get -u cloud.google.com/go/profiler
RUN cd /go/src && go get -u -v ./...
```

Then run `docker build .`.

**Comment by jadekler** [comment]
Actually, that error is legit but the repro doesn't work. Re-attempting to make a repro dockerfile (without having a bunch of cruft in it)...

**Comment by jollyra** [comment]
@jadekler could you elaborate a little bit for me? I'm running into the same problem.

**Comment by jadekler** [comment]
@jollyra Basically, doing `go get -u $GOPATH/...` is non-intended usage. It's only intended as `go get <specific path to a single project>`.
