### ISSUE TITLE
Re-enable the Appveyor CI build once it's stable. 

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-go#897]
Currently the Appveyor CI build is flaky and we make it "optional" for PR merge. We should make it "required" once it's stable.

**Comment by rakyll** [comment]
Appveyor is failing due to a missing gcc error, not because of flakiness.

```
exec: "gcc": executable file not found in %PATH%
```

https://ci.appveyor.com/project/opencensusgoteam/opencensus-go/branch/master

**Comment by songy23** [comment]
Looks like the failure is resolved in https://github.com/census-instrumentation/opencensus-go/pull/907.

**Comment by ramonza** [comment]
Yup, the root cause is commented in the appveyor.yaml file
