### ISSUE TITLE
Remove godoc.org/go.opencensus.io/exporterutil

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#904]
We deprecated https://godoc.org/go.opencensus.io/exporterutil package quite a while ago and moved it under https://godoc.org/go.opencensus.io/exporter/exporterutil.

Can we now remove it?

/cc @ramonza

**Comment by ramonza** [comment]
SGTM

**Comment by bogdandrutu** [comment]
nit: Please consider https://godoc.org/go.opencensus.io/exporter/util

**Comment by rakyll** [comment]
@bogdandrutu In Go, we don't name util packages as util.

See net/http/httputil or io/ioutil.

You can read more at https://rakyll.org/style-packages/ why util packages are not preferred.

**Comment by bogdandrutu** [comment]
Thanks. You are right
