### ISSUE TITLE
trace: add support for stacktraces

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#912]
I was just going through useful signals to help distinguish a trace, I noticed in the OpenCensus Proto specs that we have a definition for StackTrace
https://github.com/census-instrumentation/opencensus-proto/blob/d3b7200dbd14743faa22c6642291d76030833cbd/src/opencensus/proto/trace/v1/trace.proto#L300-L350
<img width="943" alt="screen shot 2018-09-12 at 9 40 18 pm" src="https://user-images.githubusercontent.com/4898263/45465879-7bbb6200-b6d4-11e8-8177-0b17c4ed5fcc.png">

Perhaps we should support for stacktraces as fields of a span and provide helpers.

### Options available
* Go runtime package support
The Go runtime package provides the ability to retrieve stack frames e.g.
https://golang.org/pkg/runtime/#Frames
```go
package main

import (
	"fmt"
	"runtime"
)

func main() {
	e := func() {
		pc := make([]uintptr, 10)
		n := runtime.Callers(0, pc)
		if n == 0 {
			return
		}
		pc = pc[:n]
		frames := runtime.CallersFrames(pc)

		for {
			frame, more := frames.Next()
			fmt.Printf("- more:%v | %s\n%#v\n", more, frame.Function, frame)
			if !more {
				break
			}
		}
	}

	d := func() { e() }
	c := func() { d() }
	b := func() { c() }
	a := func() { b() }
	a()
}
```

 * Panic/Byteslice translators
In the case of panics. if users invoke recover() or they can invoke
runtime.Stack or runtime/debug.Stack and from that we can provide a translator that basically translator  an error, string, byte slice into *StackFrames e.g. in package trace
```go
func ParseStackFrames(source interface{}) (*StackFrames, error) 
```
where `StackFrames` is a translation of the proto definition

## Exporter support
Stackdriver Trace supports exporting Stacktraces https://godoc.org/google.golang.org/genproto/googleapis/devtools/cloudtrace/v2#StackTrace
and I think other APM providers would be interested in following too.

**Comment by ramonza** [comment]
I think this needs to be specified in OpenCensus specs first.

**Comment by rakyll** [comment]
We deprecated stacktrace support from OpenCensus. AFAIK, they ended up being in the proto in the first place to comply with some legacy stuff we are not interested in supporting anymore. Please open an issue at the specs repo, https://github.com/census-instrumentation/opencensus-proto, if we need to reconsider them.
