### ISSUE TITLE
New release with Tracestate propagation.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-go#913]
Some customers are requesting a new release with the `Tracestate` propagation (https://github.com/census-instrumentation/opencensus-go/pull/901).

**Comment by songy23** [comment]
A question would be should this release be a minor release (i.e `v0.17.0`) or a patch release (i.e `v0.16.1`)? I think it makes more sense to call it `v0.16.1`, since we're making regular releases every 4 weeks and [v0.16.0](https://github.com/census-instrumentation/opencensus-go/releases/tag/v0.16.0) was released just 3 days ago. Though it seems patch release is not a tradition in [Go](https://github.com/census-instrumentation/opencensus-go/releases).

**Comment by bogdandrutu** [comment]
Patch release should not include new APIs, so this should be a minor release. Unfortunately we will not wait 4 weeks but that should be fine for one time exception.
