### ISSUE TITLE
TestHandlerImplementsHTTPCloseNotify is flaky

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#926]
It occasionally fails, see the log:

```
=== RUN   TestHandlerImplementsHTTPCloseNotify
--- FAIL: TestHandlerImplementsHTTPCloseNotify (1.03s)
    server_test.go:554: HTTP2Log got
        	"ended\nended\nended\n"
        want
        	"ended\nended\nended\nended\n"
```

**Comment by odeke-em** [comment]
Thanks for this report @rakyll!

**Comment by ssgelm** [comment]
We're seeing this somewhat commonly in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921575.  @odeke-em I'm happy to help look into this.  Did you have any idea where the problem might be?

**Comment by ssgelm** [comment]
So far my best guess is that the time here needs to be increased: https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ochttp/server_test.go#L546

**Comment by ssgelm** [comment]
For example, if I set that time to zero the test will fail in that way every time.
