### ISSUE TITLE
Add Metrics APIs as per "metrics.proto" 

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-go#940]
Add Metrics package and below classes based on [metrics.proto](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/metrics/v1/metrics.proto). Although Metrics proto is still being finalized, We think it is safe to start working on value classes like LabelKey, TimeSeries, Point etc.

- [x] Metrics: Add LabelKey and LabelValue.
- [x] Metrics: Add Value and Point.
- [x] Metrics: Add TimeSeries.
- [x] Metrics: Add MetricDescriptor.
- [x] Metrics: Add Metric.
- [x] Metrics: Add Summary and Distribution.
- [x] Metrics: Produce and store Metrics in Stats impl.(#1078)

Counterpart classes available in Java for reference : https://github.com/census-instrumentation/opencensus-java/tree/master/api/src/main/java/io/opencensus/metrics

**Comment by ramonza** [comment]
At the moment, I am leaning towards relying directly on the protobuf generated classes rather than re-implementing them unless anyone has objections.

**Comment by bogdandrutu** [comment]
@ramonza we should not add a protobuf dependency on the core library (that was our decision).

**Comment by johanbrandhorst** [comment]
Will this include Go specific metrics like `gc_pause` time distributions?

**Comment by bogdandrutu** [comment]
Yes we can have that as a "contrib" package.

**Comment by rghetia** [comment]
all tasks are complete.
