### ISSUE TITLE
0.18.0 release ?

### ISSUE THREAD

**Issue by vladbarosan** [census-instrumentation/opencensus-go#954]
**Is your feature request related to a problem? Please describe.**
Hello, any expected time for releasing 0.18.0 ? We would like to start using the library for instrumentation with the new non-deprecated convenience views and also new features ( like `GetStartOptions` ). 

**Additional context**
We would like to do this without having to avoid taking a dependency on master for dep and module users.

**Comment by ramonza** [comment]
Released. Will try to keep to the two week schedule going forward.

**Comment by vladbarosan** [comment]
@ramonza awesome, thanks @ramonza
