### ISSUE TITLE
Tracing: Allow limits to be configurable.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-go#957]
According to specs: https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/TraceConfig.md#limits, limits on `Attribute`, `Annotation`, `MessageEvent` and `Link` should have default values and should be configurable. 

Currently in Go, only the `Sampler` is configurable, while we hard-coded the limits when exporting: https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/d1e19f5c23e955d7b65ff59e935007a2edce045e/trace_proto.go#L33-L35.

/cc @odeke-em

**Comment by rghetia** [comment]
fixed by #1015 #1020, #1021, #1022
