### ISSUE TITLE
should we remove support for Go 1.8?

### ISSUE THREAD

**Issue by basvanbeek** [census-instrumentation/opencensus-go#958]
Go 1.8 is not officially supported anymore and it's showing side effects due to it. Running `go lint` on travis will either fail on the old import path like this:
```
$ go get -u github.com/golang/lint/...
package github.com/golang/lint: code in directory /home/travis/gopath/src/github.com/golang/lint expects import "golang.org/x/lint"
package github.com/golang/lint/golint: code in directory /home/travis/gopath/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
```
or using the new import path we error out like this:
```
$ go get -u golang.org/x/lint/golint
# golang.org/x/tools/go/internal/gcimporter
../../../golang.org/x/tools/go/internal/gcimporter/bexport.go:212: obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)
```
I'm running into these issues with ocsql and need to either set-up a vendored linter for 1.8 or deprecate 1.8 if we don't officially support it anymore. The README of opencensus-go still lists support for 1.8 and up. According to the opencensus.io quickstart guides we're at 1.9 and up.

Another thing I noticed is that we currently only test the opencensus-go repo against 1.11 (both Travis and AppVeyor) where our travis.yml comments AppVeyor as testing 1.8 (which it doesn't).

Are we following the official Go language support schedule or are we more conservative (which I hope)? If we are, we should even deprecate support for Go 1.9 which sounds rather drastic.

@rakyll @bogdandrutu @ramonza @odeke-em

**Comment by rakyll** [comment]
We can remove the 1.8 support. If 1.8 support is a huge breaking issue for anyone, please update this issue with your concerns and see how we can help. The entire ecosystem is adopting a support model that aligns with the Go's official support model. I assume more significant components will be already broken if are already on 1.8.

**Comment by basvanbeek** [comment]
Stated requirements now at Go 1.9 or above.
