### ISSUE TITLE
exporter/zipkin: allow NewExporter to set remote endpoint

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#959]
Currently the zipkin exporter was implemented with only the ability to create a localEndpoint in the call
https://godoc.org/go.opencensus.io/exporter/zipkin#NewExporter

https://github.com/census-instrumentation/opencensus-go/blob/96e75b88df843315da521168a0e3b11792088728/exporter/zipkin/zipkin.go#L34-L50

We need the ability to add a remote endpoint if need be. That is because RemoteEndpoint https://github.com/openzipkin/zipkin-go/blob/70244c9703277c13566aac289c530a1143b14cf5/model/span.go#L39-L40 is essential when creating the service graph of elements by Zipkin later.

I am currently wrapping up the Zipkin interceptor for the OpenCensus Agent/Service in https://github.com/census-instrumentation/opencensus-service/pull/111 and the only thing lacking here is the ability to create an OpenCensus exporter that also adds the endpoint.

Since the exporter seems to have suggested optionality of the RemoteEndpoint, perhaps let's add an option `WithRemoteEndpoint` and with that always transmit one when uploading Zipkin spans to a backend.

**Comment by odeke-em** [comment]
While each SpanData could have a unique RemoteEndpoint and LocalEndpoint, this exporter's constructor seems to be usable by only one LocalEndpoint which also alludes to just using one RemoteEndpoint for parity.

A patching fix would be to interpret fields in the Attributes map e.g. "zipkin.remoteEndpoint.serviceName" or "zipkin.localEndpoint.serviceName" but that ship sailed when we made the signature for `NewExporter` take a LocalEndpoint hence for each unique localEndpoint-remoteEndpoint consumer we have to initiate a new exporter.

**Comment by basvanbeek** [comment]
It is much more common to have a sticky local endpoint (as you are describing your own service) even though Zipkin allows per span local endpoint (as you may be a proxying service or a multi homed service).
It is very uncommon for a remote endpoint to be sticky on the service level (service A always calling the same peer service B does not make a lot of sense).

**Comment by odeke-em** [comment]
@ramonza I guess so, but as is currently we won't be able to use the OpenCensus-Go Zipkin exporter so for the OpenCensus-Service thus we've reimplemented it as per https://github.com/census-instrumentation/opencensus-service/pull/145 to allow for per-span {LocalEndpoint, RemoteEndpoint} extraction and using a single exporter, and one day will eventually have to redesign the OpenCensus-Go Zipkin exporter and then bring that code here, over from the OpenCensus-Service.

**Comment by ramonza** [comment]
Let's discuss a general solution on the specs repo.
