### ISSUE TITLE
[Question] Adding tag to span in http middleware 

### ISSUE THREAD

**Issue by etsangsplk** [census-instrumentation/opencensus-go#965]
It looks like ochttp middleware already takes care of instrumenting incoming http requests for server, but for my case, we have user defined http header which I would also like to annotate to the Span created by the middlware. Is it possible to do that?
The same question about http client roundtripper. For example, for say kubernetes, we can hook the http client with your roundtripper, but if also send customer http header with it, how I attach that to the Span from the outgoing http request??

**Comment by basvanbeek** [comment]
Good question!

Please take a look at my comment in https://github.com/census-instrumentation/opencensus-go/pull/964

I’ve provided two gists (client and server side) which show the custom header annotation case. Let me know if that solution works for you.

**Comment by etsangsplk** [comment]
@basvanbeek cool thanks. 
BTW, do you happen to know the anwer to the following too?
https://github.com/census-instrumentation/opencensus-go/issues/966
