### ISSUE TITLE
[Question] What is the behaviour for zero value SpanContext?

### ISSUE THREAD

**Issue by etsangsplk** [census-instrumentation/opencensus-go#966]
For opentracing, there is Noop Tracer, noopspan, noopSpanContext
https://github.com/opentracing/opentracing-go/blob/master/noop.go

Having Noop as zero value makes it much easier to know that  even missing a nil check or when things goes bad, there is a state to fall back to and the worst is just not doing anything.

I don't think there is anything noop in opencensus, or is there? If there is one, please point me to that, would like to use that as the base case

**Comment by bogdandrutu** [comment]
@etsangsplk did you close this issue?

**Comment by bogdandrutu** [comment]
I completely agree with the fact that nil checks should not be a problem, I think the way how the library handles this is by allowing all the methods on the Span to work with nil.

**Comment by etsangsplk** [comment]
@bogdandrutu Yes I closed the issue, looks like someone answer that. But if you have more information to provide please do. Now I am playing with the ochttp middleware, I do have some more question. For example, it looks like ochttp middleware need to be the first handler in the handler chain???

**Comment by ramonza** [comment]
`Span` methods are generally tolerant of `nil` receiver. I think this is the equivalent of a no-op tracer. As for `SpanContext`, the zero value is not useful - it's just a TraceID and SpanID of all zeros.
