### ISSUE TITLE
Trace attribute vs tags difference..

### ISSUE THREAD

**Issue by etsangsplk** [census-instrumentation/opencensus-go#967]
What is the difference between Trace attributes and tags? It seems like tags are used for stats but attributes is the only one settable for span.
But in plugin/ochttp, tags are used for routes to context before sending downstream. What at are the guidelines of when to use tags vs attributes?

**Comment by odeke-em** [comment]
PS: in the future, for general concepts, please feel free to ask on the community based Gitter channel https://gitter.im/census-instrumentation/Lobby as these language specific repos are for bugs

**Comment by odeke-em** [comment]
>Thanks. The reason why I have to confirm is that I come from opentracing background. They uses Tag as attributes here. Until I see some explorer (e.g. jaeger explorer that does the translation) and the source code for the library, I can't be 100% sure.

@etsangsplk OpenCensus is different from OpenTracing as you've probably already noticed and I hope that that answered your question?

**Comment by ramonza** [comment]
Closing since this doesn't seem like an actionable issue for OpenCensus Go.
