### ISSUE TITLE
Exporters should be able to intercept `addSample`

### ISSUE THREAD

**Issue by postwait** [census-instrumentation/opencensus-go#970]
The distribution data in the default implementation is slow for robust histogram binning (with thousands of bins).  Ideally, an exporter would be able to intercept (or subscribe to) the addSample calls (and other calls to record measurements so they can provide a richer perspective than the current "view".

There are a variety of distribution-centric online calculations (from moment sketches to modal extractions, to advanced/HDR/dynamic binning) that can only be done if the exporter can see the source data being measured.

Ideally, when registering an exporter, it can optionally hook into/subscribe to the recording layer.

**Comment by postwait** [comment]
Please let me know if this is what you had in mind?

https://github.com/census-instrumentation/opencensus-specs/issues/216

**Comment by rghetia** [comment]
it is already tracked under spec repo.
