### ISSUE TITLE
Opencensus support in go-redis with a wrapper

### ISSUE THREAD

**Issue by edevil** [census-instrumentation/opencensus-go#976]
**Is your feature request related to a problem? Please describe.**
Currently there is a fork of https://github.com/go-redis/redis with opencensus integration in https://github.com/opencensus-integrations/redis. However, this fork has not seen activity in several months, and is already some versions behind the upstream version.

The nature of the [changes](https://github.com/opencensus-integrations/redis/pull/1) also make it unlikely that they will be merged upstream. I've tried backporting the new stuff but there are several conflicts and it looks like an uphill battle.

**Describe the solution you'd like**
I think the best way to support the go-redis driver is with a wrapper around it's interface. Are there plans to do this?

**Comment by odeke-em** [comment]
@edevil thank you filing this issue!

Unfortunately OpenCensus Go isn't for integrations and I got feedback from various folks that the better direction is to make a wrapper instead as you've noticed. We just need to find the time to work on it. If you'd like, we can collaborate it and I can help with code review, otherwise yes I plan on rolling a wrapper out but I just have a lot currently on my backlog.

I'll close this issue since that's an issue for a different repo but let's keep the conversation active on that repo or via email and collaboration.

**Comment by odeke-em** [comment]
@edevil now I recall I actually worked on a wrapper about 8 months ago as recommended by goredis/redis in https://github.com/orijtech/go-opencensus-integrations/blob/da8b4420d3d3e41250e3dc1d87cf5449d6af1670/ocredis/example_test.go#L40-L103
```go
func Example_NewClient() {
	// Just some pre-requisites to demo the interaction
	// between OpenCensus and the integration.
	trace.ApplyConfig(trace.Config{DefaultSampler: trace.AlwaysSample()})
	trace.RegisterExporter(pe)
	defer trace.UnregisterExporter(pe)

	// Create and use the client
	client := ocredis.NewClient(context.Background(), ":6379")
	if _, err := client.HSet("programs", "space", 1961).Result(); err != nil {
		log.Fatalf("HSet error: %v", err)
	}
}
```
or 
```go
func Example_PerCommandTracer() {
	// Just some pre-requisites to demo the interaction
	// between OpenCensus and the integration.
	trace.ApplyConfig(trace.Config{DefaultSampler: trace.AlwaysSample()})
	trace.RegisterExporter(pe)
	defer trace.UnregisterExporter(pe)

	client := redis.NewClient(&redis.Options{Addr: ":6379"})
	client.WrapProcess(ocredis.PerCommandTracer(context.Background()))
	_, err := client.HMSet("names", map[string]interface{}{
		"space": 1961, "tracing": "OpenCensus",
		"monitoring": "OpenCensus",
	}).Result()
	if err != nil {
		log.Fatalf("Failed to HMSet: %v", err)
	}
}
```

which provides the wrapper -- so basically this is already implemented.

However, I personally found that I couldn't get annotations from it hence went to the full instrumentation.

**Comment by edevil** [comment]
@odeke-em Got it. But which is the correct repo to discuss this?

**Comment by odeke-em** [comment]
@edevil I just commented as you were typing that we actually have what you are looking for, the implemented wrapper https://github.com/orijtech/go-opencensus-integrations/tree/master/ocredis :)

**Comment by edevil** [comment]
Thanks!

**Comment by edevil** [comment]
@odeke-em The downside of using WrapProcess() is that you cannot pass a context per-command, right? In situations in which you have a shared long-lived redis client that you use multiple times while servicing a request it is not possible to attach the spans to the request's context.

**Comment by edevil** [comment]
@odeke-em A middle-ground that I found was to use the WrapProcess() approach you showed and then create a copy of the redis client per-request:

```go
func WrapClient(ctx context.Context, origClient *redis.Client) *redis.Client {
	client := origClient.WithContext(ctx)
	client.WrapProcess(PerCommandTracer(client.Context()))
	return client
}
```

```go
	client := common.WrapClient(ctx, genericRedisClient)
	result, err := client.Get(key).Result()
```

**Comment by odeke-em** [comment]
@edevil nice! Could you please file an issue or send a PR to https://github.com/orijtech/go-opencensus-integrations. I am currently doing a retouch to ensure that we don't encounter any problems of discovery but also ensure everyone can use them easily.
