### ISSUE TITLE
zpages: missing statz endpoint

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#984]
/statz is implemented in OpenCensus-Java https://opencensus.io/zpages/java/#statz but not in OpenCensus-Go. While helping an OpenCensus user over the week, we encountered a need for /statz and they looked at the Java documentation and found it but not for Go which they needed.

**Comment by songy23** [comment]
There's already an issue there: https://github.com/census-instrumentation/opencensus-go/issues/473.

**Comment by odeke-em** [comment]
Oh cool, thank you for letting me know @songy23! I'll update that title to make it easy to grok and find.
