### ISSUE TITLE
release: v0.19.0

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#998]
Coming here from https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/issues/38
we recently imported the new resource package into ocagent-go-exporter but unfortunately a v0.19.0 release hasn't yet been made here hence we can't update our Go modules.

/cc @bogdandrutu @rakyll

**Comment by songy23** [comment]
Also cc @rghetia for Go releases.

**Comment by bcmills** [comment]
> hence we can't update our Go modules.

Note that you can request pre-release versions explicitly: `go get go.opencensus.io@master` currently resolves to a pseudo-version starting with `v0.18.1-0.`.

**Comment by sagikazarmark** [comment]
0.19.0 has been released.

**Comment by odeke-em** [comment]
>Note that you can request pre-release versions explicitly: go get go.opencensus.io@master currently resolves to a pseudo-version starting with v0.18.1-0..

Thank you @bcmills for the help with that!

>0.19.0 has been released.

Thank you @sagikazarmark for the ping!
